/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Enums.Cir
{

    /// <summary>
    /// Gets or Sets SendToCir
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SendToCir
    {
        /// <summary>
        /// Enum NoEnum for No
        /// </summary>
        [EnumMember(Value = "No")]
        NoEnum = 0,
        /// <summary>
        /// Enum YesEnum for Yes
        /// </summary>
        [EnumMember(Value = "Yes")]
        YesEnum = 1
    }
}
