/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using eFaktureModel.Api.Models.Vat;

namespace eFaktureModel.Api.Models.Sales
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SalesInvoiceTotalPaymentsCalculationDto : IEquatable<SalesInvoiceTotalPaymentsCalculationDto>
    {
        /// <summary>
        /// Gets or Sets TotalPayments
        /// </summary>

        [DataMember(Name = "totalPayments")]
        public double? TotalPayments { get; set; }

        /// <summary>
        /// Gets or Sets PaymentFeeForVatCategories
        /// </summary>

        [DataMember(Name = "paymentFeeForVatCategories")]
        public List<VatCategoryDetailsDto> PaymentFeeForVatCategories { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SalesInvoiceTotalPaymentsCalculationDto {\n");
            sb.Append("  TotalPayments: ").Append(TotalPayments).Append("\n");
            sb.Append("  PaymentFeeForVatCategories: ").Append(PaymentFeeForVatCategories).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SalesInvoiceTotalPaymentsCalculationDto)obj);
        }

        /// <summary>
        /// Returns true if SalesInvoiceTotalPaymentsCalculationDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SalesInvoiceTotalPaymentsCalculationDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SalesInvoiceTotalPaymentsCalculationDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    TotalPayments == other.TotalPayments ||
                    TotalPayments != null &&
                    TotalPayments.Equals(other.TotalPayments)
                ) &&
                (
                    PaymentFeeForVatCategories == other.PaymentFeeForVatCategories ||
                    PaymentFeeForVatCategories != null &&
                    PaymentFeeForVatCategories.SequenceEqual(other.PaymentFeeForVatCategories)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (TotalPayments != null)
                    hashCode = hashCode * 59 + TotalPayments.GetHashCode();
                if (PaymentFeeForVatCategories != null)
                    hashCode = hashCode * 59 + PaymentFeeForVatCategories.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SalesInvoiceTotalPaymentsCalculationDto left, SalesInvoiceTotalPaymentsCalculationDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SalesInvoiceTotalPaymentsCalculationDto left, SalesInvoiceTotalPaymentsCalculationDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
