/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Sales
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SalesLineItemAllowanceDto : IEquatable<SalesLineItemAllowanceDto>
    {
        /// <summary>
        /// Gets or Sets SalesLineItemAllowanceId
        /// </summary>

        [DataMember(Name = "salesLineItemAllowanceId")]
        public long? SalesLineItemAllowanceId { get; set; }

        /// <summary>
        /// Gets or Sets SalesLineItemId
        /// </summary>

        [DataMember(Name = "salesLineItemId")]
        public long? SalesLineItemId { get; set; }

        /// <summary>
        /// Gets or Sets BaseAmount
        /// </summary>

        [DataMember(Name = "baseAmount")]
        public double? BaseAmount { get; set; }

        /// <summary>
        /// Gets or Sets Percentage
        /// </summary>

        [DataMember(Name = "percentage")]
        public double? Percentage { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>

        [DataMember(Name = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// Gets or Sets ReasonCode
        /// </summary>

        [DataMember(Name = "reasonCode")]
        public string ReasonCode { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>

        [DataMember(Name = "reason")]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SalesLineItemAllowanceDto {\n");
            sb.Append("  SalesLineItemAllowanceId: ").Append(SalesLineItemAllowanceId).Append("\n");
            sb.Append("  SalesLineItemId: ").Append(SalesLineItemId).Append("\n");
            sb.Append("  BaseAmount: ").Append(BaseAmount).Append("\n");
            sb.Append("  Percentage: ").Append(Percentage).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ReasonCode: ").Append(ReasonCode).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SalesLineItemAllowanceDto)obj);
        }

        /// <summary>
        /// Returns true if SalesLineItemAllowanceDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SalesLineItemAllowanceDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SalesLineItemAllowanceDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    SalesLineItemAllowanceId == other.SalesLineItemAllowanceId ||
                    SalesLineItemAllowanceId != null &&
                    SalesLineItemAllowanceId.Equals(other.SalesLineItemAllowanceId)
                ) &&
                (
                    SalesLineItemId == other.SalesLineItemId ||
                    SalesLineItemId != null &&
                    SalesLineItemId.Equals(other.SalesLineItemId)
                ) &&
                (
                    BaseAmount == other.BaseAmount ||
                    BaseAmount != null &&
                    BaseAmount.Equals(other.BaseAmount)
                ) &&
                (
                    Percentage == other.Percentage ||
                    Percentage != null &&
                    Percentage.Equals(other.Percentage)
                ) &&
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) &&
                (
                    ReasonCode == other.ReasonCode ||
                    ReasonCode != null &&
                    ReasonCode.Equals(other.ReasonCode)
                ) &&
                (
                    Reason == other.Reason ||
                    Reason != null &&
                    Reason.Equals(other.Reason)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (SalesLineItemAllowanceId != null)
                    hashCode = hashCode * 59 + SalesLineItemAllowanceId.GetHashCode();
                if (SalesLineItemId != null)
                    hashCode = hashCode * 59 + SalesLineItemId.GetHashCode();
                if (BaseAmount != null)
                    hashCode = hashCode * 59 + BaseAmount.GetHashCode();
                if (Percentage != null)
                    hashCode = hashCode * 59 + Percentage.GetHashCode();
                if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                if (ReasonCode != null)
                    hashCode = hashCode * 59 + ReasonCode.GetHashCode();
                if (Reason != null)
                    hashCode = hashCode * 59 + Reason.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SalesLineItemAllowanceDto left, SalesLineItemAllowanceDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SalesLineItemAllowanceDto left, SalesLineItemAllowanceDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
