/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Sales
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SalesIndividualPrepaymentCalculationVatPerRateParametersDto : IEquatable<SalesIndividualPrepaymentCalculationVatPerRateParametersDto>
    {
        /// <summary>
        /// Gets or Sets PrepaymentCalculationVatPerRateParametersId
        /// </summary>

        [DataMember(Name = "prepaymentCalculationVatPerRateParametersId")]
        public long? PrepaymentCalculationVatPerRateParametersId { get; set; }

        /// <summary>
        /// Gets or Sets VatRate
        /// </summary>

        [DataMember(Name = "vatRate")]
        public double? VatRate { get; set; }

        /// <summary>
        /// Gets or Sets PrepaymentVatBaseReduction
        /// </summary>

        [DataMember(Name = "prepaymentVatBaseReduction")]
        public double? PrepaymentVatBaseReduction { get; set; }

        /// <summary>
        /// Gets or Sets PrepaidVatPerRate
        /// </summary>

        [DataMember(Name = "prepaidVatPerRate")]
        public double? PrepaidVatPerRate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SalesIndividualPrepaymentCalculationVatPerRateParametersDto {\n");
            sb.Append("  PrepaymentCalculationVatPerRateParametersId: ").Append(PrepaymentCalculationVatPerRateParametersId).Append("\n");
            sb.Append("  VatRate: ").Append(VatRate).Append("\n");
            sb.Append("  PrepaymentVatBaseReduction: ").Append(PrepaymentVatBaseReduction).Append("\n");
            sb.Append("  PrepaidVatPerRate: ").Append(PrepaidVatPerRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SalesIndividualPrepaymentCalculationVatPerRateParametersDto)obj);
        }

        /// <summary>
        /// Returns true if SalesIndividualPrepaymentCalculationVatPerRateParametersDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SalesIndividualPrepaymentCalculationVatPerRateParametersDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SalesIndividualPrepaymentCalculationVatPerRateParametersDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PrepaymentCalculationVatPerRateParametersId == other.PrepaymentCalculationVatPerRateParametersId ||
                    PrepaymentCalculationVatPerRateParametersId != null &&
                    PrepaymentCalculationVatPerRateParametersId.Equals(other.PrepaymentCalculationVatPerRateParametersId)
                ) &&
                (
                    VatRate == other.VatRate ||
                    VatRate != null &&
                    VatRate.Equals(other.VatRate)
                ) &&
                (
                    PrepaymentVatBaseReduction == other.PrepaymentVatBaseReduction ||
                    PrepaymentVatBaseReduction != null &&
                    PrepaymentVatBaseReduction.Equals(other.PrepaymentVatBaseReduction)
                ) &&
                (
                    PrepaidVatPerRate == other.PrepaidVatPerRate ||
                    PrepaidVatPerRate != null &&
                    PrepaidVatPerRate.Equals(other.PrepaidVatPerRate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (PrepaymentCalculationVatPerRateParametersId != null)
                    hashCode = hashCode * 59 + PrepaymentCalculationVatPerRateParametersId.GetHashCode();
                if (VatRate != null)
                    hashCode = hashCode * 59 + VatRate.GetHashCode();
                if (PrepaymentVatBaseReduction != null)
                    hashCode = hashCode * 59 + PrepaymentVatBaseReduction.GetHashCode();
                if (PrepaidVatPerRate != null)
                    hashCode = hashCode * 59 + PrepaidVatPerRate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SalesIndividualPrepaymentCalculationVatPerRateParametersDto left, SalesIndividualPrepaymentCalculationVatPerRateParametersDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SalesIndividualPrepaymentCalculationVatPerRateParametersDto left, SalesIndividualPrepaymentCalculationVatPerRateParametersDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
