/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AcceptRejectPurchaseInvoiceByCirInvoiceId : IEquatable<AcceptRejectPurchaseInvoiceByCirInvoiceId>
    { 
        /// <summary>
        /// Gets or Sets CirInvoiceId
        /// </summary>

        [DataMember(Name="cirInvoiceId")]
        public string CirInvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets Accepted
        /// </summary>

        [DataMember(Name="accepted")]
        public bool? Accepted { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>

        [DataMember(Name="comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AcceptRejectPurchaseInvoiceByCirInvoiceId {\n");
            sb.Append("  CirInvoiceId: ").Append(CirInvoiceId).Append("\n");
            sb.Append("  Accepted: ").Append(Accepted).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AcceptRejectPurchaseInvoiceByCirInvoiceId)obj);
        }

        /// <summary>
        /// Returns true if AcceptRejectPurchaseInvoiceByCirInvoiceId instances are equal
        /// </summary>
        /// <param name="other">Instance of AcceptRejectPurchaseInvoiceByCirInvoiceId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AcceptRejectPurchaseInvoiceByCirInvoiceId other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CirInvoiceId == other.CirInvoiceId ||
                    CirInvoiceId != null &&
                    CirInvoiceId.Equals(other.CirInvoiceId)
                ) && 
                (
                    Accepted == other.Accepted ||
                    Accepted != null &&
                    Accepted.Equals(other.Accepted)
                ) && 
                (
                    Comment == other.Comment ||
                    Comment != null &&
                    Comment.Equals(other.Comment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CirInvoiceId != null)
                    hashCode = hashCode * 59 + CirInvoiceId.GetHashCode();
                    if (Accepted != null)
                    hashCode = hashCode * 59 + Accepted.GetHashCode();
                    if (Comment != null)
                    hashCode = hashCode * 59 + Comment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AcceptRejectPurchaseInvoiceByCirInvoiceId left, AcceptRejectPurchaseInvoiceByCirInvoiceId right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AcceptRejectPurchaseInvoiceByCirInvoiceId left, AcceptRejectPurchaseInvoiceByCirInvoiceId right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
