/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AssignmentDto : IEquatable<AssignmentDto>
    { 
        /// <summary>
        /// Gets or Sets AssignmentContractNr
        /// </summary>

        [DataMember(Name="assignmentContractNr")]
        public string AssignmentContractNr { get; set; }

        /// <summary>
        /// Gets or Sets AssignmentDebtorName
        /// </summary>

        [DataMember(Name="assignmentDebtorName")]
        public string AssignmentDebtorName { get; set; }

        /// <summary>
        /// Gets or Sets AssignmentDebtorCompanyNr
        /// </summary>

        [DataMember(Name="assignmentDebtorCompanyNr")]
        public string AssignmentDebtorCompanyNr { get; set; }

        /// <summary>
        /// Gets or Sets AssignmentIdfNr
        /// </summary>

        [DataMember(Name="assignmentIdfNr")]
        public string AssignmentIdfNr { get; set; }

        /// <summary>
        /// Gets or Sets OriginalIdfNr
        /// </summary>

        [DataMember(Name="originalIdfNr")]
        public string OriginalIdfNr { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssignmentDto {\n");
            sb.Append("  AssignmentContractNr: ").Append(AssignmentContractNr).Append("\n");
            sb.Append("  AssignmentDebtorName: ").Append(AssignmentDebtorName).Append("\n");
            sb.Append("  AssignmentDebtorCompanyNr: ").Append(AssignmentDebtorCompanyNr).Append("\n");
            sb.Append("  AssignmentIdfNr: ").Append(AssignmentIdfNr).Append("\n");
            sb.Append("  OriginalIdfNr: ").Append(OriginalIdfNr).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AssignmentDto)obj);
        }

        /// <summary>
        /// Returns true if AssignmentDto instances are equal
        /// </summary>
        /// <param name="other">Instance of AssignmentDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssignmentDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AssignmentContractNr == other.AssignmentContractNr ||
                    AssignmentContractNr != null &&
                    AssignmentContractNr.Equals(other.AssignmentContractNr)
                ) && 
                (
                    AssignmentDebtorName == other.AssignmentDebtorName ||
                    AssignmentDebtorName != null &&
                    AssignmentDebtorName.Equals(other.AssignmentDebtorName)
                ) && 
                (
                    AssignmentDebtorCompanyNr == other.AssignmentDebtorCompanyNr ||
                    AssignmentDebtorCompanyNr != null &&
                    AssignmentDebtorCompanyNr.Equals(other.AssignmentDebtorCompanyNr)
                ) && 
                (
                    AssignmentIdfNr == other.AssignmentIdfNr ||
                    AssignmentIdfNr != null &&
                    AssignmentIdfNr.Equals(other.AssignmentIdfNr)
                ) && 
                (
                    OriginalIdfNr == other.OriginalIdfNr ||
                    OriginalIdfNr != null &&
                    OriginalIdfNr.Equals(other.OriginalIdfNr)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AssignmentContractNr != null)
                    hashCode = hashCode * 59 + AssignmentContractNr.GetHashCode();
                    if (AssignmentDebtorName != null)
                    hashCode = hashCode * 59 + AssignmentDebtorName.GetHashCode();
                    if (AssignmentDebtorCompanyNr != null)
                    hashCode = hashCode * 59 + AssignmentDebtorCompanyNr.GetHashCode();
                    if (AssignmentIdfNr != null)
                    hashCode = hashCode * 59 + AssignmentIdfNr.GetHashCode();
                    if (OriginalIdfNr != null)
                    hashCode = hashCode * 59 + OriginalIdfNr.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AssignmentDto left, AssignmentDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AssignmentDto left, AssignmentDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
