/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CirHistoryDto : IEquatable<CirHistoryDto>
    { 
        /// <summary>
        /// Gets or Sets Comment
        /// </summary>

        [DataMember(Name="comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets Assignment
        /// </summary>

        [DataMember(Name="assignment")]
        public AssignmentDto Assignment { get; set; }

        /// <summary>
        /// Gets or Sets AmountChanges
        /// </summary>

        [DataMember(Name="amountChanges")]
        public List<AmountChangeDto> AmountChanges { get; set; }

        /// <summary>
        /// Gets or Sets Cancellation
        /// </summary>

        [DataMember(Name="cancellation")]
        public CancellationDto Cancellation { get; set; }

        /// <summary>
        /// Gets or Sets Settlements
        /// </summary>

        [DataMember(Name="settlements")]
        public List<SettlementDto> Settlements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CirHistoryDto {\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Assignment: ").Append(Assignment).Append("\n");
            sb.Append("  AmountChanges: ").Append(AmountChanges).Append("\n");
            sb.Append("  Cancellation: ").Append(Cancellation).Append("\n");
            sb.Append("  Settlements: ").Append(Settlements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CirHistoryDto)obj);
        }

        /// <summary>
        /// Returns true if CirHistoryDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CirHistoryDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CirHistoryDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Comment == other.Comment ||
                    Comment != null &&
                    Comment.Equals(other.Comment)
                ) && 
                (
                    Assignment == other.Assignment ||
                    Assignment != null &&
                    Assignment.Equals(other.Assignment)
                ) && 
                (
                    AmountChanges == other.AmountChanges ||
                    AmountChanges != null &&
                    AmountChanges.SequenceEqual(other.AmountChanges)
                ) && 
                (
                    Cancellation == other.Cancellation ||
                    Cancellation != null &&
                    Cancellation.Equals(other.Cancellation)
                ) && 
                (
                    Settlements == other.Settlements ||
                    Settlements != null &&
                    Settlements.SequenceEqual(other.Settlements)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Comment != null)
                    hashCode = hashCode * 59 + Comment.GetHashCode();
                    if (Assignment != null)
                    hashCode = hashCode * 59 + Assignment.GetHashCode();
                    if (AmountChanges != null)
                    hashCode = hashCode * 59 + AmountChanges.GetHashCode();
                    if (Cancellation != null)
                    hashCode = hashCode * 59 + Cancellation.GetHashCode();
                    if (Settlements != null)
                    hashCode = hashCode * 59 + Settlements.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CirHistoryDto left, CirHistoryDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CirHistoryDto left, CirHistoryDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
