/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// Gets or Sets CirInvoiceStatus
          /// </summary>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum CirInvoiceStatus
          {
              /// <summary>
              /// Enum NoneEnum for None
              /// </summary>
              [EnumMember(Value = "None")]
              NoneEnum = 0,
              /// <summary>
              /// Enum ActiveCirEnum for ActiveCir
              /// </summary>
              [EnumMember(Value = "ActiveCir")]
              ActiveCirEnum = 1,
              /// <summary>
              /// Enum InvalidCirEnum for InvalidCir
              /// </summary>
              [EnumMember(Value = "InvalidCir")]
              InvalidCirEnum = 2,
              /// <summary>
              /// Enum CancelledCirEnum for CancelledCir
              /// </summary>
              [EnumMember(Value = "CancelledCir")]
              CancelledCirEnum = 3,
              /// <summary>
              /// Enum PartiallySettledEnum for PartiallySettled
              /// </summary>
              [EnumMember(Value = "PartiallySettled")]
              PartiallySettledEnum = 4,
              /// <summary>
              /// Enum SettledEnum for Settled
              /// </summary>
              [EnumMember(Value = "Settled")]
              SettledEnum = 5,
              /// <summary>
              /// Enum AssignedEnum for Assigned
              /// </summary>
              [EnumMember(Value = "Assigned")]
              AssignedEnum = 6,
              /// <summary>
              /// Enum ProinvoiceEnum for Proinvoice
              /// </summary>
              [EnumMember(Value = "Proinvoice")]
              ProinvoiceEnum = 7,
              /// <summary>
              /// Enum CIRStatusSyncErrorEnum for CIRStatusSyncError
              /// </summary>
              [EnumMember(Value = "CIRStatusSyncError")]
              CIRStatusSyncErrorEnum = 8          }
}
