/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CompanySettingsDto : IEquatable<CompanySettingsDto>
    { 
        /// <summary>
        /// Gets or Sets HomeRoute
        /// </summary>

        [DataMember(Name="homeRoute")]
        public string HomeRoute { get; set; }

        /// <summary>
        /// Gets or Sets Modules
        /// </summary>

        [DataMember(Name="modules")]
        public List<SspModules> Modules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompanySettingsDto {\n");
            sb.Append("  HomeRoute: ").Append(HomeRoute).Append("\n");
            sb.Append("  Modules: ").Append(Modules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CompanySettingsDto)obj);
        }

        /// <summary>
        /// Returns true if CompanySettingsDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CompanySettingsDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompanySettingsDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    HomeRoute == other.HomeRoute ||
                    HomeRoute != null &&
                    HomeRoute.Equals(other.HomeRoute)
                ) && 
                (
                    Modules == other.Modules ||
                    Modules != null &&
                    Modules.SequenceEqual(other.Modules)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (HomeRoute != null)
                    hashCode = hashCode * 59 + HomeRoute.GetHashCode();
                    if (Modules != null)
                    hashCode = hashCode * 59 + Modules.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CompanySettingsDto left, CompanySettingsDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CompanySettingsDto left, CompanySettingsDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
