/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CustomsDeclarationItemDto : IEquatable<CustomsDeclarationItemDto>
    { 
        /// <summary>
        /// Gets or Sets Value
        /// </summary>

        [DataMember(Name="value")]
        public double? Value { get; set; }

        /// <summary>
        /// Gets or Sets ExNum
        /// </summary>

        [DataMember(Name="exNum")]
        public string ExNum { get; set; }

        /// <summary>
        /// Gets or Sets OrdinalNumber
        /// </summary>

        [DataMember(Name="ordinalNumber")]
        public int? OrdinalNumber { get; set; }

        /// <summary>
        /// Gets or Sets BindingTariffReferenceValue
        /// </summary>

        [DataMember(Name="bindingTariffReferenceValue")]
        public double? BindingTariffReferenceValue { get; set; }

        /// <summary>
        /// Gets or Sets TaxExemptionCode
        /// </summary>

        [DataMember(Name="taxExemptionCode")]
        public string TaxExemptionCode { get; set; }

        /// <summary>
        /// Gets or Sets TaxExemptionMinFinCode
        /// </summary>

        [DataMember(Name="taxExemptionMinFinCode")]
        public string TaxExemptionMinFinCode { get; set; }

        /// <summary>
        /// Gets or Sets OriginCountryCode
        /// </summary>

        [DataMember(Name="originCountryCode")]
        public string OriginCountryCode { get; set; }

        /// <summary>
        /// Gets or Sets TaxExemptionReasonCode
        /// </summary>

        [DataMember(Name="taxExemptionReasonCode")]
        public string TaxExemptionReasonCode { get; set; }

        /// <summary>
        /// Gets or Sets SysDate
        /// </summary>

        [DataMember(Name="sysDate")]
        public DateTime? SysDate { get; set; }

        /// <summary>
        /// Gets or Sets CustomsDeclarationItemDocuments
        /// </summary>

        [DataMember(Name="customsDeclarationItemDocuments")]
        public List<CustomsDeclarationItemDocumentDto> CustomsDeclarationItemDocuments { get; set; }

        /// <summary>
        /// Gets or Sets CustomsDeclarationItemDuties
        /// </summary>

        [DataMember(Name="customsDeclarationItemDuties")]
        public List<CustomsDeclarationItemDutyDto> CustomsDeclarationItemDuties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomsDeclarationItemDto {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  ExNum: ").Append(ExNum).Append("\n");
            sb.Append("  OrdinalNumber: ").Append(OrdinalNumber).Append("\n");
            sb.Append("  BindingTariffReferenceValue: ").Append(BindingTariffReferenceValue).Append("\n");
            sb.Append("  TaxExemptionCode: ").Append(TaxExemptionCode).Append("\n");
            sb.Append("  TaxExemptionMinFinCode: ").Append(TaxExemptionMinFinCode).Append("\n");
            sb.Append("  OriginCountryCode: ").Append(OriginCountryCode).Append("\n");
            sb.Append("  TaxExemptionReasonCode: ").Append(TaxExemptionReasonCode).Append("\n");
            sb.Append("  SysDate: ").Append(SysDate).Append("\n");
            sb.Append("  CustomsDeclarationItemDocuments: ").Append(CustomsDeclarationItemDocuments).Append("\n");
            sb.Append("  CustomsDeclarationItemDuties: ").Append(CustomsDeclarationItemDuties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CustomsDeclarationItemDto)obj);
        }

        /// <summary>
        /// Returns true if CustomsDeclarationItemDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CustomsDeclarationItemDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomsDeclarationItemDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.Equals(other.Value)
                ) && 
                (
                    ExNum == other.ExNum ||
                    ExNum != null &&
                    ExNum.Equals(other.ExNum)
                ) && 
                (
                    OrdinalNumber == other.OrdinalNumber ||
                    OrdinalNumber != null &&
                    OrdinalNumber.Equals(other.OrdinalNumber)
                ) && 
                (
                    BindingTariffReferenceValue == other.BindingTariffReferenceValue ||
                    BindingTariffReferenceValue != null &&
                    BindingTariffReferenceValue.Equals(other.BindingTariffReferenceValue)
                ) && 
                (
                    TaxExemptionCode == other.TaxExemptionCode ||
                    TaxExemptionCode != null &&
                    TaxExemptionCode.Equals(other.TaxExemptionCode)
                ) && 
                (
                    TaxExemptionMinFinCode == other.TaxExemptionMinFinCode ||
                    TaxExemptionMinFinCode != null &&
                    TaxExemptionMinFinCode.Equals(other.TaxExemptionMinFinCode)
                ) && 
                (
                    OriginCountryCode == other.OriginCountryCode ||
                    OriginCountryCode != null &&
                    OriginCountryCode.Equals(other.OriginCountryCode)
                ) && 
                (
                    TaxExemptionReasonCode == other.TaxExemptionReasonCode ||
                    TaxExemptionReasonCode != null &&
                    TaxExemptionReasonCode.Equals(other.TaxExemptionReasonCode)
                ) && 
                (
                    SysDate == other.SysDate ||
                    SysDate != null &&
                    SysDate.Equals(other.SysDate)
                ) && 
                (
                    CustomsDeclarationItemDocuments == other.CustomsDeclarationItemDocuments ||
                    CustomsDeclarationItemDocuments != null &&
                    CustomsDeclarationItemDocuments.SequenceEqual(other.CustomsDeclarationItemDocuments)
                ) && 
                (
                    CustomsDeclarationItemDuties == other.CustomsDeclarationItemDuties ||
                    CustomsDeclarationItemDuties != null &&
                    CustomsDeclarationItemDuties.SequenceEqual(other.CustomsDeclarationItemDuties)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (ExNum != null)
                    hashCode = hashCode * 59 + ExNum.GetHashCode();
                    if (OrdinalNumber != null)
                    hashCode = hashCode * 59 + OrdinalNumber.GetHashCode();
                    if (BindingTariffReferenceValue != null)
                    hashCode = hashCode * 59 + BindingTariffReferenceValue.GetHashCode();
                    if (TaxExemptionCode != null)
                    hashCode = hashCode * 59 + TaxExemptionCode.GetHashCode();
                    if (TaxExemptionMinFinCode != null)
                    hashCode = hashCode * 59 + TaxExemptionMinFinCode.GetHashCode();
                    if (OriginCountryCode != null)
                    hashCode = hashCode * 59 + OriginCountryCode.GetHashCode();
                    if (TaxExemptionReasonCode != null)
                    hashCode = hashCode * 59 + TaxExemptionReasonCode.GetHashCode();
                    if (SysDate != null)
                    hashCode = hashCode * 59 + SysDate.GetHashCode();
                    if (CustomsDeclarationItemDocuments != null)
                    hashCode = hashCode * 59 + CustomsDeclarationItemDocuments.GetHashCode();
                    if (CustomsDeclarationItemDuties != null)
                    hashCode = hashCode * 59 + CustomsDeclarationItemDuties.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CustomsDeclarationItemDto left, CustomsDeclarationItemDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CustomsDeclarationItemDto left, CustomsDeclarationItemDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
