/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CustomsDeclarationItemDocumentDto : IEquatable<CustomsDeclarationItemDocumentDto>
    { 
        /// <summary>
        /// Gets or Sets DocumentCode
        /// </summary>

        [DataMember(Name="documentCode")]
        public string DocumentCode { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyCode
        /// </summary>

        [DataMember(Name="currencyCode")]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets OrdinalNumber
        /// </summary>

        [DataMember(Name="ordinalNumber")]
        public int? OrdinalNumber { get; set; }

        /// <summary>
        /// Gets or Sets DocumentValue
        /// </summary>

        [DataMember(Name="documentValue")]
        public double? DocumentValue { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalInfo
        /// </summary>

        [DataMember(Name="additionalInfo")]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomsDeclarationItemDocumentDto {\n");
            sb.Append("  DocumentCode: ").Append(DocumentCode).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  OrdinalNumber: ").Append(OrdinalNumber).Append("\n");
            sb.Append("  DocumentValue: ").Append(DocumentValue).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CustomsDeclarationItemDocumentDto)obj);
        }

        /// <summary>
        /// Returns true if CustomsDeclarationItemDocumentDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CustomsDeclarationItemDocumentDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomsDeclarationItemDocumentDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DocumentCode == other.DocumentCode ||
                    DocumentCode != null &&
                    DocumentCode.Equals(other.DocumentCode)
                ) && 
                (
                    CurrencyCode == other.CurrencyCode ||
                    CurrencyCode != null &&
                    CurrencyCode.Equals(other.CurrencyCode)
                ) && 
                (
                    OrdinalNumber == other.OrdinalNumber ||
                    OrdinalNumber != null &&
                    OrdinalNumber.Equals(other.OrdinalNumber)
                ) && 
                (
                    DocumentValue == other.DocumentValue ||
                    DocumentValue != null &&
                    DocumentValue.Equals(other.DocumentValue)
                ) && 
                (
                    AdditionalInfo == other.AdditionalInfo ||
                    AdditionalInfo != null &&
                    AdditionalInfo.Equals(other.AdditionalInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DocumentCode != null)
                    hashCode = hashCode * 59 + DocumentCode.GetHashCode();
                    if (CurrencyCode != null)
                    hashCode = hashCode * 59 + CurrencyCode.GetHashCode();
                    if (OrdinalNumber != null)
                    hashCode = hashCode * 59 + OrdinalNumber.GetHashCode();
                    if (DocumentValue != null)
                    hashCode = hashCode * 59 + DocumentValue.GetHashCode();
                    if (AdditionalInfo != null)
                    hashCode = hashCode * 59 + AdditionalInfo.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CustomsDeclarationItemDocumentDto left, CustomsDeclarationItemDocumentDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CustomsDeclarationItemDocumentDto left, CustomsDeclarationItemDocumentDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
