/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// Gets or Sets eSortColumn
          /// </summary>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum ESortColumn
          {
              /// <summary>
              /// Enum InvoiceInvoiceIdEnum for Invoice_InvoiceId
              /// </summary>
              [EnumMember(Value = "Invoice_InvoiceId")]
              InvoiceInvoiceIdEnum = 0,
              /// <summary>
              /// Enum InvoiceSenderNameEnum for Invoice_SenderName
              /// </summary>
              [EnumMember(Value = "Invoice_SenderName")]
              InvoiceSenderNameEnum = 1,
              /// <summary>
              /// Enum InvoiceReceiverNameEnum for Invoice_ReceiverName
              /// </summary>
              [EnumMember(Value = "Invoice_ReceiverName")]
              InvoiceReceiverNameEnum = 2,
              /// <summary>
              /// Enum InvoiceAccountingDateUtcEnum for Invoice_AccountingDateUtc
              /// </summary>
              [EnumMember(Value = "Invoice_AccountingDateUtc")]
              InvoiceAccountingDateUtcEnum = 3,
              /// <summary>
              /// Enum InvoiceInvoiceDateUtcEnum for Invoice_InvoiceDateUtc
              /// </summary>
              [EnumMember(Value = "Invoice_InvoiceDateUtc")]
              InvoiceInvoiceDateUtcEnum = 4,
              /// <summary>
              /// Enum InvoicePaymentDateUtcEnum for Invoice_PaymentDateUtc
              /// </summary>
              [EnumMember(Value = "Invoice_PaymentDateUtc")]
              InvoicePaymentDateUtcEnum = 5,
              /// <summary>
              /// Enum InvoiceSumWithoutVatEnum for Invoice_SumWithoutVat
              /// </summary>
              [EnumMember(Value = "Invoice_SumWithoutVat")]
              InvoiceSumWithoutVatEnum = 6,
              /// <summary>
              /// Enum InvoiceVatRateEnum for Invoice_VatRate
              /// </summary>
              [EnumMember(Value = "Invoice_VatRate")]
              InvoiceVatRateEnum = 7,
              /// <summary>
              /// Enum InvoiceVatSumEnum for Invoice_VatSum
              /// </summary>
              [EnumMember(Value = "Invoice_VatSum")]
              InvoiceVatSumEnum = 8,
              /// <summary>
              /// Enum InvoiceSumWithVatEnum for Invoice_SumWithVat
              /// </summary>
              [EnumMember(Value = "Invoice_SumWithVat")]
              InvoiceSumWithVatEnum = 9,
              /// <summary>
              /// Enum InvoiceReferenceNumberEnum for Invoice_ReferenceNumber
              /// </summary>
              [EnumMember(Value = "Invoice_ReferenceNumber")]
              InvoiceReferenceNumberEnum = 10,
              /// <summary>
              /// Enum InvoiceDescriptionEnum for Invoice_Description
              /// </summary>
              [EnumMember(Value = "Invoice_Description")]
              InvoiceDescriptionEnum = 11,
              /// <summary>
              /// Enum InvoiceOrderNumberEnum for Invoice_OrderNumber
              /// </summary>
              [EnumMember(Value = "Invoice_OrderNumber")]
              InvoiceOrderNumberEnum = 12,
              /// <summary>
              /// Enum InvoiceInvoiceNumberEnum for Invoice_InvoiceNumber
              /// </summary>
              [EnumMember(Value = "Invoice_InvoiceNumber")]
              InvoiceInvoiceNumberEnum = 13,
              /// <summary>
              /// Enum InvoiceStatusEnum for Invoice_Status
              /// </summary>
              [EnumMember(Value = "Invoice_Status")]
              InvoiceStatusEnum = 14,
              /// <summary>
              /// Enum InvoiceServiceIdEnum for Invoice_ServiceId
              /// </summary>
              [EnumMember(Value = "Invoice_ServiceId")]
              InvoiceServiceIdEnum = 15,
              /// <summary>
              /// Enum InvoiceChannelIdEnum for Invoice_ChannelId
              /// </summary>
              [EnumMember(Value = "Invoice_ChannelId")]
              InvoiceChannelIdEnum = 16,
              /// <summary>
              /// Enum InvoiceChannelAdressEnum for Invoice_ChannelAdress
              /// </summary>
              [EnumMember(Value = "Invoice_ChannelAdress")]
              InvoiceChannelAdressEnum = 17,
              /// <summary>
              /// Enum InvoiceDocumentTypeEnum for Invoice_DocumentType
              /// </summary>
              [EnumMember(Value = "Invoice_DocumentType")]
              InvoiceDocumentTypeEnum = 18,
              /// <summary>
              /// Enum InvoiceInvoiceSentDateUtcEnum for Invoice_InvoiceSentDateUtc
              /// </summary>
              [EnumMember(Value = "Invoice_InvoiceSentDateUtc")]
              InvoiceInvoiceSentDateUtcEnum = 19,
              /// <summary>
              /// Enum InvoiceInvoiceTypeEnum for Invoice_InvoiceType
              /// </summary>
              [EnumMember(Value = "Invoice_InvoiceType")]
              InvoiceInvoiceTypeEnum = 20,
              /// <summary>
              /// Enum InvoiceLastModifiedUtcEnum for Invoice_LastModifiedUtc
              /// </summary>
              [EnumMember(Value = "Invoice_LastModifiedUtc")]
              InvoiceLastModifiedUtcEnum = 21,
              /// <summary>
              /// Enum VatRecordCalculationNumberEnum for VatRecord_CalculationNumber
              /// </summary>
              [EnumMember(Value = "VatRecord_CalculationNumber")]
              VatRecordCalculationNumberEnum = 22,
              /// <summary>
              /// Enum VatRecordVatPeriodEnum for VatRecord_VatPeriod
              /// </summary>
              [EnumMember(Value = "VatRecord_VatPeriod")]
              VatRecordVatPeriodEnum = 23,
              /// <summary>
              /// Enum VatRecordDocumentNumberEnum for VatRecord_DocumentNumber
              /// </summary>
              [EnumMember(Value = "VatRecord_DocumentNumber")]
              VatRecordDocumentNumberEnum = 24,
              /// <summary>
              /// Enum VatRecordStatusChangeDateEnum for VatRecord_StatusChangeDate
              /// </summary>
              [EnumMember(Value = "VatRecord_StatusChangeDate")]
              VatRecordStatusChangeDateEnum = 25,
              /// <summary>
              /// Enum VatRecordDocumentTypeEnum for VatRecord_DocumentType
              /// </summary>
              [EnumMember(Value = "VatRecord_DocumentType")]
              VatRecordDocumentTypeEnum = 26          }
}
