/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Header : IEquatable<Header>
    { 
        /// <summary>
        /// Gets or Sets ClientInvoiceNumber
        /// </summary>

        [DataMember(Name="clientInvoiceNumber")]
        public string ClientInvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets InternalInvoiceId
        /// </summary>

        [DataMember(Name="internalInvoiceId")]
        public string InternalInvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets Extensions
        /// </summary>

        [DataMember(Name="extensions")]
        public List<Extension> Extensions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Header {\n");
            sb.Append("  ClientInvoiceNumber: ").Append(ClientInvoiceNumber).Append("\n");
            sb.Append("  InternalInvoiceId: ").Append(InternalInvoiceId).Append("\n");
            sb.Append("  Extensions: ").Append(Extensions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Header)obj);
        }

        /// <summary>
        /// Returns true if Header instances are equal
        /// </summary>
        /// <param name="other">Instance of Header to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Header other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ClientInvoiceNumber == other.ClientInvoiceNumber ||
                    ClientInvoiceNumber != null &&
                    ClientInvoiceNumber.Equals(other.ClientInvoiceNumber)
                ) && 
                (
                    InternalInvoiceId == other.InternalInvoiceId ||
                    InternalInvoiceId != null &&
                    InternalInvoiceId.Equals(other.InternalInvoiceId)
                ) && 
                (
                    Extensions == other.Extensions ||
                    Extensions != null &&
                    Extensions.SequenceEqual(other.Extensions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ClientInvoiceNumber != null)
                    hashCode = hashCode * 59 + ClientInvoiceNumber.GetHashCode();
                    if (InternalInvoiceId != null)
                    hashCode = hashCode * 59 + InternalInvoiceId.GetHashCode();
                    if (Extensions != null)
                    hashCode = hashCode * 59 + Extensions.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Header left, Header right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Header left, Header right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
