/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class IndividualVatAddDto : IEquatable<IndividualVatAddDto>
    { 
        /// <summary>
        /// Gets or Sets DocumentNumber
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="documentNumber")]
        public string DocumentNumber { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverDate
        /// </summary>

        [DataMember(Name="turnoverDate")]
        public DateTime? TurnoverDate { get; set; }

        /// <summary>
        /// Gets or Sets PaymentDate
        /// </summary>

        [DataMember(Name="paymentDate")]
        public DateTime? PaymentDate { get; set; }

        /// <summary>
        /// Gets or Sets DocumentType
        /// </summary>

        [DataMember(Name="documentType")]
        public VatRecordingDocumentType DocumentType { get; set; }

        /// <summary>
        /// Gets or Sets Year
        /// </summary>
        [Required]

        [Range(0, 9999)]
        [DataMember(Name="year")]
        public int? Year { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverDescription
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="turnoverDescription")]
        public string TurnoverDescription { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverAmount
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="turnoverAmount")]
        public double? TurnoverAmount { get; set; }

        /// <summary>
        /// Gets or Sets VatBaseAmount20
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="vatBaseAmount20")]
        public double? VatBaseAmount20 { get; set; }

        /// <summary>
        /// Gets or Sets VatBaseAmount10
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="vatBaseAmount10")]
        public double? VatBaseAmount10 { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="vatAmount")]
        public double? VatAmount { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount10
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="vatAmount10")]
        public double? VatAmount10 { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount20
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="vatAmount20")]
        public double? VatAmount20 { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="totalAmount")]
        public double? TotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets VatDeductionRight
        /// </summary>

        [DataMember(Name="vatDeductionRight")]
        public VatDeductionRight VatDeductionRight { get; set; }

        /// <summary>
        /// Gets or Sets RelatedDocuments
        /// </summary>

        [DataMember(Name="relatedDocuments")]
        public List<RelatedVatDocumentAddDto> RelatedDocuments { get; set; }

        /// <summary>
        /// Gets or Sets DocumentDirection
        /// </summary>

        [DataMember(Name="documentDirection")]
        public DocumentDirection DocumentDirection { get; set; }

        /// <summary>
        /// Gets or Sets RelatedPartyIdentifier
        /// </summary>
        [Required]

        [MinLength(1)]
        [DataMember(Name="relatedPartyIdentifier")]
        public string RelatedPartyIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets ForeignDocument
        /// </summary>

        [DataMember(Name="foreignDocument")]
        public bool? ForeignDocument { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverDescription20
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="turnoverDescription20")]
        public string TurnoverDescription20 { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverDescription10
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="turnoverDescription10")]
        public string TurnoverDescription10 { get; set; }

        /// <summary>
        /// Gets or Sets VatPeriod
        /// </summary>

        [DataMember(Name="vatPeriod")]
        public VatPeriod VatPeriod { get; set; }

        /// <summary>
        /// Gets or Sets InternalInvoiceOption
        /// </summary>

        [DataMember(Name="internalInvoiceOption")]
        public InternalInvoiceOption InternalInvoiceOption { get; set; }

        /// <summary>
        /// Gets or Sets CalculationNumber
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="calculationNumber")]
        public string CalculationNumber { get; set; }

        /// <summary>
        /// Gets or Sets BasisForPrepayment
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="basisForPrepayment")]
        public string BasisForPrepayment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IndividualVatAddDto {\n");
            sb.Append("  DocumentNumber: ").Append(DocumentNumber).Append("\n");
            sb.Append("  TurnoverDate: ").Append(TurnoverDate).Append("\n");
            sb.Append("  PaymentDate: ").Append(PaymentDate).Append("\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  TurnoverDescription: ").Append(TurnoverDescription).Append("\n");
            sb.Append("  TurnoverAmount: ").Append(TurnoverAmount).Append("\n");
            sb.Append("  VatBaseAmount20: ").Append(VatBaseAmount20).Append("\n");
            sb.Append("  VatBaseAmount10: ").Append(VatBaseAmount10).Append("\n");
            sb.Append("  VatAmount: ").Append(VatAmount).Append("\n");
            sb.Append("  VatAmount10: ").Append(VatAmount10).Append("\n");
            sb.Append("  VatAmount20: ").Append(VatAmount20).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  VatDeductionRight: ").Append(VatDeductionRight).Append("\n");
            sb.Append("  RelatedDocuments: ").Append(RelatedDocuments).Append("\n");
            sb.Append("  DocumentDirection: ").Append(DocumentDirection).Append("\n");
            sb.Append("  RelatedPartyIdentifier: ").Append(RelatedPartyIdentifier).Append("\n");
            sb.Append("  ForeignDocument: ").Append(ForeignDocument).Append("\n");
            sb.Append("  TurnoverDescription20: ").Append(TurnoverDescription20).Append("\n");
            sb.Append("  TurnoverDescription10: ").Append(TurnoverDescription10).Append("\n");
            sb.Append("  VatPeriod: ").Append(VatPeriod).Append("\n");
            sb.Append("  InternalInvoiceOption: ").Append(InternalInvoiceOption).Append("\n");
            sb.Append("  CalculationNumber: ").Append(CalculationNumber).Append("\n");
            sb.Append("  BasisForPrepayment: ").Append(BasisForPrepayment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IndividualVatAddDto)obj);
        }

        /// <summary>
        /// Returns true if IndividualVatAddDto instances are equal
        /// </summary>
        /// <param name="other">Instance of IndividualVatAddDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IndividualVatAddDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DocumentNumber == other.DocumentNumber ||
                    DocumentNumber != null &&
                    DocumentNumber.Equals(other.DocumentNumber)
                ) && 
                (
                    TurnoverDate == other.TurnoverDate ||
                    TurnoverDate != null &&
                    TurnoverDate.Equals(other.TurnoverDate)
                ) && 
                (
                    PaymentDate == other.PaymentDate ||
                    PaymentDate != null &&
                    PaymentDate.Equals(other.PaymentDate)
                ) && 
                (
                    DocumentType == other.DocumentType ||
                    DocumentType != null &&
                    DocumentType.Equals(other.DocumentType)
                ) && 
                (
                    Year == other.Year ||
                    Year != null &&
                    Year.Equals(other.Year)
                ) && 
                (
                    TurnoverDescription == other.TurnoverDescription ||
                    TurnoverDescription != null &&
                    TurnoverDescription.Equals(other.TurnoverDescription)
                ) && 
                (
                    TurnoverAmount == other.TurnoverAmount ||
                    TurnoverAmount != null &&
                    TurnoverAmount.Equals(other.TurnoverAmount)
                ) && 
                (
                    VatBaseAmount20 == other.VatBaseAmount20 ||
                    VatBaseAmount20 != null &&
                    VatBaseAmount20.Equals(other.VatBaseAmount20)
                ) && 
                (
                    VatBaseAmount10 == other.VatBaseAmount10 ||
                    VatBaseAmount10 != null &&
                    VatBaseAmount10.Equals(other.VatBaseAmount10)
                ) && 
                (
                    VatAmount == other.VatAmount ||
                    VatAmount != null &&
                    VatAmount.Equals(other.VatAmount)
                ) && 
                (
                    VatAmount10 == other.VatAmount10 ||
                    VatAmount10 != null &&
                    VatAmount10.Equals(other.VatAmount10)
                ) && 
                (
                    VatAmount20 == other.VatAmount20 ||
                    VatAmount20 != null &&
                    VatAmount20.Equals(other.VatAmount20)
                ) && 
                (
                    TotalAmount == other.TotalAmount ||
                    TotalAmount != null &&
                    TotalAmount.Equals(other.TotalAmount)
                ) && 
                (
                    VatDeductionRight == other.VatDeductionRight ||
                    VatDeductionRight != null &&
                    VatDeductionRight.Equals(other.VatDeductionRight)
                ) && 
                (
                    RelatedDocuments == other.RelatedDocuments ||
                    RelatedDocuments != null &&
                    RelatedDocuments.SequenceEqual(other.RelatedDocuments)
                ) && 
                (
                    DocumentDirection == other.DocumentDirection ||
                    DocumentDirection != null &&
                    DocumentDirection.Equals(other.DocumentDirection)
                ) && 
                (
                    RelatedPartyIdentifier == other.RelatedPartyIdentifier ||
                    RelatedPartyIdentifier != null &&
                    RelatedPartyIdentifier.Equals(other.RelatedPartyIdentifier)
                ) && 
                (
                    ForeignDocument == other.ForeignDocument ||
                    ForeignDocument != null &&
                    ForeignDocument.Equals(other.ForeignDocument)
                ) && 
                (
                    TurnoverDescription20 == other.TurnoverDescription20 ||
                    TurnoverDescription20 != null &&
                    TurnoverDescription20.Equals(other.TurnoverDescription20)
                ) && 
                (
                    TurnoverDescription10 == other.TurnoverDescription10 ||
                    TurnoverDescription10 != null &&
                    TurnoverDescription10.Equals(other.TurnoverDescription10)
                ) && 
                (
                    VatPeriod == other.VatPeriod ||
                    VatPeriod != null &&
                    VatPeriod.Equals(other.VatPeriod)
                ) && 
                (
                    InternalInvoiceOption == other.InternalInvoiceOption ||
                    InternalInvoiceOption != null &&
                    InternalInvoiceOption.Equals(other.InternalInvoiceOption)
                ) && 
                (
                    CalculationNumber == other.CalculationNumber ||
                    CalculationNumber != null &&
                    CalculationNumber.Equals(other.CalculationNumber)
                ) && 
                (
                    BasisForPrepayment == other.BasisForPrepayment ||
                    BasisForPrepayment != null &&
                    BasisForPrepayment.Equals(other.BasisForPrepayment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DocumentNumber != null)
                    hashCode = hashCode * 59 + DocumentNumber.GetHashCode();
                    if (TurnoverDate != null)
                    hashCode = hashCode * 59 + TurnoverDate.GetHashCode();
                    if (PaymentDate != null)
                    hashCode = hashCode * 59 + PaymentDate.GetHashCode();
                    if (DocumentType != null)
                    hashCode = hashCode * 59 + DocumentType.GetHashCode();
                    if (Year != null)
                    hashCode = hashCode * 59 + Year.GetHashCode();
                    if (TurnoverDescription != null)
                    hashCode = hashCode * 59 + TurnoverDescription.GetHashCode();
                    if (TurnoverAmount != null)
                    hashCode = hashCode * 59 + TurnoverAmount.GetHashCode();
                    if (VatBaseAmount20 != null)
                    hashCode = hashCode * 59 + VatBaseAmount20.GetHashCode();
                    if (VatBaseAmount10 != null)
                    hashCode = hashCode * 59 + VatBaseAmount10.GetHashCode();
                    if (VatAmount != null)
                    hashCode = hashCode * 59 + VatAmount.GetHashCode();
                    if (VatAmount10 != null)
                    hashCode = hashCode * 59 + VatAmount10.GetHashCode();
                    if (VatAmount20 != null)
                    hashCode = hashCode * 59 + VatAmount20.GetHashCode();
                    if (TotalAmount != null)
                    hashCode = hashCode * 59 + TotalAmount.GetHashCode();
                    if (VatDeductionRight != null)
                    hashCode = hashCode * 59 + VatDeductionRight.GetHashCode();
                    if (RelatedDocuments != null)
                    hashCode = hashCode * 59 + RelatedDocuments.GetHashCode();
                    if (DocumentDirection != null)
                    hashCode = hashCode * 59 + DocumentDirection.GetHashCode();
                    if (RelatedPartyIdentifier != null)
                    hashCode = hashCode * 59 + RelatedPartyIdentifier.GetHashCode();
                    if (ForeignDocument != null)
                    hashCode = hashCode * 59 + ForeignDocument.GetHashCode();
                    if (TurnoverDescription20 != null)
                    hashCode = hashCode * 59 + TurnoverDescription20.GetHashCode();
                    if (TurnoverDescription10 != null)
                    hashCode = hashCode * 59 + TurnoverDescription10.GetHashCode();
                    if (VatPeriod != null)
                    hashCode = hashCode * 59 + VatPeriod.GetHashCode();
                    if (InternalInvoiceOption != null)
                    hashCode = hashCode * 59 + InternalInvoiceOption.GetHashCode();
                    if (CalculationNumber != null)
                    hashCode = hashCode * 59 + CalculationNumber.GetHashCode();
                    if (BasisForPrepayment != null)
                    hashCode = hashCode * 59 + BasisForPrepayment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(IndividualVatAddDto left, IndividualVatAddDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IndividualVatAddDto left, IndividualVatAddDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
