/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InvoiceDto : IEquatable<InvoiceDto>
    { 
        /// <summary>
        /// Gets or Sets ServiceId
        /// </summary>

        [DataMember(Name="serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>

        [DataMember(Name="invoiceId")]
        public long? InvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets SenderId
        /// </summary>

        [DataMember(Name="senderId")]
        public int? SenderId { get; set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>

        [DataMember(Name="sender")]
        public string Sender { get; set; }

        /// <summary>
        /// Gets or Sets Receiver
        /// </summary>

        [DataMember(Name="receiver")]
        public string Receiver { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>

        [DataMember(Name="invoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets AccountingDateUtc
        /// </summary>

        [DataMember(Name="accountingDateUtc")]
        public DateTime? AccountingDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets PaymentDateUtc
        /// </summary>

        [DataMember(Name="paymentDateUtc")]
        public DateTime? PaymentDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceDateUtc
        /// </summary>

        [DataMember(Name="invoiceDateUtc")]
        public DateTime? InvoiceDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceSentDateUtc
        /// </summary>

        [DataMember(Name="invoiceSentDateUtc")]
        public DateTime? InvoiceSentDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNumber
        /// </summary>

        [DataMember(Name="referenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets FineRatePerDay
        /// </summary>

        [DataMember(Name="fineRatePerDay")]
        public double? FineRatePerDay { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>

        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>

        [DataMember(Name="note")]
        public string Note { get; set; }

        /// <summary>
        /// Gets or Sets OrderNumber
        /// </summary>

        [DataMember(Name="orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>

        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets DiscountPercentage
        /// </summary>

        [DataMember(Name="discountPercentage")]
        public double? DiscountPercentage { get; set; }

        /// <summary>
        /// Gets or Sets DiscountAmount
        /// </summary>

        [DataMember(Name="discountAmount")]
        public double? DiscountAmount { get; set; }

        /// <summary>
        /// Gets or Sets SumWithoutVat
        /// </summary>

        [DataMember(Name="sumWithoutVat")]
        public double? SumWithoutVat { get; set; }

        /// <summary>
        /// Gets or Sets VatRate
        /// </summary>

        [DataMember(Name="vatRate")]
        public double? VatRate { get; set; }

        /// <summary>
        /// Gets or Sets VatSum
        /// </summary>

        [DataMember(Name="vatSum")]
        public double? VatSum { get; set; }

        /// <summary>
        /// Gets or Sets SumWithVat
        /// </summary>

        [DataMember(Name="sumWithVat")]
        public double? SumWithVat { get; set; }

        /// <summary>
        /// Gets or Sets CreatedUtc
        /// </summary>

        [DataMember(Name="createdUtc")]
        public DateTime? CreatedUtc { get; set; }

        /// <summary>
        /// Gets or Sets LastModifiedUtc
        /// </summary>

        [DataMember(Name="lastModifiedUtc")]
        public DateTime? LastModifiedUtc { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>

        [DataMember(Name="version")]
        public long? Version { get; set; }

        /// <summary>
        /// Gets or Sets ModelNumber
        /// </summary>

        [DataMember(Name="modelNumber")]
        public string ModelNumber { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverId
        /// </summary>

        [DataMember(Name="receiverId")]
        public int? ReceiverId { get; set; }

        /// <summary>
        /// Gets or Sets PublicPurchaseContractSigner
        /// </summary>

        [DataMember(Name="publicPurchaseContractSigner")]
        public SspCustomerSupplierDto PublicPurchaseContractSigner { get; set; }

        /// <summary>
        /// Gets or Sets PublicPurchaseContractSignerContractId
        /// </summary>

        [DataMember(Name="publicPurchaseContractSignerContractId")]
        public int? PublicPurchaseContractSignerContractId { get; set; }

        /// <summary>
        /// Gets or Sets Contract
        /// </summary>

        [DataMember(Name="contract")]
        public SspContractDto Contract { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>

        [DataMember(Name="status")]
        public SalesInvoiceStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets UasSender
        /// </summary>

        [DataMember(Name="uasSender")]
        public CompanyDto UasSender { get; set; }

        /// <summary>
        /// Gets or Sets TotalRowsCount
        /// </summary>

        [DataMember(Name="totalRowsCount")]
        public int? TotalRowsCount { get; set; }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>

        [DataMember(Name="channel")]
        public int? Channel { get; set; }

        /// <summary>
        /// Gets or Sets ChannelAddress
        /// </summary>

        [DataMember(Name="channelAddress")]
        public string ChannelAddress { get; set; }

        /// <summary>
        /// Gets or Sets ServiceProvider
        /// </summary>

        [DataMember(Name="serviceProvider")]
        public string ServiceProvider { get; set; }

        /// <summary>
        /// Gets or Sets Rows
        /// </summary>

        [DataMember(Name="rows")]
        public List<LineItemDto> Rows { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceMessage
        /// </summary>

        [MaxLength(500)]
        [DataMember(Name="invoiceMessage")]
        public string InvoiceMessage { get; set; }

        /// <summary>
        /// Gets or Sets AcceptRejectMessage
        /// </summary>

        [MaxLength(500)]
        [DataMember(Name="acceptRejectMessage")]
        public string AcceptRejectMessage { get; set; }

        /// <summary>
        /// Gets or Sets Attachments
        /// </summary>

        [DataMember(Name="attachments")]
        public List<SalesInvoiceAttachmentDto> Attachments { get; set; }

        /// <summary>
        /// Gets or Sets BankAccounts
        /// </summary>

        [DataMember(Name="bankAccounts")]
        public List<SalesInvoiceBankAccountDto> BankAccounts { get; set; }

        /// <summary>
        /// Gets or Sets SelectedPrepaymentInvoices
        /// </summary>

        [DataMember(Name="selectedPrepaymentInvoices")]
        public List<SelectedIndividualPrepaymentInvoiceDto> SelectedPrepaymentInvoices { get; set; }

        /// <summary>
        /// Gets or Sets IsCreditInvoice
        /// </summary>

        [DataMember(Name="isCreditInvoice")]
        public bool? IsCreditInvoice { get; set; }

        /// <summary>
        /// Gets or Sets SenderReceiverContractNumber
        /// </summary>

        [DataMember(Name="senderReceiverContractNumber")]
        public string SenderReceiverContractNumber { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>

        [DataMember(Name="errorCode")]
        public ErrorCodes ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets TotalToPay
        /// </summary>

        [DataMember(Name="totalToPay")]
        public double? TotalToPay { get; set; }

        /// <summary>
        /// Gets or Sets SendInvoiceToCir
        /// </summary>

        [DataMember(Name="sendInvoiceToCir")]
        public bool? SendInvoiceToCir { get; set; }

        /// <summary>
        /// Gets or Sets CirInvoiceId
        /// </summary>

        [DataMember(Name="cirInvoiceId")]
        public string CirInvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets CirAmountChangeId
        /// </summary>

        [DataMember(Name="cirAmountChangeId")]
        public string CirAmountChangeId { get; set; }

        /// <summary>
        /// Gets or Sets CirSettledAmount
        /// </summary>

        [DataMember(Name="cirSettledAmount")]
        public double? CirSettledAmount { get; set; }

        /// <summary>
        /// Gets or Sets IsProFormaInvoice
        /// </summary>

        [DataMember(Name="isProFormaInvoice")]
        public bool? IsProFormaInvoice { get; set; }

        /// <summary>
        /// Gets or Sets CirHistory
        /// </summary>

        [DataMember(Name="cirHistory")]
        public CirHistoryDto CirHistory { get; set; }

        /// <summary>
        /// Gets or Sets CirAssignationHistory
        /// </summary>

        [DataMember(Name="cirAssignationHistory")]
        public InvoiceHistoryDto CirAssignationHistory { get; set; }

        /// <summary>
        /// Gets or Sets CirStatus
        /// </summary>

        [DataMember(Name="cirStatus")]
        public CirInvoiceStatus CirStatus { get; set; }

        /// <summary>
        /// Gets or Sets IsDebitNote
        /// </summary>

        [DataMember(Name="isDebitNote")]
        public bool? IsDebitNote { get; set; }

        /// <summary>
        /// Gets or Sets StornoNumber
        /// </summary>

        [DataMember(Name="stornoNumber")]
        public string StornoNumber { get; set; }

        /// <summary>
        /// Gets or Sets CancelInvoiceMessage
        /// </summary>

        [DataMember(Name="cancelInvoiceMessage")]
        public string CancelInvoiceMessage { get; set; }

        /// <summary>
        /// Gets or Sets PrepaymentInvoiceNumber
        /// </summary>

        [DataMember(Name="prepaymentInvoiceNumber")]
        public string PrepaymentInvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets IsPrepaymentInvoice
        /// </summary>

        [DataMember(Name="isPrepaymentInvoice")]
        public bool? IsPrepaymentInvoice { get; set; }

        /// <summary>
        /// Gets or Sets VatPointDate
        /// </summary>

        [DataMember(Name="vatPointDate")]
        public int? VatPointDate { get; set; }

        /// <summary>
        /// Gets or Sets GlobUniqId
        /// </summary>

        [DataMember(Name="globUniqId")]
        public string GlobUniqId { get; set; }

        /// <summary>
        /// Gets or Sets VatNumberFactoringCompany
        /// </summary>

        [DataMember(Name="vatNumberFactoringCompany")]
        public string VatNumberFactoringCompany { get; set; }

        /// <summary>
        /// Gets or Sets FactoringContractNumber
        /// </summary>

        [DataMember(Name="factoringContractNumber")]
        public string FactoringContractNumber { get; set; }

        /// <summary>
        /// Gets or Sets SourceInvoiceSelectionMode
        /// </summary>

        [DataMember(Name="sourceInvoiceSelectionMode")]
        public SourceInvoiceSelectionMode SourceInvoiceSelectionMode { get; set; }

        /// <summary>
        /// Gets or Sets IndebtednessPeriodFromDate
        /// </summary>

        [DataMember(Name="indebtednessPeriodFromDate")]
        public DateTime? IndebtednessPeriodFromDate { get; set; }

        /// <summary>
        /// Gets or Sets IndebtednessPeriodToDate
        /// </summary>

        [DataMember(Name="indebtednessPeriodToDate")]
        public DateTime? IndebtednessPeriodToDate { get; set; }

        /// <summary>
        /// Gets or Sets SourceInvoices
        /// </summary>

        [DataMember(Name="sourceInvoices")]
        public List<InvoiceLinkDto> SourceInvoices { get; set; }

        /// <summary>
        /// Gets or Sets CreditInvoices
        /// </summary>

        [DataMember(Name="creditInvoices")]
        public List<InvoiceLinkDto> CreditInvoices { get; set; }

        /// <summary>
        /// Gets or Sets DebitNotes
        /// </summary>

        [DataMember(Name="debitNotes")]
        public List<InvoiceLinkDto> DebitNotes { get; set; }

        /// <summary>
        /// Gets or Sets PrepaymentCalculation
        /// </summary>

        [DataMember(Name="prepaymentCalculation")]
        public SalesPrepaymentCalculationDto PrepaymentCalculation { get; set; }

        /// <summary>
        /// Gets or Sets PrepaymentCalculationDomestic
        /// </summary>

        [DataMember(Name="prepaymentCalculationDomestic")]
        public SalesPrepaymentCalculationDto PrepaymentCalculationDomestic { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceTotalPaymentsCalculation
        /// </summary>

        [DataMember(Name="invoiceTotalPaymentsCalculation")]
        public SalesInvoiceTotalPaymentsCalculationDto InvoiceTotalPaymentsCalculation { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceTotalPaymentsCalculationDomestic
        /// </summary>

        [DataMember(Name="invoiceTotalPaymentsCalculationDomestic")]
        public SalesInvoiceTotalPaymentsCalculationDto InvoiceTotalPaymentsCalculationDomestic { get; set; }

        /// <summary>
        /// Gets or Sets LotNumber
        /// </summary>

        [DataMember(Name="lotNumber")]
        public string LotNumber { get; set; }

        /// <summary>
        /// Gets or Sets ExemptionReasonsByVatCategory
        /// </summary>

        [DataMember(Name="exemptionReasonsByVatCategory")]
        public List<ExemptionReasonByVatCategoryDto> ExemptionReasonsByVatCategory { get; set; }

        /// <summary>
        /// Gets or Sets Discounts
        /// </summary>

        [DataMember(Name="discounts")]
        public List<DiscountDto> Discounts { get; set; }

        /// <summary>
        /// Gets or Sets CreatedFromXml
        /// </summary>

        [DataMember(Name="createdFromXml")]
        public bool? CreatedFromXml { get; set; }

        /// <summary>
        /// Gets or Sets RoundingAmount
        /// </summary>

        [DataMember(Name="roundingAmount")]
        public double? RoundingAmount { get; set; }

        /// <summary>
        /// Gets or Sets FiscalBillNumbers
        /// </summary>

        [DataMember(Name="fiscalBillNumbers")]
        public List<string> FiscalBillNumbers { get; set; }

        /// <summary>
        /// Gets or Sets FiscalBillNumbersRepresentation
        /// </summary>

        [DataMember(Name="fiscalBillNumbersRepresentation")]
        public List<EFiscalizationFiscalBillNumbersForInvoiceRepresentation> FiscalBillNumbersRepresentation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvoiceDto {\n");
            sb.Append("  ServiceId: ").Append(ServiceId).Append("\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  SenderId: ").Append(SenderId).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Receiver: ").Append(Receiver).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  AccountingDateUtc: ").Append(AccountingDateUtc).Append("\n");
            sb.Append("  PaymentDateUtc: ").Append(PaymentDateUtc).Append("\n");
            sb.Append("  InvoiceDateUtc: ").Append(InvoiceDateUtc).Append("\n");
            sb.Append("  InvoiceSentDateUtc: ").Append(InvoiceSentDateUtc).Append("\n");
            sb.Append("  ReferenceNumber: ").Append(ReferenceNumber).Append("\n");
            sb.Append("  FineRatePerDay: ").Append(FineRatePerDay).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("  OrderNumber: ").Append(OrderNumber).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  DiscountPercentage: ").Append(DiscountPercentage).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  SumWithoutVat: ").Append(SumWithoutVat).Append("\n");
            sb.Append("  VatRate: ").Append(VatRate).Append("\n");
            sb.Append("  VatSum: ").Append(VatSum).Append("\n");
            sb.Append("  SumWithVat: ").Append(SumWithVat).Append("\n");
            sb.Append("  CreatedUtc: ").Append(CreatedUtc).Append("\n");
            sb.Append("  LastModifiedUtc: ").Append(LastModifiedUtc).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  ModelNumber: ").Append(ModelNumber).Append("\n");
            sb.Append("  ReceiverId: ").Append(ReceiverId).Append("\n");
            sb.Append("  PublicPurchaseContractSigner: ").Append(PublicPurchaseContractSigner).Append("\n");
            sb.Append("  PublicPurchaseContractSignerContractId: ").Append(PublicPurchaseContractSignerContractId).Append("\n");
            sb.Append("  Contract: ").Append(Contract).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  UasSender: ").Append(UasSender).Append("\n");
            sb.Append("  TotalRowsCount: ").Append(TotalRowsCount).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  ChannelAddress: ").Append(ChannelAddress).Append("\n");
            sb.Append("  ServiceProvider: ").Append(ServiceProvider).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("  InvoiceMessage: ").Append(InvoiceMessage).Append("\n");
            sb.Append("  AcceptRejectMessage: ").Append(AcceptRejectMessage).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  BankAccounts: ").Append(BankAccounts).Append("\n");
            sb.Append("  SelectedPrepaymentInvoices: ").Append(SelectedPrepaymentInvoices).Append("\n");
            sb.Append("  IsCreditInvoice: ").Append(IsCreditInvoice).Append("\n");
            sb.Append("  SenderReceiverContractNumber: ").Append(SenderReceiverContractNumber).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  TotalToPay: ").Append(TotalToPay).Append("\n");
            sb.Append("  SendInvoiceToCir: ").Append(SendInvoiceToCir).Append("\n");
            sb.Append("  CirInvoiceId: ").Append(CirInvoiceId).Append("\n");
            sb.Append("  CirAmountChangeId: ").Append(CirAmountChangeId).Append("\n");
            sb.Append("  CirSettledAmount: ").Append(CirSettledAmount).Append("\n");
            sb.Append("  IsProFormaInvoice: ").Append(IsProFormaInvoice).Append("\n");
            sb.Append("  CirHistory: ").Append(CirHistory).Append("\n");
            sb.Append("  CirAssignationHistory: ").Append(CirAssignationHistory).Append("\n");
            sb.Append("  CirStatus: ").Append(CirStatus).Append("\n");
            sb.Append("  IsDebitNote: ").Append(IsDebitNote).Append("\n");
            sb.Append("  StornoNumber: ").Append(StornoNumber).Append("\n");
            sb.Append("  CancelInvoiceMessage: ").Append(CancelInvoiceMessage).Append("\n");
            sb.Append("  PrepaymentInvoiceNumber: ").Append(PrepaymentInvoiceNumber).Append("\n");
            sb.Append("  IsPrepaymentInvoice: ").Append(IsPrepaymentInvoice).Append("\n");
            sb.Append("  VatPointDate: ").Append(VatPointDate).Append("\n");
            sb.Append("  GlobUniqId: ").Append(GlobUniqId).Append("\n");
            sb.Append("  VatNumberFactoringCompany: ").Append(VatNumberFactoringCompany).Append("\n");
            sb.Append("  FactoringContractNumber: ").Append(FactoringContractNumber).Append("\n");
            sb.Append("  SourceInvoiceSelectionMode: ").Append(SourceInvoiceSelectionMode).Append("\n");
            sb.Append("  IndebtednessPeriodFromDate: ").Append(IndebtednessPeriodFromDate).Append("\n");
            sb.Append("  IndebtednessPeriodToDate: ").Append(IndebtednessPeriodToDate).Append("\n");
            sb.Append("  SourceInvoices: ").Append(SourceInvoices).Append("\n");
            sb.Append("  CreditInvoices: ").Append(CreditInvoices).Append("\n");
            sb.Append("  DebitNotes: ").Append(DebitNotes).Append("\n");
            sb.Append("  PrepaymentCalculation: ").Append(PrepaymentCalculation).Append("\n");
            sb.Append("  PrepaymentCalculationDomestic: ").Append(PrepaymentCalculationDomestic).Append("\n");
            sb.Append("  InvoiceTotalPaymentsCalculation: ").Append(InvoiceTotalPaymentsCalculation).Append("\n");
            sb.Append("  InvoiceTotalPaymentsCalculationDomestic: ").Append(InvoiceTotalPaymentsCalculationDomestic).Append("\n");
            sb.Append("  LotNumber: ").Append(LotNumber).Append("\n");
            sb.Append("  ExemptionReasonsByVatCategory: ").Append(ExemptionReasonsByVatCategory).Append("\n");
            sb.Append("  Discounts: ").Append(Discounts).Append("\n");
            sb.Append("  CreatedFromXml: ").Append(CreatedFromXml).Append("\n");
            sb.Append("  RoundingAmount: ").Append(RoundingAmount).Append("\n");
            sb.Append("  FiscalBillNumbers: ").Append(FiscalBillNumbers).Append("\n");
            sb.Append("  FiscalBillNumbersRepresentation: ").Append(FiscalBillNumbersRepresentation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InvoiceDto)obj);
        }

        /// <summary>
        /// Returns true if InvoiceDto instances are equal
        /// </summary>
        /// <param name="other">Instance of InvoiceDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvoiceDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ServiceId == other.ServiceId ||
                    ServiceId != null &&
                    ServiceId.Equals(other.ServiceId)
                ) && 
                (
                    InvoiceId == other.InvoiceId ||
                    InvoiceId != null &&
                    InvoiceId.Equals(other.InvoiceId)
                ) && 
                (
                    SenderId == other.SenderId ||
                    SenderId != null &&
                    SenderId.Equals(other.SenderId)
                ) && 
                (
                    Sender == other.Sender ||
                    Sender != null &&
                    Sender.Equals(other.Sender)
                ) && 
                (
                    Receiver == other.Receiver ||
                    Receiver != null &&
                    Receiver.Equals(other.Receiver)
                ) && 
                (
                    InvoiceNumber == other.InvoiceNumber ||
                    InvoiceNumber != null &&
                    InvoiceNumber.Equals(other.InvoiceNumber)
                ) && 
                (
                    AccountingDateUtc == other.AccountingDateUtc ||
                    AccountingDateUtc != null &&
                    AccountingDateUtc.Equals(other.AccountingDateUtc)
                ) && 
                (
                    PaymentDateUtc == other.PaymentDateUtc ||
                    PaymentDateUtc != null &&
                    PaymentDateUtc.Equals(other.PaymentDateUtc)
                ) && 
                (
                    InvoiceDateUtc == other.InvoiceDateUtc ||
                    InvoiceDateUtc != null &&
                    InvoiceDateUtc.Equals(other.InvoiceDateUtc)
                ) && 
                (
                    InvoiceSentDateUtc == other.InvoiceSentDateUtc ||
                    InvoiceSentDateUtc != null &&
                    InvoiceSentDateUtc.Equals(other.InvoiceSentDateUtc)
                ) && 
                (
                    ReferenceNumber == other.ReferenceNumber ||
                    ReferenceNumber != null &&
                    ReferenceNumber.Equals(other.ReferenceNumber)
                ) && 
                (
                    FineRatePerDay == other.FineRatePerDay ||
                    FineRatePerDay != null &&
                    FineRatePerDay.Equals(other.FineRatePerDay)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Note == other.Note ||
                    Note != null &&
                    Note.Equals(other.Note)
                ) && 
                (
                    OrderNumber == other.OrderNumber ||
                    OrderNumber != null &&
                    OrderNumber.Equals(other.OrderNumber)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    DiscountPercentage == other.DiscountPercentage ||
                    DiscountPercentage != null &&
                    DiscountPercentage.Equals(other.DiscountPercentage)
                ) && 
                (
                    DiscountAmount == other.DiscountAmount ||
                    DiscountAmount != null &&
                    DiscountAmount.Equals(other.DiscountAmount)
                ) && 
                (
                    SumWithoutVat == other.SumWithoutVat ||
                    SumWithoutVat != null &&
                    SumWithoutVat.Equals(other.SumWithoutVat)
                ) && 
                (
                    VatRate == other.VatRate ||
                    VatRate != null &&
                    VatRate.Equals(other.VatRate)
                ) && 
                (
                    VatSum == other.VatSum ||
                    VatSum != null &&
                    VatSum.Equals(other.VatSum)
                ) && 
                (
                    SumWithVat == other.SumWithVat ||
                    SumWithVat != null &&
                    SumWithVat.Equals(other.SumWithVat)
                ) && 
                (
                    CreatedUtc == other.CreatedUtc ||
                    CreatedUtc != null &&
                    CreatedUtc.Equals(other.CreatedUtc)
                ) && 
                (
                    LastModifiedUtc == other.LastModifiedUtc ||
                    LastModifiedUtc != null &&
                    LastModifiedUtc.Equals(other.LastModifiedUtc)
                ) && 
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(other.Version)
                ) && 
                (
                    ModelNumber == other.ModelNumber ||
                    ModelNumber != null &&
                    ModelNumber.Equals(other.ModelNumber)
                ) && 
                (
                    ReceiverId == other.ReceiverId ||
                    ReceiverId != null &&
                    ReceiverId.Equals(other.ReceiverId)
                ) && 
                (
                    PublicPurchaseContractSigner == other.PublicPurchaseContractSigner ||
                    PublicPurchaseContractSigner != null &&
                    PublicPurchaseContractSigner.Equals(other.PublicPurchaseContractSigner)
                ) && 
                (
                    PublicPurchaseContractSignerContractId == other.PublicPurchaseContractSignerContractId ||
                    PublicPurchaseContractSignerContractId != null &&
                    PublicPurchaseContractSignerContractId.Equals(other.PublicPurchaseContractSignerContractId)
                ) && 
                (
                    Contract == other.Contract ||
                    Contract != null &&
                    Contract.Equals(other.Contract)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    UasSender == other.UasSender ||
                    UasSender != null &&
                    UasSender.Equals(other.UasSender)
                ) && 
                (
                    TotalRowsCount == other.TotalRowsCount ||
                    TotalRowsCount != null &&
                    TotalRowsCount.Equals(other.TotalRowsCount)
                ) && 
                (
                    Channel == other.Channel ||
                    Channel != null &&
                    Channel.Equals(other.Channel)
                ) && 
                (
                    ChannelAddress == other.ChannelAddress ||
                    ChannelAddress != null &&
                    ChannelAddress.Equals(other.ChannelAddress)
                ) && 
                (
                    ServiceProvider == other.ServiceProvider ||
                    ServiceProvider != null &&
                    ServiceProvider.Equals(other.ServiceProvider)
                ) && 
                (
                    Rows == other.Rows ||
                    Rows != null &&
                    Rows.SequenceEqual(other.Rows)
                ) && 
                (
                    InvoiceMessage == other.InvoiceMessage ||
                    InvoiceMessage != null &&
                    InvoiceMessage.Equals(other.InvoiceMessage)
                ) && 
                (
                    AcceptRejectMessage == other.AcceptRejectMessage ||
                    AcceptRejectMessage != null &&
                    AcceptRejectMessage.Equals(other.AcceptRejectMessage)
                ) && 
                (
                    Attachments == other.Attachments ||
                    Attachments != null &&
                    Attachments.SequenceEqual(other.Attachments)
                ) && 
                (
                    BankAccounts == other.BankAccounts ||
                    BankAccounts != null &&
                    BankAccounts.SequenceEqual(other.BankAccounts)
                ) && 
                (
                    SelectedPrepaymentInvoices == other.SelectedPrepaymentInvoices ||
                    SelectedPrepaymentInvoices != null &&
                    SelectedPrepaymentInvoices.SequenceEqual(other.SelectedPrepaymentInvoices)
                ) && 
                (
                    IsCreditInvoice == other.IsCreditInvoice ||
                    IsCreditInvoice != null &&
                    IsCreditInvoice.Equals(other.IsCreditInvoice)
                ) && 
                (
                    SenderReceiverContractNumber == other.SenderReceiverContractNumber ||
                    SenderReceiverContractNumber != null &&
                    SenderReceiverContractNumber.Equals(other.SenderReceiverContractNumber)
                ) && 
                (
                    ErrorCode == other.ErrorCode ||
                    ErrorCode != null &&
                    ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    TotalToPay == other.TotalToPay ||
                    TotalToPay != null &&
                    TotalToPay.Equals(other.TotalToPay)
                ) && 
                (
                    SendInvoiceToCir == other.SendInvoiceToCir ||
                    SendInvoiceToCir != null &&
                    SendInvoiceToCir.Equals(other.SendInvoiceToCir)
                ) && 
                (
                    CirInvoiceId == other.CirInvoiceId ||
                    CirInvoiceId != null &&
                    CirInvoiceId.Equals(other.CirInvoiceId)
                ) && 
                (
                    CirAmountChangeId == other.CirAmountChangeId ||
                    CirAmountChangeId != null &&
                    CirAmountChangeId.Equals(other.CirAmountChangeId)
                ) && 
                (
                    CirSettledAmount == other.CirSettledAmount ||
                    CirSettledAmount != null &&
                    CirSettledAmount.Equals(other.CirSettledAmount)
                ) && 
                (
                    IsProFormaInvoice == other.IsProFormaInvoice ||
                    IsProFormaInvoice != null &&
                    IsProFormaInvoice.Equals(other.IsProFormaInvoice)
                ) && 
                (
                    CirHistory == other.CirHistory ||
                    CirHistory != null &&
                    CirHistory.Equals(other.CirHistory)
                ) && 
                (
                    CirAssignationHistory == other.CirAssignationHistory ||
                    CirAssignationHistory != null &&
                    CirAssignationHistory.Equals(other.CirAssignationHistory)
                ) && 
                (
                    CirStatus == other.CirStatus ||
                    CirStatus != null &&
                    CirStatus.Equals(other.CirStatus)
                ) && 
                (
                    IsDebitNote == other.IsDebitNote ||
                    IsDebitNote != null &&
                    IsDebitNote.Equals(other.IsDebitNote)
                ) && 
                (
                    StornoNumber == other.StornoNumber ||
                    StornoNumber != null &&
                    StornoNumber.Equals(other.StornoNumber)
                ) && 
                (
                    CancelInvoiceMessage == other.CancelInvoiceMessage ||
                    CancelInvoiceMessage != null &&
                    CancelInvoiceMessage.Equals(other.CancelInvoiceMessage)
                ) && 
                (
                    PrepaymentInvoiceNumber == other.PrepaymentInvoiceNumber ||
                    PrepaymentInvoiceNumber != null &&
                    PrepaymentInvoiceNumber.Equals(other.PrepaymentInvoiceNumber)
                ) && 
                (
                    IsPrepaymentInvoice == other.IsPrepaymentInvoice ||
                    IsPrepaymentInvoice != null &&
                    IsPrepaymentInvoice.Equals(other.IsPrepaymentInvoice)
                ) && 
                (
                    VatPointDate == other.VatPointDate ||
                    VatPointDate != null &&
                    VatPointDate.Equals(other.VatPointDate)
                ) && 
                (
                    GlobUniqId == other.GlobUniqId ||
                    GlobUniqId != null &&
                    GlobUniqId.Equals(other.GlobUniqId)
                ) && 
                (
                    VatNumberFactoringCompany == other.VatNumberFactoringCompany ||
                    VatNumberFactoringCompany != null &&
                    VatNumberFactoringCompany.Equals(other.VatNumberFactoringCompany)
                ) && 
                (
                    FactoringContractNumber == other.FactoringContractNumber ||
                    FactoringContractNumber != null &&
                    FactoringContractNumber.Equals(other.FactoringContractNumber)
                ) && 
                (
                    SourceInvoiceSelectionMode == other.SourceInvoiceSelectionMode ||
                    SourceInvoiceSelectionMode != null &&
                    SourceInvoiceSelectionMode.Equals(other.SourceInvoiceSelectionMode)
                ) && 
                (
                    IndebtednessPeriodFromDate == other.IndebtednessPeriodFromDate ||
                    IndebtednessPeriodFromDate != null &&
                    IndebtednessPeriodFromDate.Equals(other.IndebtednessPeriodFromDate)
                ) && 
                (
                    IndebtednessPeriodToDate == other.IndebtednessPeriodToDate ||
                    IndebtednessPeriodToDate != null &&
                    IndebtednessPeriodToDate.Equals(other.IndebtednessPeriodToDate)
                ) && 
                (
                    SourceInvoices == other.SourceInvoices ||
                    SourceInvoices != null &&
                    SourceInvoices.SequenceEqual(other.SourceInvoices)
                ) && 
                (
                    CreditInvoices == other.CreditInvoices ||
                    CreditInvoices != null &&
                    CreditInvoices.SequenceEqual(other.CreditInvoices)
                ) && 
                (
                    DebitNotes == other.DebitNotes ||
                    DebitNotes != null &&
                    DebitNotes.SequenceEqual(other.DebitNotes)
                ) && 
                (
                    PrepaymentCalculation == other.PrepaymentCalculation ||
                    PrepaymentCalculation != null &&
                    PrepaymentCalculation.Equals(other.PrepaymentCalculation)
                ) && 
                (
                    PrepaymentCalculationDomestic == other.PrepaymentCalculationDomestic ||
                    PrepaymentCalculationDomestic != null &&
                    PrepaymentCalculationDomestic.Equals(other.PrepaymentCalculationDomestic)
                ) && 
                (
                    InvoiceTotalPaymentsCalculation == other.InvoiceTotalPaymentsCalculation ||
                    InvoiceTotalPaymentsCalculation != null &&
                    InvoiceTotalPaymentsCalculation.Equals(other.InvoiceTotalPaymentsCalculation)
                ) && 
                (
                    InvoiceTotalPaymentsCalculationDomestic == other.InvoiceTotalPaymentsCalculationDomestic ||
                    InvoiceTotalPaymentsCalculationDomestic != null &&
                    InvoiceTotalPaymentsCalculationDomestic.Equals(other.InvoiceTotalPaymentsCalculationDomestic)
                ) && 
                (
                    LotNumber == other.LotNumber ||
                    LotNumber != null &&
                    LotNumber.Equals(other.LotNumber)
                ) && 
                (
                    ExemptionReasonsByVatCategory == other.ExemptionReasonsByVatCategory ||
                    ExemptionReasonsByVatCategory != null &&
                    ExemptionReasonsByVatCategory.SequenceEqual(other.ExemptionReasonsByVatCategory)
                ) && 
                (
                    Discounts == other.Discounts ||
                    Discounts != null &&
                    Discounts.SequenceEqual(other.Discounts)
                ) && 
                (
                    CreatedFromXml == other.CreatedFromXml ||
                    CreatedFromXml != null &&
                    CreatedFromXml.Equals(other.CreatedFromXml)
                ) && 
                (
                    RoundingAmount == other.RoundingAmount ||
                    RoundingAmount != null &&
                    RoundingAmount.Equals(other.RoundingAmount)
                ) && 
                (
                    FiscalBillNumbers == other.FiscalBillNumbers ||
                    FiscalBillNumbers != null &&
                    FiscalBillNumbers.SequenceEqual(other.FiscalBillNumbers)
                ) && 
                (
                    FiscalBillNumbersRepresentation == other.FiscalBillNumbersRepresentation ||
                    FiscalBillNumbersRepresentation != null &&
                    FiscalBillNumbersRepresentation.SequenceEqual(other.FiscalBillNumbersRepresentation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ServiceId != null)
                    hashCode = hashCode * 59 + ServiceId.GetHashCode();
                    if (InvoiceId != null)
                    hashCode = hashCode * 59 + InvoiceId.GetHashCode();
                    if (SenderId != null)
                    hashCode = hashCode * 59 + SenderId.GetHashCode();
                    if (Sender != null)
                    hashCode = hashCode * 59 + Sender.GetHashCode();
                    if (Receiver != null)
                    hashCode = hashCode * 59 + Receiver.GetHashCode();
                    if (InvoiceNumber != null)
                    hashCode = hashCode * 59 + InvoiceNumber.GetHashCode();
                    if (AccountingDateUtc != null)
                    hashCode = hashCode * 59 + AccountingDateUtc.GetHashCode();
                    if (PaymentDateUtc != null)
                    hashCode = hashCode * 59 + PaymentDateUtc.GetHashCode();
                    if (InvoiceDateUtc != null)
                    hashCode = hashCode * 59 + InvoiceDateUtc.GetHashCode();
                    if (InvoiceSentDateUtc != null)
                    hashCode = hashCode * 59 + InvoiceSentDateUtc.GetHashCode();
                    if (ReferenceNumber != null)
                    hashCode = hashCode * 59 + ReferenceNumber.GetHashCode();
                    if (FineRatePerDay != null)
                    hashCode = hashCode * 59 + FineRatePerDay.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (Note != null)
                    hashCode = hashCode * 59 + Note.GetHashCode();
                    if (OrderNumber != null)
                    hashCode = hashCode * 59 + OrderNumber.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    if (DiscountPercentage != null)
                    hashCode = hashCode * 59 + DiscountPercentage.GetHashCode();
                    if (DiscountAmount != null)
                    hashCode = hashCode * 59 + DiscountAmount.GetHashCode();
                    if (SumWithoutVat != null)
                    hashCode = hashCode * 59 + SumWithoutVat.GetHashCode();
                    if (VatRate != null)
                    hashCode = hashCode * 59 + VatRate.GetHashCode();
                    if (VatSum != null)
                    hashCode = hashCode * 59 + VatSum.GetHashCode();
                    if (SumWithVat != null)
                    hashCode = hashCode * 59 + SumWithVat.GetHashCode();
                    if (CreatedUtc != null)
                    hashCode = hashCode * 59 + CreatedUtc.GetHashCode();
                    if (LastModifiedUtc != null)
                    hashCode = hashCode * 59 + LastModifiedUtc.GetHashCode();
                    if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                    if (ModelNumber != null)
                    hashCode = hashCode * 59 + ModelNumber.GetHashCode();
                    if (ReceiverId != null)
                    hashCode = hashCode * 59 + ReceiverId.GetHashCode();
                    if (PublicPurchaseContractSigner != null)
                    hashCode = hashCode * 59 + PublicPurchaseContractSigner.GetHashCode();
                    if (PublicPurchaseContractSignerContractId != null)
                    hashCode = hashCode * 59 + PublicPurchaseContractSignerContractId.GetHashCode();
                    if (Contract != null)
                    hashCode = hashCode * 59 + Contract.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (UasSender != null)
                    hashCode = hashCode * 59 + UasSender.GetHashCode();
                    if (TotalRowsCount != null)
                    hashCode = hashCode * 59 + TotalRowsCount.GetHashCode();
                    if (Channel != null)
                    hashCode = hashCode * 59 + Channel.GetHashCode();
                    if (ChannelAddress != null)
                    hashCode = hashCode * 59 + ChannelAddress.GetHashCode();
                    if (ServiceProvider != null)
                    hashCode = hashCode * 59 + ServiceProvider.GetHashCode();
                    if (Rows != null)
                    hashCode = hashCode * 59 + Rows.GetHashCode();
                    if (InvoiceMessage != null)
                    hashCode = hashCode * 59 + InvoiceMessage.GetHashCode();
                    if (AcceptRejectMessage != null)
                    hashCode = hashCode * 59 + AcceptRejectMessage.GetHashCode();
                    if (Attachments != null)
                    hashCode = hashCode * 59 + Attachments.GetHashCode();
                    if (BankAccounts != null)
                    hashCode = hashCode * 59 + BankAccounts.GetHashCode();
                    if (SelectedPrepaymentInvoices != null)
                    hashCode = hashCode * 59 + SelectedPrepaymentInvoices.GetHashCode();
                    if (IsCreditInvoice != null)
                    hashCode = hashCode * 59 + IsCreditInvoice.GetHashCode();
                    if (SenderReceiverContractNumber != null)
                    hashCode = hashCode * 59 + SenderReceiverContractNumber.GetHashCode();
                    if (ErrorCode != null)
                    hashCode = hashCode * 59 + ErrorCode.GetHashCode();
                    if (TotalToPay != null)
                    hashCode = hashCode * 59 + TotalToPay.GetHashCode();
                    if (SendInvoiceToCir != null)
                    hashCode = hashCode * 59 + SendInvoiceToCir.GetHashCode();
                    if (CirInvoiceId != null)
                    hashCode = hashCode * 59 + CirInvoiceId.GetHashCode();
                    if (CirAmountChangeId != null)
                    hashCode = hashCode * 59 + CirAmountChangeId.GetHashCode();
                    if (CirSettledAmount != null)
                    hashCode = hashCode * 59 + CirSettledAmount.GetHashCode();
                    if (IsProFormaInvoice != null)
                    hashCode = hashCode * 59 + IsProFormaInvoice.GetHashCode();
                    if (CirHistory != null)
                    hashCode = hashCode * 59 + CirHistory.GetHashCode();
                    if (CirAssignationHistory != null)
                    hashCode = hashCode * 59 + CirAssignationHistory.GetHashCode();
                    if (CirStatus != null)
                    hashCode = hashCode * 59 + CirStatus.GetHashCode();
                    if (IsDebitNote != null)
                    hashCode = hashCode * 59 + IsDebitNote.GetHashCode();
                    if (StornoNumber != null)
                    hashCode = hashCode * 59 + StornoNumber.GetHashCode();
                    if (CancelInvoiceMessage != null)
                    hashCode = hashCode * 59 + CancelInvoiceMessage.GetHashCode();
                    if (PrepaymentInvoiceNumber != null)
                    hashCode = hashCode * 59 + PrepaymentInvoiceNumber.GetHashCode();
                    if (IsPrepaymentInvoice != null)
                    hashCode = hashCode * 59 + IsPrepaymentInvoice.GetHashCode();
                    if (VatPointDate != null)
                    hashCode = hashCode * 59 + VatPointDate.GetHashCode();
                    if (GlobUniqId != null)
                    hashCode = hashCode * 59 + GlobUniqId.GetHashCode();
                    if (VatNumberFactoringCompany != null)
                    hashCode = hashCode * 59 + VatNumberFactoringCompany.GetHashCode();
                    if (FactoringContractNumber != null)
                    hashCode = hashCode * 59 + FactoringContractNumber.GetHashCode();
                    if (SourceInvoiceSelectionMode != null)
                    hashCode = hashCode * 59 + SourceInvoiceSelectionMode.GetHashCode();
                    if (IndebtednessPeriodFromDate != null)
                    hashCode = hashCode * 59 + IndebtednessPeriodFromDate.GetHashCode();
                    if (IndebtednessPeriodToDate != null)
                    hashCode = hashCode * 59 + IndebtednessPeriodToDate.GetHashCode();
                    if (SourceInvoices != null)
                    hashCode = hashCode * 59 + SourceInvoices.GetHashCode();
                    if (CreditInvoices != null)
                    hashCode = hashCode * 59 + CreditInvoices.GetHashCode();
                    if (DebitNotes != null)
                    hashCode = hashCode * 59 + DebitNotes.GetHashCode();
                    if (PrepaymentCalculation != null)
                    hashCode = hashCode * 59 + PrepaymentCalculation.GetHashCode();
                    if (PrepaymentCalculationDomestic != null)
                    hashCode = hashCode * 59 + PrepaymentCalculationDomestic.GetHashCode();
                    if (InvoiceTotalPaymentsCalculation != null)
                    hashCode = hashCode * 59 + InvoiceTotalPaymentsCalculation.GetHashCode();
                    if (InvoiceTotalPaymentsCalculationDomestic != null)
                    hashCode = hashCode * 59 + InvoiceTotalPaymentsCalculationDomestic.GetHashCode();
                    if (LotNumber != null)
                    hashCode = hashCode * 59 + LotNumber.GetHashCode();
                    if (ExemptionReasonsByVatCategory != null)
                    hashCode = hashCode * 59 + ExemptionReasonsByVatCategory.GetHashCode();
                    if (Discounts != null)
                    hashCode = hashCode * 59 + Discounts.GetHashCode();
                    if (CreatedFromXml != null)
                    hashCode = hashCode * 59 + CreatedFromXml.GetHashCode();
                    if (RoundingAmount != null)
                    hashCode = hashCode * 59 + RoundingAmount.GetHashCode();
                    if (FiscalBillNumbers != null)
                    hashCode = hashCode * 59 + FiscalBillNumbers.GetHashCode();
                    if (FiscalBillNumbersRepresentation != null)
                    hashCode = hashCode * 59 + FiscalBillNumbersRepresentation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InvoiceDto left, InvoiceDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InvoiceDto left, InvoiceDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
