/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InvoiceTotalVatPaymentsCalculationDomesticDto : IEquatable<InvoiceTotalVatPaymentsCalculationDomesticDto>
    { 
        /// <summary>
        /// Gets or Sets VatPerRateCalculations
        /// </summary>

        [DataMember(Name="vatPerRateCalculations")]
        public List<InvoiceTotalVatPerRateCalculationDomesticDto> VatPerRateCalculations { get; set; }

        /// <summary>
        /// Gets or Sets TotalVatPaymentsDomestic
        /// </summary>

        [DataMember(Name="totalVatPaymentsDomestic")]
        public double? TotalVatPaymentsDomestic { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvoiceTotalVatPaymentsCalculationDomesticDto {\n");
            sb.Append("  VatPerRateCalculations: ").Append(VatPerRateCalculations).Append("\n");
            sb.Append("  TotalVatPaymentsDomestic: ").Append(TotalVatPaymentsDomestic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InvoiceTotalVatPaymentsCalculationDomesticDto)obj);
        }

        /// <summary>
        /// Returns true if InvoiceTotalVatPaymentsCalculationDomesticDto instances are equal
        /// </summary>
        /// <param name="other">Instance of InvoiceTotalVatPaymentsCalculationDomesticDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvoiceTotalVatPaymentsCalculationDomesticDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VatPerRateCalculations == other.VatPerRateCalculations ||
                    VatPerRateCalculations != null &&
                    VatPerRateCalculations.SequenceEqual(other.VatPerRateCalculations)
                ) && 
                (
                    TotalVatPaymentsDomestic == other.TotalVatPaymentsDomestic ||
                    TotalVatPaymentsDomestic != null &&
                    TotalVatPaymentsDomestic.Equals(other.TotalVatPaymentsDomestic)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VatPerRateCalculations != null)
                    hashCode = hashCode * 59 + VatPerRateCalculations.GetHashCode();
                    if (TotalVatPaymentsDomestic != null)
                    hashCode = hashCode * 59 + TotalVatPaymentsDomestic.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InvoiceTotalVatPaymentsCalculationDomesticDto left, InvoiceTotalVatPaymentsCalculationDomesticDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InvoiceTotalVatPaymentsCalculationDomesticDto left, InvoiceTotalVatPaymentsCalculationDomesticDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
