/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// Gets or Sets PurchaseInvoiceStatus
          /// </summary>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum PurchaseInvoiceStatus
          {
              /// <summary>
              /// Enum NewEnum for New
              /// </summary>
              [EnumMember(Value = "New")]
              NewEnum = 0,
              /// <summary>
              /// Enum SeenEnum for Seen
              /// </summary>
              [EnumMember(Value = "Seen")]
              SeenEnum = 1,
              /// <summary>
              /// Enum ReNotifiedEnum for ReNotified
              /// </summary>
              [EnumMember(Value = "ReNotified")]
              ReNotifiedEnum = 2,
              /// <summary>
              /// Enum DeletedEnum for Deleted
              /// </summary>
              [EnumMember(Value = "Deleted")]
              DeletedEnum = 3,
              /// <summary>
              /// Enum ApprovedEnum for Approved
              /// </summary>
              [EnumMember(Value = "Approved")]
              ApprovedEnum = 4,
              /// <summary>
              /// Enum RejectedEnum for Rejected
              /// </summary>
              [EnumMember(Value = "Rejected")]
              RejectedEnum = 5,
              /// <summary>
              /// Enum CancelledEnum for Cancelled
              /// </summary>
              [EnumMember(Value = "Cancelled")]
              CancelledEnum = 6,
              /// <summary>
              /// Enum StornoEnum for Storno
              /// </summary>
              [EnumMember(Value = "Storno")]
              StornoEnum = 7,
              /// <summary>
              /// Enum SendingInProgressEnum for SendingInProgress
              /// </summary>
              [EnumMember(Value = "SendingInProgress")]
              SendingInProgressEnum = 8,
              /// <summary>
              /// Enum UnknownEnum for Unknown
              /// </summary>
              [EnumMember(Value = "Unknown")]
              UnknownEnum = 9          }
}
