/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SalesPrepaymentCalculationDto : IEquatable<SalesPrepaymentCalculationDto>
    { 
        /// <summary>
        /// Gets or Sets TotalPrepaymentWithoutVat
        /// </summary>

        [DataMember(Name="totalPrepaymentWithoutVat")]
        public double? TotalPrepaymentWithoutVat { get; set; }

        /// <summary>
        /// Gets or Sets PrepaymentPaidVat
        /// </summary>

        [DataMember(Name="prepaymentPaidVat")]
        public double? PrepaymentPaidVat { get; set; }

        /// <summary>
        /// Gets or Sets TotalPrepaymentInvoice
        /// </summary>

        [DataMember(Name="totalPrepaymentInvoice")]
        public double? TotalPrepaymentInvoice { get; set; }

        /// <summary>
        /// Gets or Sets PrepaymentFeeReductionForVatCategories
        /// </summary>

        [DataMember(Name="prepaymentFeeReductionForVatCategories")]
        public List<VatCategoryDetailsDto> PrepaymentFeeReductionForVatCategories { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SalesPrepaymentCalculationDto {\n");
            sb.Append("  TotalPrepaymentWithoutVat: ").Append(TotalPrepaymentWithoutVat).Append("\n");
            sb.Append("  PrepaymentPaidVat: ").Append(PrepaymentPaidVat).Append("\n");
            sb.Append("  TotalPrepaymentInvoice: ").Append(TotalPrepaymentInvoice).Append("\n");
            sb.Append("  PrepaymentFeeReductionForVatCategories: ").Append(PrepaymentFeeReductionForVatCategories).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SalesPrepaymentCalculationDto)obj);
        }

        /// <summary>
        /// Returns true if SalesPrepaymentCalculationDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SalesPrepaymentCalculationDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SalesPrepaymentCalculationDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TotalPrepaymentWithoutVat == other.TotalPrepaymentWithoutVat ||
                    TotalPrepaymentWithoutVat != null &&
                    TotalPrepaymentWithoutVat.Equals(other.TotalPrepaymentWithoutVat)
                ) && 
                (
                    PrepaymentPaidVat == other.PrepaymentPaidVat ||
                    PrepaymentPaidVat != null &&
                    PrepaymentPaidVat.Equals(other.PrepaymentPaidVat)
                ) && 
                (
                    TotalPrepaymentInvoice == other.TotalPrepaymentInvoice ||
                    TotalPrepaymentInvoice != null &&
                    TotalPrepaymentInvoice.Equals(other.TotalPrepaymentInvoice)
                ) && 
                (
                    PrepaymentFeeReductionForVatCategories == other.PrepaymentFeeReductionForVatCategories ||
                    PrepaymentFeeReductionForVatCategories != null &&
                    PrepaymentFeeReductionForVatCategories.SequenceEqual(other.PrepaymentFeeReductionForVatCategories)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TotalPrepaymentWithoutVat != null)
                    hashCode = hashCode * 59 + TotalPrepaymentWithoutVat.GetHashCode();
                    if (PrepaymentPaidVat != null)
                    hashCode = hashCode * 59 + PrepaymentPaidVat.GetHashCode();
                    if (TotalPrepaymentInvoice != null)
                    hashCode = hashCode * 59 + TotalPrepaymentInvoice.GetHashCode();
                    if (PrepaymentFeeReductionForVatCategories != null)
                    hashCode = hashCode * 59 + PrepaymentFeeReductionForVatCategories.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SalesPrepaymentCalculationDto left, SalesPrepaymentCalculationDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SalesPrepaymentCalculationDto left, SalesPrepaymentCalculationDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
