/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SmallInvoiceDto : IEquatable<SmallInvoiceDto>
    { 
        /// <summary>
        /// Gets or Sets ServiceId
        /// </summary>

        [DataMember(Name="serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>

        [DataMember(Name="invoiceId")]
        public long? InvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets SenderId
        /// </summary>

        [DataMember(Name="senderId")]
        public int? SenderId { get; set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>

        [DataMember(Name="sender")]
        public string Sender { get; set; }

        /// <summary>
        /// Gets or Sets Receiver
        /// </summary>

        [DataMember(Name="receiver")]
        public string Receiver { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>

        [DataMember(Name="invoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets AccountingDateUtc
        /// </summary>

        [DataMember(Name="accountingDateUtc")]
        public DateTime? AccountingDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets PaymentDateUtc
        /// </summary>

        [DataMember(Name="paymentDateUtc")]
        public DateTime? PaymentDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceDateUtc
        /// </summary>

        [DataMember(Name="invoiceDateUtc")]
        public DateTime? InvoiceDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceSentDateUtc
        /// </summary>

        [DataMember(Name="invoiceSentDateUtc")]
        public DateTime? InvoiceSentDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNumber
        /// </summary>

        [DataMember(Name="referenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets FineRatePerDay
        /// </summary>

        [DataMember(Name="fineRatePerDay")]
        public double? FineRatePerDay { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>

        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>

        [DataMember(Name="note")]
        public string Note { get; set; }

        /// <summary>
        /// Gets or Sets OrderNumber
        /// </summary>

        [DataMember(Name="orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>

        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets DiscountPercentage
        /// </summary>

        [DataMember(Name="discountPercentage")]
        public double? DiscountPercentage { get; set; }

        /// <summary>
        /// Gets or Sets DiscountAmount
        /// </summary>

        [DataMember(Name="discountAmount")]
        public double? DiscountAmount { get; set; }

        /// <summary>
        /// Gets or Sets SumWithoutVat
        /// </summary>

        [DataMember(Name="sumWithoutVat")]
        public double? SumWithoutVat { get; set; }

        /// <summary>
        /// Gets or Sets VatRate
        /// </summary>

        [DataMember(Name="vatRate")]
        public double? VatRate { get; set; }

        /// <summary>
        /// Gets or Sets VatSum
        /// </summary>

        [DataMember(Name="vatSum")]
        public double? VatSum { get; set; }

        /// <summary>
        /// Gets or Sets SumWithVat
        /// </summary>

        [DataMember(Name="sumWithVat")]
        public double? SumWithVat { get; set; }

        /// <summary>
        /// Gets or Sets CreatedUtc
        /// </summary>

        [DataMember(Name="createdUtc")]
        public DateTime? CreatedUtc { get; set; }

        /// <summary>
        /// Gets or Sets LastModifiedUtc
        /// </summary>

        [DataMember(Name="lastModifiedUtc")]
        public DateTime? LastModifiedUtc { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>

        [DataMember(Name="version")]
        public long? Version { get; set; }

        /// <summary>
        /// Gets or Sets ModelNumber
        /// </summary>

        [DataMember(Name="modelNumber")]
        public string ModelNumber { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverId
        /// </summary>

        [DataMember(Name="receiverId")]
        public int? ReceiverId { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverIsDeleted
        /// </summary>

        [DataMember(Name="receiverIsDeleted")]
        public bool? ReceiverIsDeleted { get; set; }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>

        [DataMember(Name="channel")]
        public int? Channel { get; set; }

        /// <summary>
        /// Gets or Sets ChannelAdress
        /// </summary>

        [DataMember(Name="channelAdress")]
        public string ChannelAdress { get; set; }

        /// <summary>
        /// Gets or Sets ServiceProvider
        /// </summary>

        [DataMember(Name="serviceProvider")]
        public string ServiceProvider { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>

        [DataMember(Name="errorCode")]
        public ErrorCodes ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>

        [DataMember(Name="status")]
        public SalesInvoiceStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets CirStatus
        /// </summary>

        [DataMember(Name="cirStatus")]
        public CirInvoiceStatus CirStatus { get; set; }

        /// <summary>
        /// Gets or Sets CirInvoiceId
        /// </summary>

        [DataMember(Name="cirInvoiceId")]
        public string CirInvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceType
        /// </summary>

        [DataMember(Name="invoiceType")]
        public InvoiceTypes InvoiceType { get; set; }

        /// <summary>
        /// Gets or Sets IspAcceptedToRepresentCompany
        /// </summary>

        [DataMember(Name="ispAcceptedToRepresentCompany")]
        public bool? IspAcceptedToRepresentCompany { get; set; }

        /// <summary>
        /// Gets or Sets IspName
        /// </summary>

        [DataMember(Name="ispName")]
        public string IspName { get; set; }

        /// <summary>
        /// Gets or Sets TotalToPay
        /// </summary>

        [DataMember(Name="totalToPay")]
        public double? TotalToPay { get; set; }

        /// <summary>
        /// Gets or Sets RoundingAmount
        /// </summary>

        [DataMember(Name="roundingAmount")]
        public double? RoundingAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SmallInvoiceDto {\n");
            sb.Append("  ServiceId: ").Append(ServiceId).Append("\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  SenderId: ").Append(SenderId).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Receiver: ").Append(Receiver).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  AccountingDateUtc: ").Append(AccountingDateUtc).Append("\n");
            sb.Append("  PaymentDateUtc: ").Append(PaymentDateUtc).Append("\n");
            sb.Append("  InvoiceDateUtc: ").Append(InvoiceDateUtc).Append("\n");
            sb.Append("  InvoiceSentDateUtc: ").Append(InvoiceSentDateUtc).Append("\n");
            sb.Append("  ReferenceNumber: ").Append(ReferenceNumber).Append("\n");
            sb.Append("  FineRatePerDay: ").Append(FineRatePerDay).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("  OrderNumber: ").Append(OrderNumber).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  DiscountPercentage: ").Append(DiscountPercentage).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  SumWithoutVat: ").Append(SumWithoutVat).Append("\n");
            sb.Append("  VatRate: ").Append(VatRate).Append("\n");
            sb.Append("  VatSum: ").Append(VatSum).Append("\n");
            sb.Append("  SumWithVat: ").Append(SumWithVat).Append("\n");
            sb.Append("  CreatedUtc: ").Append(CreatedUtc).Append("\n");
            sb.Append("  LastModifiedUtc: ").Append(LastModifiedUtc).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  ModelNumber: ").Append(ModelNumber).Append("\n");
            sb.Append("  ReceiverId: ").Append(ReceiverId).Append("\n");
            sb.Append("  ReceiverIsDeleted: ").Append(ReceiverIsDeleted).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  ChannelAdress: ").Append(ChannelAdress).Append("\n");
            sb.Append("  ServiceProvider: ").Append(ServiceProvider).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CirStatus: ").Append(CirStatus).Append("\n");
            sb.Append("  CirInvoiceId: ").Append(CirInvoiceId).Append("\n");
            sb.Append("  InvoiceType: ").Append(InvoiceType).Append("\n");
            sb.Append("  IspAcceptedToRepresentCompany: ").Append(IspAcceptedToRepresentCompany).Append("\n");
            sb.Append("  IspName: ").Append(IspName).Append("\n");
            sb.Append("  TotalToPay: ").Append(TotalToPay).Append("\n");
            sb.Append("  RoundingAmount: ").Append(RoundingAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SmallInvoiceDto)obj);
        }

        /// <summary>
        /// Returns true if SmallInvoiceDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SmallInvoiceDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SmallInvoiceDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ServiceId == other.ServiceId ||
                    ServiceId != null &&
                    ServiceId.Equals(other.ServiceId)
                ) && 
                (
                    InvoiceId == other.InvoiceId ||
                    InvoiceId != null &&
                    InvoiceId.Equals(other.InvoiceId)
                ) && 
                (
                    SenderId == other.SenderId ||
                    SenderId != null &&
                    SenderId.Equals(other.SenderId)
                ) && 
                (
                    Sender == other.Sender ||
                    Sender != null &&
                    Sender.Equals(other.Sender)
                ) && 
                (
                    Receiver == other.Receiver ||
                    Receiver != null &&
                    Receiver.Equals(other.Receiver)
                ) && 
                (
                    InvoiceNumber == other.InvoiceNumber ||
                    InvoiceNumber != null &&
                    InvoiceNumber.Equals(other.InvoiceNumber)
                ) && 
                (
                    AccountingDateUtc == other.AccountingDateUtc ||
                    AccountingDateUtc != null &&
                    AccountingDateUtc.Equals(other.AccountingDateUtc)
                ) && 
                (
                    PaymentDateUtc == other.PaymentDateUtc ||
                    PaymentDateUtc != null &&
                    PaymentDateUtc.Equals(other.PaymentDateUtc)
                ) && 
                (
                    InvoiceDateUtc == other.InvoiceDateUtc ||
                    InvoiceDateUtc != null &&
                    InvoiceDateUtc.Equals(other.InvoiceDateUtc)
                ) && 
                (
                    InvoiceSentDateUtc == other.InvoiceSentDateUtc ||
                    InvoiceSentDateUtc != null &&
                    InvoiceSentDateUtc.Equals(other.InvoiceSentDateUtc)
                ) && 
                (
                    ReferenceNumber == other.ReferenceNumber ||
                    ReferenceNumber != null &&
                    ReferenceNumber.Equals(other.ReferenceNumber)
                ) && 
                (
                    FineRatePerDay == other.FineRatePerDay ||
                    FineRatePerDay != null &&
                    FineRatePerDay.Equals(other.FineRatePerDay)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Note == other.Note ||
                    Note != null &&
                    Note.Equals(other.Note)
                ) && 
                (
                    OrderNumber == other.OrderNumber ||
                    OrderNumber != null &&
                    OrderNumber.Equals(other.OrderNumber)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    DiscountPercentage == other.DiscountPercentage ||
                    DiscountPercentage != null &&
                    DiscountPercentage.Equals(other.DiscountPercentage)
                ) && 
                (
                    DiscountAmount == other.DiscountAmount ||
                    DiscountAmount != null &&
                    DiscountAmount.Equals(other.DiscountAmount)
                ) && 
                (
                    SumWithoutVat == other.SumWithoutVat ||
                    SumWithoutVat != null &&
                    SumWithoutVat.Equals(other.SumWithoutVat)
                ) && 
                (
                    VatRate == other.VatRate ||
                    VatRate != null &&
                    VatRate.Equals(other.VatRate)
                ) && 
                (
                    VatSum == other.VatSum ||
                    VatSum != null &&
                    VatSum.Equals(other.VatSum)
                ) && 
                (
                    SumWithVat == other.SumWithVat ||
                    SumWithVat != null &&
                    SumWithVat.Equals(other.SumWithVat)
                ) && 
                (
                    CreatedUtc == other.CreatedUtc ||
                    CreatedUtc != null &&
                    CreatedUtc.Equals(other.CreatedUtc)
                ) && 
                (
                    LastModifiedUtc == other.LastModifiedUtc ||
                    LastModifiedUtc != null &&
                    LastModifiedUtc.Equals(other.LastModifiedUtc)
                ) && 
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(other.Version)
                ) && 
                (
                    ModelNumber == other.ModelNumber ||
                    ModelNumber != null &&
                    ModelNumber.Equals(other.ModelNumber)
                ) && 
                (
                    ReceiverId == other.ReceiverId ||
                    ReceiverId != null &&
                    ReceiverId.Equals(other.ReceiverId)
                ) && 
                (
                    ReceiverIsDeleted == other.ReceiverIsDeleted ||
                    ReceiverIsDeleted != null &&
                    ReceiverIsDeleted.Equals(other.ReceiverIsDeleted)
                ) && 
                (
                    Channel == other.Channel ||
                    Channel != null &&
                    Channel.Equals(other.Channel)
                ) && 
                (
                    ChannelAdress == other.ChannelAdress ||
                    ChannelAdress != null &&
                    ChannelAdress.Equals(other.ChannelAdress)
                ) && 
                (
                    ServiceProvider == other.ServiceProvider ||
                    ServiceProvider != null &&
                    ServiceProvider.Equals(other.ServiceProvider)
                ) && 
                (
                    ErrorCode == other.ErrorCode ||
                    ErrorCode != null &&
                    ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    CirStatus == other.CirStatus ||
                    CirStatus != null &&
                    CirStatus.Equals(other.CirStatus)
                ) && 
                (
                    CirInvoiceId == other.CirInvoiceId ||
                    CirInvoiceId != null &&
                    CirInvoiceId.Equals(other.CirInvoiceId)
                ) && 
                (
                    InvoiceType == other.InvoiceType ||
                    InvoiceType != null &&
                    InvoiceType.Equals(other.InvoiceType)
                ) && 
                (
                    IspAcceptedToRepresentCompany == other.IspAcceptedToRepresentCompany ||
                    IspAcceptedToRepresentCompany != null &&
                    IspAcceptedToRepresentCompany.Equals(other.IspAcceptedToRepresentCompany)
                ) && 
                (
                    IspName == other.IspName ||
                    IspName != null &&
                    IspName.Equals(other.IspName)
                ) && 
                (
                    TotalToPay == other.TotalToPay ||
                    TotalToPay != null &&
                    TotalToPay.Equals(other.TotalToPay)
                ) && 
                (
                    RoundingAmount == other.RoundingAmount ||
                    RoundingAmount != null &&
                    RoundingAmount.Equals(other.RoundingAmount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ServiceId != null)
                    hashCode = hashCode * 59 + ServiceId.GetHashCode();
                    if (InvoiceId != null)
                    hashCode = hashCode * 59 + InvoiceId.GetHashCode();
                    if (SenderId != null)
                    hashCode = hashCode * 59 + SenderId.GetHashCode();
                    if (Sender != null)
                    hashCode = hashCode * 59 + Sender.GetHashCode();
                    if (Receiver != null)
                    hashCode = hashCode * 59 + Receiver.GetHashCode();
                    if (InvoiceNumber != null)
                    hashCode = hashCode * 59 + InvoiceNumber.GetHashCode();
                    if (AccountingDateUtc != null)
                    hashCode = hashCode * 59 + AccountingDateUtc.GetHashCode();
                    if (PaymentDateUtc != null)
                    hashCode = hashCode * 59 + PaymentDateUtc.GetHashCode();
                    if (InvoiceDateUtc != null)
                    hashCode = hashCode * 59 + InvoiceDateUtc.GetHashCode();
                    if (InvoiceSentDateUtc != null)
                    hashCode = hashCode * 59 + InvoiceSentDateUtc.GetHashCode();
                    if (ReferenceNumber != null)
                    hashCode = hashCode * 59 + ReferenceNumber.GetHashCode();
                    if (FineRatePerDay != null)
                    hashCode = hashCode * 59 + FineRatePerDay.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (Note != null)
                    hashCode = hashCode * 59 + Note.GetHashCode();
                    if (OrderNumber != null)
                    hashCode = hashCode * 59 + OrderNumber.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    if (DiscountPercentage != null)
                    hashCode = hashCode * 59 + DiscountPercentage.GetHashCode();
                    if (DiscountAmount != null)
                    hashCode = hashCode * 59 + DiscountAmount.GetHashCode();
                    if (SumWithoutVat != null)
                    hashCode = hashCode * 59 + SumWithoutVat.GetHashCode();
                    if (VatRate != null)
                    hashCode = hashCode * 59 + VatRate.GetHashCode();
                    if (VatSum != null)
                    hashCode = hashCode * 59 + VatSum.GetHashCode();
                    if (SumWithVat != null)
                    hashCode = hashCode * 59 + SumWithVat.GetHashCode();
                    if (CreatedUtc != null)
                    hashCode = hashCode * 59 + CreatedUtc.GetHashCode();
                    if (LastModifiedUtc != null)
                    hashCode = hashCode * 59 + LastModifiedUtc.GetHashCode();
                    if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                    if (ModelNumber != null)
                    hashCode = hashCode * 59 + ModelNumber.GetHashCode();
                    if (ReceiverId != null)
                    hashCode = hashCode * 59 + ReceiverId.GetHashCode();
                    if (ReceiverIsDeleted != null)
                    hashCode = hashCode * 59 + ReceiverIsDeleted.GetHashCode();
                    if (Channel != null)
                    hashCode = hashCode * 59 + Channel.GetHashCode();
                    if (ChannelAdress != null)
                    hashCode = hashCode * 59 + ChannelAdress.GetHashCode();
                    if (ServiceProvider != null)
                    hashCode = hashCode * 59 + ServiceProvider.GetHashCode();
                    if (ErrorCode != null)
                    hashCode = hashCode * 59 + ErrorCode.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (CirStatus != null)
                    hashCode = hashCode * 59 + CirStatus.GetHashCode();
                    if (CirInvoiceId != null)
                    hashCode = hashCode * 59 + CirInvoiceId.GetHashCode();
                    if (InvoiceType != null)
                    hashCode = hashCode * 59 + InvoiceType.GetHashCode();
                    if (IspAcceptedToRepresentCompany != null)
                    hashCode = hashCode * 59 + IspAcceptedToRepresentCompany.GetHashCode();
                    if (IspName != null)
                    hashCode = hashCode * 59 + IspName.GetHashCode();
                    if (TotalToPay != null)
                    hashCode = hashCode * 59 + TotalToPay.GetHashCode();
                    if (RoundingAmount != null)
                    hashCode = hashCode * 59 + RoundingAmount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SmallInvoiceDto left, SmallInvoiceDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SmallInvoiceDto left, SmallInvoiceDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
