/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// Gets or Sets SortDirection
          /// </summary>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum SortDirection
          {
              /// <summary>
              /// Enum AscEnum for Asc
              /// </summary>
              [EnumMember(Value = "Asc")]
              AscEnum = 0,
              /// <summary>
              /// Enum DescEnum for Desc
              /// </summary>
              [EnumMember(Value = "Desc")]
              DescEnum = 1          }
}
