/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SspCustomerSupplierDto : IEquatable<SspCustomerSupplierDto>
    { 
        /// <summary>
        /// Gets or Sets CustomerSupplierId
        /// </summary>

        [DataMember(Name="customerSupplierId")]
        public int? CustomerSupplierId { get; set; }

        /// <summary>
        /// Gets or Sets OwnerCompanyId
        /// </summary>

        [DataMember(Name="ownerCompanyId")]
        public int? OwnerCompanyId { get; set; }

        /// <summary>
        /// Gets or Sets CountryId
        /// </summary>

        [DataMember(Name="countryId")]
        public int? CountryId { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>

        [MaxLength(500)]
        [DataMember(Name="companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationCode
        /// </summary>

        [MaxLength(15)]
        [DataMember(Name="registrationCode")]
        public string RegistrationCode { get; set; }

        /// <summary>
        /// Gets or Sets VatRegistrationCode
        /// </summary>

        [MaxLength(100)]
        [DataMember(Name="vatRegistrationCode")]
        public string VatRegistrationCode { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>

        [DataMember(Name="firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>

        [DataMember(Name="lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets PersonalId
        /// </summary>

        [DataMember(Name="personalId")]
        public string PersonalId { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>

        [MaxLength(20)]
        [DataMember(Name="phoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets IsCompany
        /// </summary>

        [DataMember(Name="isCompany")]
        public bool? IsCompany { get; set; }

        /// <summary>
        /// Gets or Sets CompanyMail
        /// </summary>

        [DataMember(Name="companyMail")]
        public string CompanyMail { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>

        [MaxLength(200)]
        [DataMember(Name="email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>

        [DataMember(Name="language")]
        public Languages Language { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalCode
        /// </summary>

        [DataMember(Name="additionalCode")]
        public string AdditionalCode { get; set; }

        /// <summary>
        /// Gets or Sets SerbiaCompanyType
        /// </summary>

        [DataMember(Name="serbiaCompanyType")]
        public SerbiaCompanyType SerbiaCompanyType { get; set; }

        /// <summary>
        /// Gets or Sets SpecialTreatment
        /// </summary>

        [DataMember(Name="specialTreatment")]
        public bool? SpecialTreatment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SspCustomerSupplierDto {\n");
            sb.Append("  CustomerSupplierId: ").Append(CustomerSupplierId).Append("\n");
            sb.Append("  OwnerCompanyId: ").Append(OwnerCompanyId).Append("\n");
            sb.Append("  CountryId: ").Append(CountryId).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  RegistrationCode: ").Append(RegistrationCode).Append("\n");
            sb.Append("  VatRegistrationCode: ").Append(VatRegistrationCode).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  PersonalId: ").Append(PersonalId).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  IsCompany: ").Append(IsCompany).Append("\n");
            sb.Append("  CompanyMail: ").Append(CompanyMail).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  AdditionalCode: ").Append(AdditionalCode).Append("\n");
            sb.Append("  SerbiaCompanyType: ").Append(SerbiaCompanyType).Append("\n");
            sb.Append("  SpecialTreatment: ").Append(SpecialTreatment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SspCustomerSupplierDto)obj);
        }

        /// <summary>
        /// Returns true if SspCustomerSupplierDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SspCustomerSupplierDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SspCustomerSupplierDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CustomerSupplierId == other.CustomerSupplierId ||
                    CustomerSupplierId != null &&
                    CustomerSupplierId.Equals(other.CustomerSupplierId)
                ) && 
                (
                    OwnerCompanyId == other.OwnerCompanyId ||
                    OwnerCompanyId != null &&
                    OwnerCompanyId.Equals(other.OwnerCompanyId)
                ) && 
                (
                    CountryId == other.CountryId ||
                    CountryId != null &&
                    CountryId.Equals(other.CountryId)
                ) && 
                (
                    CompanyName == other.CompanyName ||
                    CompanyName != null &&
                    CompanyName.Equals(other.CompanyName)
                ) && 
                (
                    RegistrationCode == other.RegistrationCode ||
                    RegistrationCode != null &&
                    RegistrationCode.Equals(other.RegistrationCode)
                ) && 
                (
                    VatRegistrationCode == other.VatRegistrationCode ||
                    VatRegistrationCode != null &&
                    VatRegistrationCode.Equals(other.VatRegistrationCode)
                ) && 
                (
                    FirstName == other.FirstName ||
                    FirstName != null &&
                    FirstName.Equals(other.FirstName)
                ) && 
                (
                    LastName == other.LastName ||
                    LastName != null &&
                    LastName.Equals(other.LastName)
                ) && 
                (
                    PersonalId == other.PersonalId ||
                    PersonalId != null &&
                    PersonalId.Equals(other.PersonalId)
                ) && 
                (
                    PhoneNumber == other.PhoneNumber ||
                    PhoneNumber != null &&
                    PhoneNumber.Equals(other.PhoneNumber)
                ) && 
                (
                    IsCompany == other.IsCompany ||
                    IsCompany != null &&
                    IsCompany.Equals(other.IsCompany)
                ) && 
                (
                    CompanyMail == other.CompanyMail ||
                    CompanyMail != null &&
                    CompanyMail.Equals(other.CompanyMail)
                ) && 
                (
                    Email == other.Email ||
                    Email != null &&
                    Email.Equals(other.Email)
                ) && 
                (
                    Language == other.Language ||
                    Language != null &&
                    Language.Equals(other.Language)
                ) && 
                (
                    AdditionalCode == other.AdditionalCode ||
                    AdditionalCode != null &&
                    AdditionalCode.Equals(other.AdditionalCode)
                ) && 
                (
                    SerbiaCompanyType == other.SerbiaCompanyType ||
                    SerbiaCompanyType != null &&
                    SerbiaCompanyType.Equals(other.SerbiaCompanyType)
                ) && 
                (
                    SpecialTreatment == other.SpecialTreatment ||
                    SpecialTreatment != null &&
                    SpecialTreatment.Equals(other.SpecialTreatment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CustomerSupplierId != null)
                    hashCode = hashCode * 59 + CustomerSupplierId.GetHashCode();
                    if (OwnerCompanyId != null)
                    hashCode = hashCode * 59 + OwnerCompanyId.GetHashCode();
                    if (CountryId != null)
                    hashCode = hashCode * 59 + CountryId.GetHashCode();
                    if (CompanyName != null)
                    hashCode = hashCode * 59 + CompanyName.GetHashCode();
                    if (RegistrationCode != null)
                    hashCode = hashCode * 59 + RegistrationCode.GetHashCode();
                    if (VatRegistrationCode != null)
                    hashCode = hashCode * 59 + VatRegistrationCode.GetHashCode();
                    if (FirstName != null)
                    hashCode = hashCode * 59 + FirstName.GetHashCode();
                    if (LastName != null)
                    hashCode = hashCode * 59 + LastName.GetHashCode();
                    if (PersonalId != null)
                    hashCode = hashCode * 59 + PersonalId.GetHashCode();
                    if (PhoneNumber != null)
                    hashCode = hashCode * 59 + PhoneNumber.GetHashCode();
                    if (IsCompany != null)
                    hashCode = hashCode * 59 + IsCompany.GetHashCode();
                    if (CompanyMail != null)
                    hashCode = hashCode * 59 + CompanyMail.GetHashCode();
                    if (Email != null)
                    hashCode = hashCode * 59 + Email.GetHashCode();
                    if (Language != null)
                    hashCode = hashCode * 59 + Language.GetHashCode();
                    if (AdditionalCode != null)
                    hashCode = hashCode * 59 + AdditionalCode.GetHashCode();
                    if (SerbiaCompanyType != null)
                    hashCode = hashCode * 59 + SerbiaCompanyType.GetHashCode();
                    if (SpecialTreatment != null)
                    hashCode = hashCode * 59 + SpecialTreatment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SspCustomerSupplierDto left, SspCustomerSupplierDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SspCustomerSupplierDto left, SspCustomerSupplierDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
