/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VatTurnoverAddDto : IEquatable<VatTurnoverAddDto>
    { 
        /// <summary>
        /// Gets or Sets TaxableAmount20
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="taxableAmount20")]
        public double? TaxableAmount20 { get; set; }

        /// <summary>
        /// Gets or Sets TaxAmount20
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="taxAmount20")]
        public double? TaxAmount20 { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount20
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="totalAmount20")]
        public double? TotalAmount20 { get; set; }

        /// <summary>
        /// Gets or Sets TaxableAmount10
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="taxableAmount10")]
        public double? TaxableAmount10 { get; set; }

        /// <summary>
        /// Gets or Sets TaxAmount10
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="taxAmount10")]
        public double? TaxAmount10 { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount10
        /// </summary>

        [Range(0, 99999999999999)]
        [DataMember(Name="totalAmount10")]
        public double? TotalAmount10 { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverDescription10
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="turnoverDescription10")]
        public string TurnoverDescription10 { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverDescription20
        /// </summary>

        [MaxLength(2000)]
        [DataMember(Name="turnoverDescription20")]
        public string TurnoverDescription20 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VatTurnoverAddDto {\n");
            sb.Append("  TaxableAmount20: ").Append(TaxableAmount20).Append("\n");
            sb.Append("  TaxAmount20: ").Append(TaxAmount20).Append("\n");
            sb.Append("  TotalAmount20: ").Append(TotalAmount20).Append("\n");
            sb.Append("  TaxableAmount10: ").Append(TaxableAmount10).Append("\n");
            sb.Append("  TaxAmount10: ").Append(TaxAmount10).Append("\n");
            sb.Append("  TotalAmount10: ").Append(TotalAmount10).Append("\n");
            sb.Append("  TurnoverDescription10: ").Append(TurnoverDescription10).Append("\n");
            sb.Append("  TurnoverDescription20: ").Append(TurnoverDescription20).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VatTurnoverAddDto)obj);
        }

        /// <summary>
        /// Returns true if VatTurnoverAddDto instances are equal
        /// </summary>
        /// <param name="other">Instance of VatTurnoverAddDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VatTurnoverAddDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TaxableAmount20 == other.TaxableAmount20 ||
                    TaxableAmount20 != null &&
                    TaxableAmount20.Equals(other.TaxableAmount20)
                ) && 
                (
                    TaxAmount20 == other.TaxAmount20 ||
                    TaxAmount20 != null &&
                    TaxAmount20.Equals(other.TaxAmount20)
                ) && 
                (
                    TotalAmount20 == other.TotalAmount20 ||
                    TotalAmount20 != null &&
                    TotalAmount20.Equals(other.TotalAmount20)
                ) && 
                (
                    TaxableAmount10 == other.TaxableAmount10 ||
                    TaxableAmount10 != null &&
                    TaxableAmount10.Equals(other.TaxableAmount10)
                ) && 
                (
                    TaxAmount10 == other.TaxAmount10 ||
                    TaxAmount10 != null &&
                    TaxAmount10.Equals(other.TaxAmount10)
                ) && 
                (
                    TotalAmount10 == other.TotalAmount10 ||
                    TotalAmount10 != null &&
                    TotalAmount10.Equals(other.TotalAmount10)
                ) && 
                (
                    TurnoverDescription10 == other.TurnoverDescription10 ||
                    TurnoverDescription10 != null &&
                    TurnoverDescription10.Equals(other.TurnoverDescription10)
                ) && 
                (
                    TurnoverDescription20 == other.TurnoverDescription20 ||
                    TurnoverDescription20 != null &&
                    TurnoverDescription20.Equals(other.TurnoverDescription20)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TaxableAmount20 != null)
                    hashCode = hashCode * 59 + TaxableAmount20.GetHashCode();
                    if (TaxAmount20 != null)
                    hashCode = hashCode * 59 + TaxAmount20.GetHashCode();
                    if (TotalAmount20 != null)
                    hashCode = hashCode * 59 + TotalAmount20.GetHashCode();
                    if (TaxableAmount10 != null)
                    hashCode = hashCode * 59 + TaxableAmount10.GetHashCode();
                    if (TaxAmount10 != null)
                    hashCode = hashCode * 59 + TaxAmount10.GetHashCode();
                    if (TotalAmount10 != null)
                    hashCode = hashCode * 59 + TotalAmount10.GetHashCode();
                    if (TurnoverDescription10 != null)
                    hashCode = hashCode * 59 + TurnoverDescription10.GetHashCode();
                    if (TurnoverDescription20 != null)
                    hashCode = hashCode * 59 + TurnoverDescription20.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(VatTurnoverAddDto left, VatTurnoverAddDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VatTurnoverAddDto left, VatTurnoverAddDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
