/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using eFaktureModel.Api.Models.Enums;

namespace eFaktureModel.Api.Models.Vat
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class IndividualVatListDto : IEquatable<IndividualVatListDto>
    {
        /// <summary>
        /// Gets or Sets IndividualVatId
        /// </summary>

        [DataMember(Name = "individualVatId")]
        public int? IndividualVatId { get; set; }

        /// <summary>
        /// Gets or Sets Year
        /// </summary>

        [DataMember(Name = "year")]
        public int? Year { get; set; }

        /// <summary>
        /// Gets or Sets DocumentNumber
        /// </summary>

        [DataMember(Name = "documentNumber")]
        public string DocumentNumber { get; set; }

        /// <summary>
        /// Gets or Sets VatRecordingStatus
        /// </summary>

        [DataMember(Name = "vatRecordingStatus")]
        public VatRecordingStatus VatRecordingStatus { get; set; }

        /// <summary>
        /// Gets or Sets SendDate
        /// </summary>

        [DataMember(Name = "sendDate")]
        public DateTime? SendDate { get; set; }

        /// <summary>
        /// Gets or Sets DocumentType
        /// </summary>

        [DataMember(Name = "documentType")]
        public VatRecordingDocumentType DocumentType { get; set; }

        /// <summary>
        /// Gets or Sets TurnoverAmount
        /// </summary>

        [DataMember(Name = "turnoverAmount")]
        public double? TurnoverAmount { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount
        /// </summary>

        [DataMember(Name = "vatAmount")]
        public double? VatAmount { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount10
        /// </summary>

        [DataMember(Name = "vatAmount10")]
        public double? VatAmount10 { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount20
        /// </summary>

        [DataMember(Name = "vatAmount20")]
        public double? VatAmount20 { get; set; }

        /// <summary>
        /// Gets or Sets VatDeductionRight
        /// </summary>

        [DataMember(Name = "vatDeductionRight")]
        public VatDeductionRight VatDeductionRight { get; set; }

        /// <summary>
        /// Gets or Sets BasisForPrepayment
        /// </summary>

        [DataMember(Name = "basisForPrepayment")]
        public string BasisForPrepayment { get; set; }

        /// <summary>
        /// Gets or Sets DocumentDirection
        /// </summary>

        [DataMember(Name = "documentDirection")]
        public DocumentDirection DocumentDirection { get; set; }

        /// <summary>
        /// Gets or Sets RelatedPartyIdentifier
        /// </summary>

        [DataMember(Name = "relatedPartyIdentifier")]
        public string RelatedPartyIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets ForeignDocument
        /// </summary>

        [DataMember(Name = "foreignDocument")]
        public bool? ForeignDocument { get; set; }

        /// <summary>
        /// Gets or Sets VatRecordingVersion
        /// </summary>

        [DataMember(Name = "vatRecordingVersion")]
        public VatRecordVersion VatRecordingVersion { get; set; }

        /// <summary>
        /// Gets or Sets CalculationNumber
        /// </summary>

        [DataMember(Name = "calculationNumber")]
        public string CalculationNumber { get; set; }

        /// <summary>
        /// Gets or Sets InternalInvoiceOption
        /// </summary>

        [DataMember(Name = "internalInvoiceOption")]
        public InternalInvoiceOption InternalInvoiceOption { get; set; }

        /// <summary>
        /// Gets or Sets VatPeriod
        /// </summary>

        [DataMember(Name = "vatPeriod")]
        public VatPeriod VatPeriod { get; set; }

        /// <summary>
        /// Gets or Sets CreatedUtc
        /// </summary>

        [DataMember(Name = "createdUtc")]
        public DateTime? CreatedUtc { get; set; }

        /// <summary>
        /// Gets or Sets StatusChangeDate
        /// </summary>

        [DataMember(Name = "statusChangeDate")]
        public DateTime? StatusChangeDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IndividualVatListDto {\n");
            sb.Append("  IndividualVatId: ").Append(IndividualVatId).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  DocumentNumber: ").Append(DocumentNumber).Append("\n");
            sb.Append("  VatRecordingStatus: ").Append(VatRecordingStatus).Append("\n");
            sb.Append("  SendDate: ").Append(SendDate).Append("\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  TurnoverAmount: ").Append(TurnoverAmount).Append("\n");
            sb.Append("  VatAmount: ").Append(VatAmount).Append("\n");
            sb.Append("  VatAmount10: ").Append(VatAmount10).Append("\n");
            sb.Append("  VatAmount20: ").Append(VatAmount20).Append("\n");
            sb.Append("  VatDeductionRight: ").Append(VatDeductionRight).Append("\n");
            sb.Append("  BasisForPrepayment: ").Append(BasisForPrepayment).Append("\n");
            sb.Append("  DocumentDirection: ").Append(DocumentDirection).Append("\n");
            sb.Append("  RelatedPartyIdentifier: ").Append(RelatedPartyIdentifier).Append("\n");
            sb.Append("  ForeignDocument: ").Append(ForeignDocument).Append("\n");
            sb.Append("  VatRecordingVersion: ").Append(VatRecordingVersion).Append("\n");
            sb.Append("  CalculationNumber: ").Append(CalculationNumber).Append("\n");
            sb.Append("  InternalInvoiceOption: ").Append(InternalInvoiceOption).Append("\n");
            sb.Append("  VatPeriod: ").Append(VatPeriod).Append("\n");
            sb.Append("  CreatedUtc: ").Append(CreatedUtc).Append("\n");
            sb.Append("  StatusChangeDate: ").Append(StatusChangeDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IndividualVatListDto)obj);
        }

        /// <summary>
        /// Returns true if IndividualVatListDto instances are equal
        /// </summary>
        /// <param name="other">Instance of IndividualVatListDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IndividualVatListDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    IndividualVatId == other.IndividualVatId ||
                    IndividualVatId != null &&
                    IndividualVatId.Equals(other.IndividualVatId)
                ) &&
                (
                    Year == other.Year ||
                    Year != null &&
                    Year.Equals(other.Year)
                ) &&
                (
                    DocumentNumber == other.DocumentNumber ||
                    DocumentNumber != null &&
                    DocumentNumber.Equals(other.DocumentNumber)
                ) &&
                (
                    VatRecordingStatus == other.VatRecordingStatus ||
                    VatRecordingStatus != null &&
                    VatRecordingStatus.Equals(other.VatRecordingStatus)
                ) &&
                (
                    SendDate == other.SendDate ||
                    SendDate != null &&
                    SendDate.Equals(other.SendDate)
                ) &&
                (
                    DocumentType == other.DocumentType ||
                    DocumentType != null &&
                    DocumentType.Equals(other.DocumentType)
                ) &&
                (
                    TurnoverAmount == other.TurnoverAmount ||
                    TurnoverAmount != null &&
                    TurnoverAmount.Equals(other.TurnoverAmount)
                ) &&
                (
                    VatAmount == other.VatAmount ||
                    VatAmount != null &&
                    VatAmount.Equals(other.VatAmount)
                ) &&
                (
                    VatAmount10 == other.VatAmount10 ||
                    VatAmount10 != null &&
                    VatAmount10.Equals(other.VatAmount10)
                ) &&
                (
                    VatAmount20 == other.VatAmount20 ||
                    VatAmount20 != null &&
                    VatAmount20.Equals(other.VatAmount20)
                ) &&
                (
                    VatDeductionRight == other.VatDeductionRight ||
                    VatDeductionRight != null &&
                    VatDeductionRight.Equals(other.VatDeductionRight)
                ) &&
                (
                    BasisForPrepayment == other.BasisForPrepayment ||
                    BasisForPrepayment != null &&
                    BasisForPrepayment.Equals(other.BasisForPrepayment)
                ) &&
                (
                    DocumentDirection == other.DocumentDirection ||
                    DocumentDirection != null &&
                    DocumentDirection.Equals(other.DocumentDirection)
                ) &&
                (
                    RelatedPartyIdentifier == other.RelatedPartyIdentifier ||
                    RelatedPartyIdentifier != null &&
                    RelatedPartyIdentifier.Equals(other.RelatedPartyIdentifier)
                ) &&
                (
                    ForeignDocument == other.ForeignDocument ||
                    ForeignDocument != null &&
                    ForeignDocument.Equals(other.ForeignDocument)
                ) &&
                (
                    VatRecordingVersion == other.VatRecordingVersion ||
                    VatRecordingVersion != null &&
                    VatRecordingVersion.Equals(other.VatRecordingVersion)
                ) &&
                (
                    CalculationNumber == other.CalculationNumber ||
                    CalculationNumber != null &&
                    CalculationNumber.Equals(other.CalculationNumber)
                ) &&
                (
                    InternalInvoiceOption == other.InternalInvoiceOption ||
                    InternalInvoiceOption != null &&
                    InternalInvoiceOption.Equals(other.InternalInvoiceOption)
                ) &&
                (
                    VatPeriod == other.VatPeriod ||
                    VatPeriod != null &&
                    VatPeriod.Equals(other.VatPeriod)
                ) &&
                (
                    CreatedUtc == other.CreatedUtc ||
                    CreatedUtc != null &&
                    CreatedUtc.Equals(other.CreatedUtc)
                ) &&
                (
                    StatusChangeDate == other.StatusChangeDate ||
                    StatusChangeDate != null &&
                    StatusChangeDate.Equals(other.StatusChangeDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (IndividualVatId != null)
                    hashCode = hashCode * 59 + IndividualVatId.GetHashCode();
                if (Year != null)
                    hashCode = hashCode * 59 + Year.GetHashCode();
                if (DocumentNumber != null)
                    hashCode = hashCode * 59 + DocumentNumber.GetHashCode();
                if (VatRecordingStatus != null)
                    hashCode = hashCode * 59 + VatRecordingStatus.GetHashCode();
                if (SendDate != null)
                    hashCode = hashCode * 59 + SendDate.GetHashCode();
                if (DocumentType != null)
                    hashCode = hashCode * 59 + DocumentType.GetHashCode();
                if (TurnoverAmount != null)
                    hashCode = hashCode * 59 + TurnoverAmount.GetHashCode();
                if (VatAmount != null)
                    hashCode = hashCode * 59 + VatAmount.GetHashCode();
                if (VatAmount10 != null)
                    hashCode = hashCode * 59 + VatAmount10.GetHashCode();
                if (VatAmount20 != null)
                    hashCode = hashCode * 59 + VatAmount20.GetHashCode();
                if (VatDeductionRight != null)
                    hashCode = hashCode * 59 + VatDeductionRight.GetHashCode();
                if (BasisForPrepayment != null)
                    hashCode = hashCode * 59 + BasisForPrepayment.GetHashCode();
                if (DocumentDirection != null)
                    hashCode = hashCode * 59 + DocumentDirection.GetHashCode();
                if (RelatedPartyIdentifier != null)
                    hashCode = hashCode * 59 + RelatedPartyIdentifier.GetHashCode();
                if (ForeignDocument != null)
                    hashCode = hashCode * 59 + ForeignDocument.GetHashCode();
                if (VatRecordingVersion != null)
                    hashCode = hashCode * 59 + VatRecordingVersion.GetHashCode();
                if (CalculationNumber != null)
                    hashCode = hashCode * 59 + CalculationNumber.GetHashCode();
                if (InternalInvoiceOption != null)
                    hashCode = hashCode * 59 + InternalInvoiceOption.GetHashCode();
                if (VatPeriod != null)
                    hashCode = hashCode * 59 + VatPeriod.GetHashCode();
                if (CreatedUtc != null)
                    hashCode = hashCode * 59 + CreatedUtc.GetHashCode();
                if (StatusChangeDate != null)
                    hashCode = hashCode * 59 + StatusChangeDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(IndividualVatListDto left, IndividualVatListDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IndividualVatListDto left, IndividualVatListDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
