/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using eFaktureModel.Api.Models.Dto;

namespace eFaktureModel.Api.Enums.Company
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SspContractDto : IEquatable<SspContractDto>
    {
        /// <summary>
        /// Gets or Sets ContractId
        /// </summary>

        [DataMember(Name = "contractId")]
        public int? ContractId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerSupplier
        /// </summary>
        [Required]

        [DataMember(Name = "customerSupplier")]
        public SspCustomerSupplierDto CustomerSupplier { get; set; }

        /// <summary>
        /// Gets or Sets CustomerSupplierId
        /// </summary>

        [DataMember(Name = "customerSupplierId")]
        public int? CustomerSupplierId { get; set; }

        /// <summary>
        /// Gets or Sets PaymentTerms
        /// </summary>

        [Range(0, 9999)]
        [DataMember(Name = "paymentTerms")]
        public int? PaymentTerms { get; set; }

        /// <summary>
        /// Gets or Sets FineRatePerDay
        /// </summary>

        [Range(0, 9999)]
        [DataMember(Name = "fineRatePerDay")]
        public double? FineRatePerDay { get; set; }

        /// <summary>
        /// Gets or Sets ServiceId
        /// </summary>

        [MaxLength(20)]
        [DataMember(Name = "serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNr
        /// </summary>

        [MaxLength(20)]
        [DataMember(Name = "referenceNr")]
        public string ReferenceNr { get; set; }

        /// <summary>
        /// Gets or Sets ContactPersonName
        /// </summary>

        [MaxLength(100)]
        [DataMember(Name = "contactPersonName")]
        public string ContactPersonName { get; set; }

        /// <summary>
        /// Gets or Sets ContactPersonMail
        /// </summary>

        [DataMember(Name = "contactPersonMail")]
        public string ContactPersonMail { get; set; }

        /// <summary>
        /// Gets or Sets ContractDesc
        /// </summary>

        [DataMember(Name = "contractDesc")]
        public string ContractDesc { get; set; }

        /// <summary>
        /// Gets or Sets Addresses
        /// </summary>

        [DataMember(Name = "addresses")]
        public List<SspAddressDto> Addresses { get; set; }

        /// <summary>
        /// Gets or Sets CompanyAddress
        /// </summary>

        [DataMember(Name = "companyAddress")]
        public SspAddressDto CompanyAddress { get; set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>

        [DataMember(Name = "customFields")]
        public List<ContractCustomFieldDto> CustomFields { get; set; }

        /// <summary>
        /// Gets or Sets Channels
        /// </summary>

        [DataMember(Name = "channels")]
        public List<int?> Channels { get; set; }

        /// <summary>
        /// Gets or Sets IsDeleted
        /// </summary>

        [DataMember(Name = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// Gets or Sets OwnerCompanyId
        /// </summary>

        [DataMember(Name = "ownerCompanyId")]
        public int? OwnerCompanyId { get; set; }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>

        [DataMember(Name = "channel")]
        public int? Channel { get; set; }

        /// <summary>
        /// Gets or Sets ChannelAddress
        /// </summary>

        [DataMember(Name = "channelAddress")]
        public string ChannelAddress { get; set; }

        /// <summary>
        /// Gets or Sets ServiceProvider
        /// </summary>

        [DataMember(Name = "serviceProvider")]
        public string ServiceProvider { get; set; }

        /// <summary>
        /// Gets or Sets ContractNumber
        /// </summary>

        [DataMember(Name = "contractNumber")]
        public int? ContractNumber { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNotificationEmail
        /// </summary>

        [DataMember(Name = "invoiceNotificationEmail")]
        public string InvoiceNotificationEmail { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceCurrency
        /// </summary>

        [MaxLength(3)]
        [DataMember(Name = "invoiceCurrency")]
        public string InvoiceCurrency { get; set; }

        /// <summary>
        /// Gets or Sets IsBudgetClient
        /// </summary>

        [DataMember(Name = "isBudgetClient")]
        public bool? IsBudgetClient { get; set; }

        /// <summary>
        /// Gets or Sets SendInvoiceToCir
        /// </summary>

        [DataMember(Name = "sendInvoiceToCir")]
        public bool? SendInvoiceToCir { get; set; }

        /// <summary>
        /// Gets or Sets AvailableContracts
        /// </summary>

        [DataMember(Name = "availableContracts")]
        public List<string> AvailableContracts { get; set; }

        /// <summary>
        /// Gets or Sets ContractApplication
        /// </summary>

        [DataMember(Name = "contractApplication")]
        public ContractApplicationDto ContractApplication { get; set; }

        /// <summary>
        /// Gets or Sets IsReceiverCompanyDeleted
        /// </summary>

        [DataMember(Name = "isReceiverCompanyDeleted")]
        public bool? IsReceiverCompanyDeleted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SspContractDto {\n");
            sb.Append("  ContractId: ").Append(ContractId).Append("\n");
            sb.Append("  CustomerSupplier: ").Append(CustomerSupplier).Append("\n");
            sb.Append("  CustomerSupplierId: ").Append(CustomerSupplierId).Append("\n");
            sb.Append("  PaymentTerms: ").Append(PaymentTerms).Append("\n");
            sb.Append("  FineRatePerDay: ").Append(FineRatePerDay).Append("\n");
            sb.Append("  ServiceId: ").Append(ServiceId).Append("\n");
            sb.Append("  ReferenceNr: ").Append(ReferenceNr).Append("\n");
            sb.Append("  ContactPersonName: ").Append(ContactPersonName).Append("\n");
            sb.Append("  ContactPersonMail: ").Append(ContactPersonMail).Append("\n");
            sb.Append("  ContractDesc: ").Append(ContractDesc).Append("\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  CompanyAddress: ").Append(CompanyAddress).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  Channels: ").Append(Channels).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  OwnerCompanyId: ").Append(OwnerCompanyId).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  ChannelAddress: ").Append(ChannelAddress).Append("\n");
            sb.Append("  ServiceProvider: ").Append(ServiceProvider).Append("\n");
            sb.Append("  ContractNumber: ").Append(ContractNumber).Append("\n");
            sb.Append("  InvoiceNotificationEmail: ").Append(InvoiceNotificationEmail).Append("\n");
            sb.Append("  InvoiceCurrency: ").Append(InvoiceCurrency).Append("\n");
            sb.Append("  IsBudgetClient: ").Append(IsBudgetClient).Append("\n");
            sb.Append("  SendInvoiceToCir: ").Append(SendInvoiceToCir).Append("\n");
            sb.Append("  AvailableContracts: ").Append(AvailableContracts).Append("\n");
            sb.Append("  ContractApplication: ").Append(ContractApplication).Append("\n");
            sb.Append("  IsReceiverCompanyDeleted: ").Append(IsReceiverCompanyDeleted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SspContractDto)obj);
        }

        /// <summary>
        /// Returns true if SspContractDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SspContractDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SspContractDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    ContractId == other.ContractId ||
                    ContractId != null &&
                    ContractId.Equals(other.ContractId)
                ) &&
                (
                    CustomerSupplier == other.CustomerSupplier ||
                    CustomerSupplier != null &&
                    CustomerSupplier.Equals(other.CustomerSupplier)
                ) &&
                (
                    CustomerSupplierId == other.CustomerSupplierId ||
                    CustomerSupplierId != null &&
                    CustomerSupplierId.Equals(other.CustomerSupplierId)
                ) &&
                (
                    PaymentTerms == other.PaymentTerms ||
                    PaymentTerms != null &&
                    PaymentTerms.Equals(other.PaymentTerms)
                ) &&
                (
                    FineRatePerDay == other.FineRatePerDay ||
                    FineRatePerDay != null &&
                    FineRatePerDay.Equals(other.FineRatePerDay)
                ) &&
                (
                    ServiceId == other.ServiceId ||
                    ServiceId != null &&
                    ServiceId.Equals(other.ServiceId)
                ) &&
                (
                    ReferenceNr == other.ReferenceNr ||
                    ReferenceNr != null &&
                    ReferenceNr.Equals(other.ReferenceNr)
                ) &&
                (
                    ContactPersonName == other.ContactPersonName ||
                    ContactPersonName != null &&
                    ContactPersonName.Equals(other.ContactPersonName)
                ) &&
                (
                    ContactPersonMail == other.ContactPersonMail ||
                    ContactPersonMail != null &&
                    ContactPersonMail.Equals(other.ContactPersonMail)
                ) &&
                (
                    ContractDesc == other.ContractDesc ||
                    ContractDesc != null &&
                    ContractDesc.Equals(other.ContractDesc)
                ) &&
                (
                    Addresses == other.Addresses ||
                    Addresses != null &&
                    Addresses.SequenceEqual(other.Addresses)
                ) &&
                (
                    CompanyAddress == other.CompanyAddress ||
                    CompanyAddress != null &&
                    CompanyAddress.Equals(other.CompanyAddress)
                ) &&
                (
                    CustomFields == other.CustomFields ||
                    CustomFields != null &&
                    CustomFields.SequenceEqual(other.CustomFields)
                ) &&
                (
                    Channels == other.Channels ||
                    Channels != null &&
                    Channels.SequenceEqual(other.Channels)
                ) &&
                (
                    IsDeleted == other.IsDeleted ||
                    IsDeleted != null &&
                    IsDeleted.Equals(other.IsDeleted)
                ) &&
                (
                    OwnerCompanyId == other.OwnerCompanyId ||
                    OwnerCompanyId != null &&
                    OwnerCompanyId.Equals(other.OwnerCompanyId)
                ) &&
                (
                    Channel == other.Channel ||
                    Channel != null &&
                    Channel.Equals(other.Channel)
                ) &&
                (
                    ChannelAddress == other.ChannelAddress ||
                    ChannelAddress != null &&
                    ChannelAddress.Equals(other.ChannelAddress)
                ) &&
                (
                    ServiceProvider == other.ServiceProvider ||
                    ServiceProvider != null &&
                    ServiceProvider.Equals(other.ServiceProvider)
                ) &&
                (
                    ContractNumber == other.ContractNumber ||
                    ContractNumber != null &&
                    ContractNumber.Equals(other.ContractNumber)
                ) &&
                (
                    InvoiceNotificationEmail == other.InvoiceNotificationEmail ||
                    InvoiceNotificationEmail != null &&
                    InvoiceNotificationEmail.Equals(other.InvoiceNotificationEmail)
                ) &&
                (
                    InvoiceCurrency == other.InvoiceCurrency ||
                    InvoiceCurrency != null &&
                    InvoiceCurrency.Equals(other.InvoiceCurrency)
                ) &&
                (
                    IsBudgetClient == other.IsBudgetClient ||
                    IsBudgetClient != null &&
                    IsBudgetClient.Equals(other.IsBudgetClient)
                ) &&
                (
                    SendInvoiceToCir == other.SendInvoiceToCir ||
                    SendInvoiceToCir != null &&
                    SendInvoiceToCir.Equals(other.SendInvoiceToCir)
                ) &&
                (
                    AvailableContracts == other.AvailableContracts ||
                    AvailableContracts != null &&
                    AvailableContracts.SequenceEqual(other.AvailableContracts)
                ) &&
                (
                    ContractApplication == other.ContractApplication ||
                    ContractApplication != null &&
                    ContractApplication.Equals(other.ContractApplication)
                ) &&
                (
                    IsReceiverCompanyDeleted == other.IsReceiverCompanyDeleted ||
                    IsReceiverCompanyDeleted != null &&
                    IsReceiverCompanyDeleted.Equals(other.IsReceiverCompanyDeleted)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (ContractId != null)
                    hashCode = hashCode * 59 + ContractId.GetHashCode();
                if (CustomerSupplier != null)
                    hashCode = hashCode * 59 + CustomerSupplier.GetHashCode();
                if (CustomerSupplierId != null)
                    hashCode = hashCode * 59 + CustomerSupplierId.GetHashCode();
                if (PaymentTerms != null)
                    hashCode = hashCode * 59 + PaymentTerms.GetHashCode();
                if (FineRatePerDay != null)
                    hashCode = hashCode * 59 + FineRatePerDay.GetHashCode();
                if (ServiceId != null)
                    hashCode = hashCode * 59 + ServiceId.GetHashCode();
                if (ReferenceNr != null)
                    hashCode = hashCode * 59 + ReferenceNr.GetHashCode();
                if (ContactPersonName != null)
                    hashCode = hashCode * 59 + ContactPersonName.GetHashCode();
                if (ContactPersonMail != null)
                    hashCode = hashCode * 59 + ContactPersonMail.GetHashCode();
                if (ContractDesc != null)
                    hashCode = hashCode * 59 + ContractDesc.GetHashCode();
                if (Addresses != null)
                    hashCode = hashCode * 59 + Addresses.GetHashCode();
                if (CompanyAddress != null)
                    hashCode = hashCode * 59 + CompanyAddress.GetHashCode();
                if (CustomFields != null)
                    hashCode = hashCode * 59 + CustomFields.GetHashCode();
                if (Channels != null)
                    hashCode = hashCode * 59 + Channels.GetHashCode();
                if (IsDeleted != null)
                    hashCode = hashCode * 59 + IsDeleted.GetHashCode();
                if (OwnerCompanyId != null)
                    hashCode = hashCode * 59 + OwnerCompanyId.GetHashCode();
                if (Channel != null)
                    hashCode = hashCode * 59 + Channel.GetHashCode();
                if (ChannelAddress != null)
                    hashCode = hashCode * 59 + ChannelAddress.GetHashCode();
                if (ServiceProvider != null)
                    hashCode = hashCode * 59 + ServiceProvider.GetHashCode();
                if (ContractNumber != null)
                    hashCode = hashCode * 59 + ContractNumber.GetHashCode();
                if (InvoiceNotificationEmail != null)
                    hashCode = hashCode * 59 + InvoiceNotificationEmail.GetHashCode();
                if (InvoiceCurrency != null)
                    hashCode = hashCode * 59 + InvoiceCurrency.GetHashCode();
                if (IsBudgetClient != null)
                    hashCode = hashCode * 59 + IsBudgetClient.GetHashCode();
                if (SendInvoiceToCir != null)
                    hashCode = hashCode * 59 + SendInvoiceToCir.GetHashCode();
                if (AvailableContracts != null)
                    hashCode = hashCode * 59 + AvailableContracts.GetHashCode();
                if (ContractApplication != null)
                    hashCode = hashCode * 59 + ContractApplication.GetHashCode();
                if (IsReceiverCompanyDeleted != null)
                    hashCode = hashCode * 59 + IsReceiverCompanyDeleted.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SspContractDto left, SspContractDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SspContractDto left, SspContractDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
