/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Company.Enums
{

    /// <summary>
    /// Gets or Sets SspModules
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SspModules
    {
        /// <summary>
        /// Enum RootEnum for root
        /// </summary>
        [EnumMember(Value = "root")]
        RootEnum = 0,
        /// <summary>
        /// Enum DashboardEnum for dashboard
        /// </summary>
        [EnumMember(Value = "dashboard")]
        DashboardEnum = 1,
        /// <summary>
        /// Enum SalesInvoicesEnum for salesInvoices
        /// </summary>
        [EnumMember(Value = "salesInvoices")]
        SalesInvoicesEnum = 2,
        /// <summary>
        /// Enum SalesInvoiceNewEnum for salesInvoiceNew
        /// </summary>
        [EnumMember(Value = "salesInvoiceNew")]
        SalesInvoiceNewEnum = 3,
        /// <summary>
        /// Enum SalesInvoiceEditEnum for salesInvoiceEdit
        /// </summary>
        [EnumMember(Value = "salesInvoiceEdit")]
        SalesInvoiceEditEnum = 4,
        /// <summary>
        /// Enum SalesInvoicePreviewEnum for salesInvoicePreview
        /// </summary>
        [EnumMember(Value = "salesInvoicePreview")]
        SalesInvoicePreviewEnum = 5,
        /// <summary>
        /// Enum SalesInvoiceViewEnum for salesInvoiceView
        /// </summary>
        [EnumMember(Value = "salesInvoiceView")]
        SalesInvoiceViewEnum = 6,
        /// <summary>
        /// Enum PurchasesEnum for purchases
        /// </summary>
        [EnumMember(Value = "purchases")]
        PurchasesEnum = 7,
        /// <summary>
        /// Enum PurchaseInvoiceEditEnum for purchaseInvoiceEdit
        /// </summary>
        [EnumMember(Value = "purchaseInvoiceEdit")]
        PurchaseInvoiceEditEnum = 8,
        /// <summary>
        /// Enum PurchaseInvoicePublicEnum for purchaseInvoicePublic
        /// </summary>
        [EnumMember(Value = "purchaseInvoicePublic")]
        PurchaseInvoicePublicEnum = 9,
        /// <summary>
        /// Enum SettingsEnum for settings
        /// </summary>
        [EnumMember(Value = "settings")]
        SettingsEnum = 10,
        /// <summary>
        /// Enum LoginEnum for login
        /// </summary>
        [EnumMember(Value = "login")]
        LoginEnum = 11,
        /// <summary>
        /// Enum MyDetailsEnum for myDetails
        /// </summary>
        [EnumMember(Value = "myDetails")]
        MyDetailsEnum = 12,
        /// <summary>
        /// Enum UsersListEnum for usersList
        /// </summary>
        [EnumMember(Value = "usersList")]
        UsersListEnum = 13,
        /// <summary>
        /// Enum UserEditEnum for userEdit
        /// </summary>
        [EnumMember(Value = "userEdit")]
        UserEditEnum = 14,
        /// <summary>
        /// Enum RegistersEnum for registers
        /// </summary>
        [EnumMember(Value = "registers")]
        RegistersEnum = 15,
        /// <summary>
        /// Enum BillingEnum for billing
        /// </summary>
        [EnumMember(Value = "billing")]
        BillingEnum = 16,
        /// <summary>
        /// Enum CompanyDetailsEnum for companyDetails
        /// </summary>
        [EnumMember(Value = "companyDetails")]
        CompanyDetailsEnum = 17,
        /// <summary>
        /// Enum ContactsListEnum for contactsList
        /// </summary>
        [EnumMember(Value = "contactsList")]
        ContactsListEnum = 18,
        /// <summary>
        /// Enum InvoiceSettingsEnum for invoiceSettings
        /// </summary>
        [EnumMember(Value = "invoiceSettings")]
        InvoiceSettingsEnum = 19,
        /// <summary>
        /// Enum ProductsListEnum for productsList
        /// </summary>
        [EnumMember(Value = "productsList")]
        ProductsListEnum = 20,
        /// <summary>
        /// Enum ProductEditEnum for productEdit
        /// </summary>
        [EnumMember(Value = "productEdit")]
        ProductEditEnum = 21,
        /// <summary>
        /// Enum SearchResultsEnum for searchResults
        /// </summary>
        [EnumMember(Value = "searchResults")]
        SearchResultsEnum = 22,
        /// <summary>
        /// Enum ConversationEnum for conversation
        /// </summary>
        [EnumMember(Value = "conversation")]
        ConversationEnum = 23,
        /// <summary>
        /// Enum FilesEnum for files
        /// </summary>
        [EnumMember(Value = "files")]
        FilesEnum = 24,
        /// <summary>
        /// Enum FilesAddEnum for filesAdd
        /// </summary>
        [EnumMember(Value = "filesAdd")]
        FilesAddEnum = 25,
        /// <summary>
        /// Enum FilesEditEnum for filesEdit
        /// </summary>
        [EnumMember(Value = "filesEdit")]
        FilesEditEnum = 26,
        /// <summary>
        /// Enum SalesInvoiceUploadEnum for salesInvoiceUpload
        /// </summary>
        [EnumMember(Value = "salesInvoiceUpload")]
        SalesInvoiceUploadEnum = 27,
        /// <summary>
        /// Enum CompanyListEnum for companyList
        /// </summary>
        [EnumMember(Value = "companyList")]
        CompanyListEnum = 28,
        /// <summary>
        /// Enum TunnelPageEnum for tunnelPage
        /// </summary>
        [EnumMember(Value = "tunnelPage")]
        TunnelPageEnum = 29,
        /// <summary>
        /// Enum PackagesEnum for packages
        /// </summary>
        [EnumMember(Value = "packages")]
        PackagesEnum = 30,
        /// <summary>
        /// Enum ContactsEditEnum for contactsEdit
        /// </summary>
        [EnumMember(Value = "contactsEdit")]
        ContactsEditEnum = 31,
        /// <summary>
        /// Enum ApiManagementEnum for apiManagement
        /// </summary>
        [EnumMember(Value = "apiManagement")]
        ApiManagementEnum = 32,
        /// <summary>
        /// Enum SalesAttachmentUploadEnum for salesAttachmentUpload
        /// </summary>
        [EnumMember(Value = "salesAttachmentUpload")]
        SalesAttachmentUploadEnum = 33,
        /// <summary>
        /// Enum InvoiceMessagesEnum for invoiceMessages
        /// </summary>
        [EnumMember(Value = "invoiceMessages")]
        InvoiceMessagesEnum = 34,
        /// <summary>
        /// Enum AddCompanyEnum for addCompany
        /// </summary>
        [EnumMember(Value = "addCompany")]
        AddCompanyEnum = 35,
        /// <summary>
        /// Enum ContractApplicationsEnum for contractApplications
        /// </summary>
        [EnumMember(Value = "contractApplications")]
        ContractApplicationsEnum = 36,
        /// <summary>
        /// Enum ContractApplicationsUpdateEnum for contractApplicationsUpdate
        /// </summary>
        [EnumMember(Value = "contractApplicationsUpdate")]
        ContractApplicationsUpdateEnum = 37,
        /// <summary>
        /// Enum SalesInvoiceCopyEnum for salesInvoiceCopy
        /// </summary>
        [EnumMember(Value = "salesInvoiceCopy")]
        SalesInvoiceCopyEnum = 38,
        /// <summary>
        /// Enum CompanyNameFromRegisterEnum for companyNameFromRegister
        /// </summary>
        [EnumMember(Value = "companyNameFromRegister")]
        CompanyNameFromRegisterEnum = 39,
        /// <summary>
        /// Enum SalesInvoiceCirEditEnum for salesInvoiceCirEdit
        /// </summary>
        [EnumMember(Value = "salesInvoiceCirEdit")]
        SalesInvoiceCirEditEnum = 40,
        /// <summary>
        /// Enum PurchaseInvoiceCirEditEnum for purchaseInvoiceCirEdit
        /// </summary>
        [EnumMember(Value = "purchaseInvoiceCirEdit")]
        PurchaseInvoiceCirEditEnum = 41,
        /// <summary>
        /// Enum ChangePackageEnum for changePackage
        /// </summary>
        [EnumMember(Value = "changePackage")]
        ChangePackageEnum = 42,
        /// <summary>
        /// Enum OneClickOrderEnum for oneClickOrder
        /// </summary>
        [EnumMember(Value = "oneClickOrder")]
        OneClickOrderEnum = 43,
        /// <summary>
        /// Enum CompanyLogoEnum for companyLogo
        /// </summary>
        [EnumMember(Value = "companyLogo")]
        CompanyLogoEnum = 44,
        /// <summary>
        /// Enum CirTicketsEnum for cirTickets
        /// </summary>
        [EnumMember(Value = "cirTickets")]
        CirTicketsEnum = 45,
        /// <summary>
        /// Enum CirTicketDetailsEnum for cirTicketDetails
        /// </summary>
        [EnumMember(Value = "cirTicketDetails")]
        CirTicketDetailsEnum = 46,
        /// <summary>
        /// Enum CirTicketNewEnum for cirTicketNew
        /// </summary>
        [EnumMember(Value = "cirTicketNew")]
        CirTicketNewEnum = 47,
        /// <summary>
        /// Enum GroupVatEnum for groupVat
        /// </summary>
        [EnumMember(Value = "groupVat")]
        GroupVatEnum = 48,
        /// <summary>
        /// Enum GroupVatEditEnum for groupVatEdit
        /// </summary>
        [EnumMember(Value = "groupVatEdit")]
        GroupVatEditEnum = 49,
        /// <summary>
        /// Enum SingleVatEnum for singleVat
        /// </summary>
        [EnumMember(Value = "singleVat")]
        SingleVatEnum = 50,
        /// <summary>
        /// Enum SingleVatEditEnum for singleVatEdit
        /// </summary>
        [EnumMember(Value = "singleVatEdit")]
        SingleVatEditEnum = 51,
        /// <summary>
        /// Enum IspSettingsEnum for ispSettings
        /// </summary>
        [EnumMember(Value = "ispSettings")]
        IspSettingsEnum = 52,
        /// <summary>
        /// Enum PublicPurchaseContractorInvoicesEnum for publicPurchaseContractorInvoices
        /// </summary>
        [EnumMember(Value = "publicPurchaseContractorInvoices")]
        PublicPurchaseContractorInvoicesEnum = 53,
        /// <summary>
        /// Enum IspConfigurationEnum for ispConfiguration
        /// </summary>
        [EnumMember(Value = "ispConfiguration")]
        IspConfigurationEnum = 54,
        /// <summary>
        /// Enum PublicPurchaseContractorInvoiceViewEnum for publicPurchaseContractorInvoiceView
        /// </summary>
        [EnumMember(Value = "publicPurchaseContractorInvoiceView")]
        PublicPurchaseContractorInvoiceViewEnum = 55,
        /// <summary>
        /// Enum FiscalizationEnum for fiscalization
        /// </summary>
        [EnumMember(Value = "fiscalization")]
        FiscalizationEnum = 56,
        /// <summary>
        /// Enum IncomingFiscalInvoicesEnum for incomingFiscalInvoices
        /// </summary>
        [EnumMember(Value = "incomingFiscalInvoices")]
        IncomingFiscalInvoicesEnum = 57,
        /// <summary>
        /// Enum OutgoingFiscalInvoicesEnum for outgoingFiscalInvoices
        /// </summary>
        [EnumMember(Value = "outgoingFiscalInvoices")]
        OutgoingFiscalInvoicesEnum = 58,
        /// <summary>
        /// Enum IncomingFiscalInvoicesViewEnum for incomingFiscalInvoicesView
        /// </summary>
        [EnumMember(Value = "incomingFiscalInvoicesView")]
        IncomingFiscalInvoicesViewEnum = 59,
        /// <summary>
        /// Enum OutgoingFiscalInvoicesViewEnum for outgoingFiscalInvoicesView
        /// </summary>
        [EnumMember(Value = "outgoingFiscalInvoicesView")]
        OutgoingFiscalInvoicesViewEnum = 60,
        /// <summary>
        /// Enum ReleaseNotesEnum for releaseNotes
        /// </summary>
        [EnumMember(Value = "releaseNotes")]
        ReleaseNotesEnum = 61,
        /// <summary>
        /// Enum CrossBorderDocumentsEnum for crossBorderDocuments
        /// </summary>
        [EnumMember(Value = "crossBorderDocuments")]
        CrossBorderDocumentsEnum = 62,
        /// <summary>
        /// Enum ImportCustomsDeclarationsEnum for importCustomsDeclarations
        /// </summary>
        [EnumMember(Value = "importCustomsDeclarations")]
        ImportCustomsDeclarationsEnum = 63,
        /// <summary>
        /// Enum ImportCustomsDeclarationsViewEnum for importCustomsDeclarationsView
        /// </summary>
        [EnumMember(Value = "importCustomsDeclarationsView")]
        ImportCustomsDeclarationsViewEnum = 64,
        /// <summary>
        /// Enum RecordsOfExportInvoicesEnum for recordsOfExportInvoices
        /// </summary>
        [EnumMember(Value = "recordsOfExportInvoices")]
        RecordsOfExportInvoicesEnum = 65,
        /// <summary>
        /// Enum RecordsOfExportInvoicesViewEnum for recordsOfExportInvoicesView
        /// </summary>
        [EnumMember(Value = "recordsOfExportInvoicesView")]
        RecordsOfExportInvoicesViewEnum = 66,
        /// <summary>
        /// Enum RecordsOfExportInvoicesEditEnum for recordsOfExportInvoicesEdit
        /// </summary>
        [EnumMember(Value = "recordsOfExportInvoicesEdit")]
        RecordsOfExportInvoicesEditEnum = 67,
        /// <summary>
        /// Enum SingleVatV2Enum for singleVatV2
        /// </summary>
        [EnumMember(Value = "singleVatV2")]
        SingleVatV2Enum = 68,
        /// <summary>
        /// Enum SingleVatViewV2Enum for singleVatViewV2
        /// </summary>
        [EnumMember(Value = "singleVatViewV2")]
        SingleVatViewV2Enum = 69,
        /// <summary>
        /// Enum GroupVatV2Enum for groupVatV2
        /// </summary>
        [EnumMember(Value = "groupVatV2")]
        GroupVatV2Enum = 70,
        /// <summary>
        /// Enum GroupVatViewV2Enum for groupVatViewV2
        /// </summary>
        [EnumMember(Value = "groupVatViewV2")]
        GroupVatViewV2Enum = 71,
        /// <summary>
        /// Enum VatRecordsUploadV2Enum for vatRecordsUploadV2
        /// </summary>
        [EnumMember(Value = "vatRecordsUploadV2")]
        VatRecordsUploadV2Enum = 72,
        /// <summary>
        /// Enum DispatchNoteEnum for dispatchNote
        /// </summary>
        [EnumMember(Value = "dispatchNote")]
        DispatchNoteEnum = 73,
        /// <summary>
        /// Enum DispatchNoteViewEnum for dispatchNoteView
        /// </summary>
        [EnumMember(Value = "dispatchNoteView")]
        DispatchNoteViewEnum = 74
    }
}
