/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using eFaktureModel.Api.Models.Company.Enums;

namespace eFaktureModel.Api.Models.Dto
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ContractApplicationDto : IEquatable<ContractApplicationDto>
    {
        /// <summary>
        /// Gets or Sets ContractApplicationId
        /// </summary>

        [DataMember(Name = "contractApplicationId")]
        public int? ContractApplicationId { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>

        [DataMember(Name = "companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationCode
        /// </summary>

        [DataMember(Name = "registrationCode")]
        public string RegistrationCode { get; set; }

        /// <summary>
        /// Gets or Sets VatRegistrationCode
        /// </summary>

        [DataMember(Name = "vatRegistrationCode")]
        public string VatRegistrationCode { get; set; }

        /// <summary>
        /// Gets or Sets ServiceId
        /// </summary>

        [DataMember(Name = "serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// Gets or Sets Addresses
        /// </summary>

        [DataMember(Name = "addresses")]
        public List<SspAddressDto> Addresses { get; set; }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>

        [DataMember(Name = "channel")]
        public int? Channel { get; set; }

        /// <summary>
        /// Gets or Sets ChannelAddress
        /// </summary>

        [DataMember(Name = "channelAddress")]
        public string ChannelAddress { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNotificationEmail
        /// </summary>

        [DataMember(Name = "invoiceNotificationEmail")]
        public string InvoiceNotificationEmail { get; set; }

        /// <summary>
        /// Gets or Sets ServiceProvider
        /// </summary>

        [DataMember(Name = "serviceProvider")]
        public string ServiceProvider { get; set; }

        /// <summary>
        /// Gets or Sets PaymentTerms
        /// </summary>

        [DataMember(Name = "paymentTerms")]
        public int? PaymentTerms { get; set; }

        /// <summary>
        /// Gets or Sets FineRatePerDay
        /// </summary>

        [DataMember(Name = "fineRatePerDay")]
        public double? FineRatePerDay { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNr
        /// </summary>

        [DataMember(Name = "referenceNr")]
        public string ReferenceNr { get; set; }

        /// <summary>
        /// Gets or Sets ContractDate
        /// </summary>

        [DataMember(Name = "contractDate")]
        public DateTime? ContractDate { get; set; }

        /// <summary>
        /// Gets or Sets CompanyLabel
        /// </summary>

        [DataMember(Name = "companyLabel")]
        public string CompanyLabel { get; set; }

        /// <summary>
        /// Gets or Sets CompanyEmail
        /// </summary>

        [DataMember(Name = "companyEmail")]
        public string CompanyEmail { get; set; }

        /// <summary>
        /// Gets or Sets CompanyPhone
        /// </summary>

        [DataMember(Name = "companyPhone")]
        public string CompanyPhone { get; set; }

        /// <summary>
        /// Gets or Sets ContactPersonName
        /// </summary>

        [DataMember(Name = "contactPersonName")]
        public string ContactPersonName { get; set; }

        /// <summary>
        /// Gets or Sets ContactPersonEmail
        /// </summary>

        [DataMember(Name = "contactPersonEmail")]
        public string ContactPersonEmail { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverCompanyId
        /// </summary>

        [DataMember(Name = "receiverCompanyId")]
        public int? ReceiverCompanyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContractApplicationDto {\n");
            sb.Append("  ContractApplicationId: ").Append(ContractApplicationId).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  RegistrationCode: ").Append(RegistrationCode).Append("\n");
            sb.Append("  VatRegistrationCode: ").Append(VatRegistrationCode).Append("\n");
            sb.Append("  ServiceId: ").Append(ServiceId).Append("\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  ChannelAddress: ").Append(ChannelAddress).Append("\n");
            sb.Append("  InvoiceNotificationEmail: ").Append(InvoiceNotificationEmail).Append("\n");
            sb.Append("  ServiceProvider: ").Append(ServiceProvider).Append("\n");
            sb.Append("  PaymentTerms: ").Append(PaymentTerms).Append("\n");
            sb.Append("  FineRatePerDay: ").Append(FineRatePerDay).Append("\n");
            sb.Append("  ReferenceNr: ").Append(ReferenceNr).Append("\n");
            sb.Append("  ContractDate: ").Append(ContractDate).Append("\n");
            sb.Append("  CompanyLabel: ").Append(CompanyLabel).Append("\n");
            sb.Append("  CompanyEmail: ").Append(CompanyEmail).Append("\n");
            sb.Append("  CompanyPhone: ").Append(CompanyPhone).Append("\n");
            sb.Append("  ContactPersonName: ").Append(ContactPersonName).Append("\n");
            sb.Append("  ContactPersonEmail: ").Append(ContactPersonEmail).Append("\n");
            sb.Append("  ReceiverCompanyId: ").Append(ReceiverCompanyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ContractApplicationDto)obj);
        }

        /// <summary>
        /// Returns true if ContractApplicationDto instances are equal
        /// </summary>
        /// <param name="other">Instance of ContractApplicationDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContractApplicationDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    ContractApplicationId == other.ContractApplicationId ||
                    ContractApplicationId != null &&
                    ContractApplicationId.Equals(other.ContractApplicationId)
                ) &&
                (
                    CompanyName == other.CompanyName ||
                    CompanyName != null &&
                    CompanyName.Equals(other.CompanyName)
                ) &&
                (
                    RegistrationCode == other.RegistrationCode ||
                    RegistrationCode != null &&
                    RegistrationCode.Equals(other.RegistrationCode)
                ) &&
                (
                    VatRegistrationCode == other.VatRegistrationCode ||
                    VatRegistrationCode != null &&
                    VatRegistrationCode.Equals(other.VatRegistrationCode)
                ) &&
                (
                    ServiceId == other.ServiceId ||
                    ServiceId != null &&
                    ServiceId.Equals(other.ServiceId)
                ) &&
                (
                    Addresses == other.Addresses ||
                    Addresses != null &&
                    Addresses.SequenceEqual(other.Addresses)
                ) &&
                (
                    Channel == other.Channel ||
                    Channel != null &&
                    Channel.Equals(other.Channel)
                ) &&
                (
                    ChannelAddress == other.ChannelAddress ||
                    ChannelAddress != null &&
                    ChannelAddress.Equals(other.ChannelAddress)
                ) &&
                (
                    InvoiceNotificationEmail == other.InvoiceNotificationEmail ||
                    InvoiceNotificationEmail != null &&
                    InvoiceNotificationEmail.Equals(other.InvoiceNotificationEmail)
                ) &&
                (
                    ServiceProvider == other.ServiceProvider ||
                    ServiceProvider != null &&
                    ServiceProvider.Equals(other.ServiceProvider)
                ) &&
                (
                    PaymentTerms == other.PaymentTerms ||
                    PaymentTerms != null &&
                    PaymentTerms.Equals(other.PaymentTerms)
                ) &&
                (
                    FineRatePerDay == other.FineRatePerDay ||
                    FineRatePerDay != null &&
                    FineRatePerDay.Equals(other.FineRatePerDay)
                ) &&
                (
                    ReferenceNr == other.ReferenceNr ||
                    ReferenceNr != null &&
                    ReferenceNr.Equals(other.ReferenceNr)
                ) &&
                (
                    ContractDate == other.ContractDate ||
                    ContractDate != null &&
                    ContractDate.Equals(other.ContractDate)
                ) &&
                (
                    CompanyLabel == other.CompanyLabel ||
                    CompanyLabel != null &&
                    CompanyLabel.Equals(other.CompanyLabel)
                ) &&
                (
                    CompanyEmail == other.CompanyEmail ||
                    CompanyEmail != null &&
                    CompanyEmail.Equals(other.CompanyEmail)
                ) &&
                (
                    CompanyPhone == other.CompanyPhone ||
                    CompanyPhone != null &&
                    CompanyPhone.Equals(other.CompanyPhone)
                ) &&
                (
                    ContactPersonName == other.ContactPersonName ||
                    ContactPersonName != null &&
                    ContactPersonName.Equals(other.ContactPersonName)
                ) &&
                (
                    ContactPersonEmail == other.ContactPersonEmail ||
                    ContactPersonEmail != null &&
                    ContactPersonEmail.Equals(other.ContactPersonEmail)
                ) &&
                (
                    ReceiverCompanyId == other.ReceiverCompanyId ||
                    ReceiverCompanyId != null &&
                    ReceiverCompanyId.Equals(other.ReceiverCompanyId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (ContractApplicationId != null)
                    hashCode = hashCode * 59 + ContractApplicationId.GetHashCode();
                if (CompanyName != null)
                    hashCode = hashCode * 59 + CompanyName.GetHashCode();
                if (RegistrationCode != null)
                    hashCode = hashCode * 59 + RegistrationCode.GetHashCode();
                if (VatRegistrationCode != null)
                    hashCode = hashCode * 59 + VatRegistrationCode.GetHashCode();
                if (ServiceId != null)
                    hashCode = hashCode * 59 + ServiceId.GetHashCode();
                if (Addresses != null)
                    hashCode = hashCode * 59 + Addresses.GetHashCode();
                if (Channel != null)
                    hashCode = hashCode * 59 + Channel.GetHashCode();
                if (ChannelAddress != null)
                    hashCode = hashCode * 59 + ChannelAddress.GetHashCode();
                if (InvoiceNotificationEmail != null)
                    hashCode = hashCode * 59 + InvoiceNotificationEmail.GetHashCode();
                if (ServiceProvider != null)
                    hashCode = hashCode * 59 + ServiceProvider.GetHashCode();
                if (PaymentTerms != null)
                    hashCode = hashCode * 59 + PaymentTerms.GetHashCode();
                if (FineRatePerDay != null)
                    hashCode = hashCode * 59 + FineRatePerDay.GetHashCode();
                if (ReferenceNr != null)
                    hashCode = hashCode * 59 + ReferenceNr.GetHashCode();
                if (ContractDate != null)
                    hashCode = hashCode * 59 + ContractDate.GetHashCode();
                if (CompanyLabel != null)
                    hashCode = hashCode * 59 + CompanyLabel.GetHashCode();
                if (CompanyEmail != null)
                    hashCode = hashCode * 59 + CompanyEmail.GetHashCode();
                if (CompanyPhone != null)
                    hashCode = hashCode * 59 + CompanyPhone.GetHashCode();
                if (ContactPersonName != null)
                    hashCode = hashCode * 59 + ContactPersonName.GetHashCode();
                if (ContactPersonEmail != null)
                    hashCode = hashCode * 59 + ContactPersonEmail.GetHashCode();
                if (ReceiverCompanyId != null)
                    hashCode = hashCode * 59 + ReceiverCompanyId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ContractApplicationDto left, ContractApplicationDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ContractApplicationDto left, ContractApplicationDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
