/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Dto
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DiscountDto : IEquatable<DiscountDto>
    {
        /// <summary>
        /// Gets or Sets Amount
        /// </summary>

        [DataMember(Name = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// Gets or Sets VatRate
        /// </summary>

        [DataMember(Name = "vatRate")]
        public double? VatRate { get; set; }

        /// <summary>
        /// Gets or Sets VatCategoryCode
        /// </summary>

        [DataMember(Name = "vatCategoryCode")]
        public string VatCategoryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DiscountDto {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  VatRate: ").Append(VatRate).Append("\n");
            sb.Append("  VatCategoryCode: ").Append(VatCategoryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DiscountDto)obj);
        }

        /// <summary>
        /// Returns true if DiscountDto instances are equal
        /// </summary>
        /// <param name="other">Instance of DiscountDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DiscountDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) &&
                (
                    VatRate == other.VatRate ||
                    VatRate != null &&
                    VatRate.Equals(other.VatRate)
                ) &&
                (
                    VatCategoryCode == other.VatCategoryCode ||
                    VatCategoryCode != null &&
                    VatCategoryCode.Equals(other.VatCategoryCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                if (VatRate != null)
                    hashCode = hashCode * 59 + VatRate.GetHashCode();
                if (VatCategoryCode != null)
                    hashCode = hashCode * 59 + VatCategoryCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(DiscountDto left, DiscountDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DiscountDto left, DiscountDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
