/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Enums.Customs
{

    /// <summary>
    /// Gets or Sets CustomsDeclarationStatus
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum CustomsDeclarationStatus
    {
        /// <summary>
        /// Enum ActiveEnum for Active
        /// </summary>
        [EnumMember(Value = "Active")]
        ActiveEnum = 0,
        /// <summary>
        /// Enum ModifiedEnum for Modified
        /// </summary>
        [EnumMember(Value = "Modified")]
        ModifiedEnum = 1,
        /// <summary>
        /// Enum BackVersionEnum for BackVersion
        /// </summary>
        [EnumMember(Value = "BackVersion")]
        BackVersionEnum = 2,
        /// <summary>
        /// Enum CancelledEnum for Cancelled
        /// </summary>
        [EnumMember(Value = "Cancelled")]
        CancelledEnum = 3
    }
}
