/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CancelInvoiceMessageDto : IEquatable<CancelInvoiceMessageDto>
    {
        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>

        [DataMember(Name = "invoiceId")]
        public long? InvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets CancelComments
        /// </summary>

        [DataMember(Name = "cancelComments")]
        public string CancelComments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancelInvoiceMessageDto {\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  CancelComments: ").Append(CancelComments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CancelInvoiceMessageDto)obj);
        }

        /// <summary>
        /// Returns true if CancelInvoiceMessageDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CancelInvoiceMessageDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancelInvoiceMessageDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    InvoiceId == other.InvoiceId ||
                    InvoiceId != null &&
                    InvoiceId.Equals(other.InvoiceId)
                ) &&
                (
                    CancelComments == other.CancelComments ||
                    CancelComments != null &&
                    CancelComments.Equals(other.CancelComments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (InvoiceId != null)
                    hashCode = hashCode * 59 + InvoiceId.GetHashCode();
                if (CancelComments != null)
                    hashCode = hashCode * 59 + CancelComments.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CancelInvoiceMessageDto left, CancelInvoiceMessageDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CancelInvoiceMessageDto left, CancelInvoiceMessageDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
