/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CirTicketHistoryDto : IEquatable<CirTicketHistoryDto>
    {
        /// <summary>
        /// Gets or Sets CirTicketId
        /// </summary>

        [DataMember(Name = "cirTicketId")]
        public long? CirTicketId { get; set; }

        /// <summary>
        /// Gets or Sets CirTicketChanges
        /// </summary>

        [DataMember(Name = "cirTicketChanges")]
        public List<CirTicketChangeDto> CirTicketChanges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CirTicketHistoryDto {\n");
            sb.Append("  CirTicketId: ").Append(CirTicketId).Append("\n");
            sb.Append("  CirTicketChanges: ").Append(CirTicketChanges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CirTicketHistoryDto)obj);
        }

        /// <summary>
        /// Returns true if CirTicketHistoryDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CirTicketHistoryDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CirTicketHistoryDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    CirTicketId == other.CirTicketId ||
                    CirTicketId != null &&
                    CirTicketId.Equals(other.CirTicketId)
                ) &&
                (
                    CirTicketChanges == other.CirTicketChanges ||
                    CirTicketChanges != null &&
                    CirTicketChanges.SequenceEqual(other.CirTicketChanges)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (CirTicketId != null)
                    hashCode = hashCode * 59 + CirTicketId.GetHashCode();
                if (CirTicketChanges != null)
                    hashCode = hashCode * 59 + CirTicketChanges.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CirTicketHistoryDto left, CirTicketHistoryDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CirTicketHistoryDto left, CirTicketHistoryDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
