/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CirTicketDto : IEquatable<CirTicketDto>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets CirId
        /// </summary>

        [DataMember(Name = "cirId")]
        public string CirId { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>

        [DataMember(Name = "category")]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>

        [DataMember(Name = "data")]
        public string Data { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>

        [DataMember(Name = "organizationId")]
        public int? OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets UserComment
        /// </summary>

        [DataMember(Name = "userComment")]
        public string UserComment { get; set; }

        /// <summary>
        /// Gets or Sets OperatorComment
        /// </summary>

        [DataMember(Name = "operatorComment")]
        public object OperatorComment { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>

        [DataMember(Name = "status")]
        public CirTicketStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets CreationDate
        /// </summary>

        [DataMember(Name = "creationDate")]
        public DateTime? CreationDate { get; set; }

        /// <summary>
        /// Gets or Sets ClosingDate
        /// </summary>

        [DataMember(Name = "closingDate")]
        public DateTime? ClosingDate { get; set; }

        /// <summary>
        /// Gets or Sets CategoryCyr
        /// </summary>

        [DataMember(Name = "categoryCyr")]
        public string CategoryCyr { get; set; }

        /// <summary>
        /// Gets or Sets CompanyNumber
        /// </summary>

        [DataMember(Name = "companyNumber")]
        public string CompanyNumber { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationName
        /// </summary>

        [DataMember(Name = "organizationName")]
        public string OrganizationName { get; set; }

        /// <summary>
        /// Gets or Sets ResourceId
        /// </summary>

        [DataMember(Name = "resourceId")]
        public CirResourceType ResourceId { get; set; }

        /// <summary>
        /// Gets or Sets CirTicketHistory
        /// </summary>

        [DataMember(Name = "cirTicketHistory")]
        public CirTicketHistoryDto CirTicketHistory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CirTicketDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CirId: ").Append(CirId).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  UserComment: ").Append(UserComment).Append("\n");
            sb.Append("  OperatorComment: ").Append(OperatorComment).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreationDate: ").Append(CreationDate).Append("\n");
            sb.Append("  ClosingDate: ").Append(ClosingDate).Append("\n");
            sb.Append("  CategoryCyr: ").Append(CategoryCyr).Append("\n");
            sb.Append("  CompanyNumber: ").Append(CompanyNumber).Append("\n");
            sb.Append("  OrganizationName: ").Append(OrganizationName).Append("\n");
            sb.Append("  ResourceId: ").Append(ResourceId).Append("\n");
            sb.Append("  CirTicketHistory: ").Append(CirTicketHistory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CirTicketDto)obj);
        }

        /// <summary>
        /// Returns true if CirTicketDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CirTicketDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CirTicketDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    CirId == other.CirId ||
                    CirId != null &&
                    CirId.Equals(other.CirId)
                ) &&
                (
                    Category == other.Category ||
                    Category != null &&
                    Category.Equals(other.Category)
                ) &&
                (
                    Data == other.Data ||
                    Data != null &&
                    Data.Equals(other.Data)
                ) &&
                (
                    OrganizationId == other.OrganizationId ||
                    OrganizationId != null &&
                    OrganizationId.Equals(other.OrganizationId)
                ) &&
                (
                    UserComment == other.UserComment ||
                    UserComment != null &&
                    UserComment.Equals(other.UserComment)
                ) &&
                (
                    OperatorComment == other.OperatorComment ||
                    OperatorComment != null &&
                    OperatorComment.Equals(other.OperatorComment)
                ) &&
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) &&
                (
                    CreationDate == other.CreationDate ||
                    CreationDate != null &&
                    CreationDate.Equals(other.CreationDate)
                ) &&
                (
                    ClosingDate == other.ClosingDate ||
                    ClosingDate != null &&
                    ClosingDate.Equals(other.ClosingDate)
                ) &&
                (
                    CategoryCyr == other.CategoryCyr ||
                    CategoryCyr != null &&
                    CategoryCyr.Equals(other.CategoryCyr)
                ) &&
                (
                    CompanyNumber == other.CompanyNumber ||
                    CompanyNumber != null &&
                    CompanyNumber.Equals(other.CompanyNumber)
                ) &&
                (
                    OrganizationName == other.OrganizationName ||
                    OrganizationName != null &&
                    OrganizationName.Equals(other.OrganizationName)
                ) &&
                (
                    ResourceId == other.ResourceId ||
                    ResourceId != null &&
                    ResourceId.Equals(other.ResourceId)
                ) &&
                (
                    CirTicketHistory == other.CirTicketHistory ||
                    CirTicketHistory != null &&
                    CirTicketHistory.Equals(other.CirTicketHistory)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (CirId != null)
                    hashCode = hashCode * 59 + CirId.GetHashCode();
                if (Category != null)
                    hashCode = hashCode * 59 + Category.GetHashCode();
                if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                if (OrganizationId != null)
                    hashCode = hashCode * 59 + OrganizationId.GetHashCode();
                if (UserComment != null)
                    hashCode = hashCode * 59 + UserComment.GetHashCode();
                if (OperatorComment != null)
                    hashCode = hashCode * 59 + OperatorComment.GetHashCode();
                if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                if (CreationDate != null)
                    hashCode = hashCode * 59 + CreationDate.GetHashCode();
                if (ClosingDate != null)
                    hashCode = hashCode * 59 + ClosingDate.GetHashCode();
                if (CategoryCyr != null)
                    hashCode = hashCode * 59 + CategoryCyr.GetHashCode();
                if (CompanyNumber != null)
                    hashCode = hashCode * 59 + CompanyNumber.GetHashCode();
                if (OrganizationName != null)
                    hashCode = hashCode * 59 + OrganizationName.GetHashCode();
                if (ResourceId != null)
                    hashCode = hashCode * 59 + ResourceId.GetHashCode();
                if (CirTicketHistory != null)
                    hashCode = hashCode * 59 + CirTicketHistory.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CirTicketDto left, CirTicketDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CirTicketDto left, CirTicketDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
