/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{

    /// <summary>
    /// Gets or Sets CirTicketSortEnum
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum CirTicketSortEnum
    {
        /// <summary>
        /// Enum CirIdEnum for CirId
        /// </summary>
        [EnumMember(Value = "CirId")]
        CirIdEnum = 0,
        /// <summary>
        /// Enum CompanyNumberEnum for CompanyNumber
        /// </summary>
        [EnumMember(Value = "CompanyNumber")]
        CompanyNumberEnum = 1,
        /// <summary>
        /// Enum OrganizationNameEnum for OrganizationName
        /// </summary>
        [EnumMember(Value = "OrganizationName")]
        OrganizationNameEnum = 2,
        /// <summary>
        /// Enum DataEnum for Data
        /// </summary>
        [EnumMember(Value = "Data")]
        DataEnum = 3,
        /// <summary>
        /// Enum CreationDateEnum for CreationDate
        /// </summary>
        [EnumMember(Value = "CreationDate")]
        CreationDateEnum = 4,
        /// <summary>
        /// Enum ClosingDateEnum for ClosingDate
        /// </summary>
        [EnumMember(Value = "ClosingDate")]
        ClosingDateEnum = 5
    }
}
