/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CompanyAccountIdentificationDto : IEquatable<CompanyAccountIdentificationDto>
    {
        /// <summary>
        /// Gets or Sets RegistrationNumber
        /// </summary>

        [DataMember(Name = "registrationNumber")]
        public string RegistrationNumber { get; set; }

        /// <summary>
        /// Gets or Sets Jbkjs
        /// </summary>

        [DataMember(Name = "jbkjs")]
        public string Jbkjs { get; set; }

        /// <summary>
        /// Gets or Sets VatNumber
        /// </summary>

        [DataMember(Name = "vatNumber")]
        public string VatNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompanyAccountIdentificationDto {\n");
            sb.Append("  RegistrationNumber: ").Append(RegistrationNumber).Append("\n");
            sb.Append("  Jbkjs: ").Append(Jbkjs).Append("\n");
            sb.Append("  VatNumber: ").Append(VatNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CompanyAccountIdentificationDto)obj);
        }

        /// <summary>
        /// Returns true if CompanyAccountIdentificationDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CompanyAccountIdentificationDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompanyAccountIdentificationDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    RegistrationNumber == other.RegistrationNumber ||
                    RegistrationNumber != null &&
                    RegistrationNumber.Equals(other.RegistrationNumber)
                ) &&
                (
                    Jbkjs == other.Jbkjs ||
                    Jbkjs != null &&
                    Jbkjs.Equals(other.Jbkjs)
                ) &&
                (
                    VatNumber == other.VatNumber ||
                    VatNumber != null &&
                    VatNumber.Equals(other.VatNumber)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (RegistrationNumber != null)
                    hashCode = hashCode * 59 + RegistrationNumber.GetHashCode();
                if (Jbkjs != null)
                    hashCode = hashCode * 59 + Jbkjs.GetHashCode();
                if (VatNumber != null)
                    hashCode = hashCode * 59 + VatNumber.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CompanyAccountIdentificationDto left, CompanyAccountIdentificationDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CompanyAccountIdentificationDto left, CompanyAccountIdentificationDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
