/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CompanyUpdateNotificationEndpointDto : IEquatable<CompanyUpdateNotificationEndpointDto>
    {
        /// <summary>
        /// Gets or Sets OutgoingInvoicesEndpoint
        /// </summary>

        [DataMember(Name = "outgoingInvoicesEndpoint")]
        public string OutgoingInvoicesEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets IncomingInvoicesEndpoint
        /// </summary>

        [DataMember(Name = "incomingInvoicesEndpoint")]
        public string IncomingInvoicesEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets IncomingInvoicesPPCEndpoint
        /// </summary>

        [DataMember(Name = "incomingInvoicesPPCEndpoint")]
        public string IncomingInvoicesPPCEndpoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompanyUpdateNotificationEndpointDto {\n");
            sb.Append("  OutgoingInvoicesEndpoint: ").Append(OutgoingInvoicesEndpoint).Append("\n");
            sb.Append("  IncomingInvoicesEndpoint: ").Append(IncomingInvoicesEndpoint).Append("\n");
            sb.Append("  IncomingInvoicesPPCEndpoint: ").Append(IncomingInvoicesPPCEndpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CompanyUpdateNotificationEndpointDto)obj);
        }

        /// <summary>
        /// Returns true if CompanyUpdateNotificationEndpointDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CompanyUpdateNotificationEndpointDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompanyUpdateNotificationEndpointDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    OutgoingInvoicesEndpoint == other.OutgoingInvoicesEndpoint ||
                    OutgoingInvoicesEndpoint != null &&
                    OutgoingInvoicesEndpoint.Equals(other.OutgoingInvoicesEndpoint)
                ) &&
                (
                    IncomingInvoicesEndpoint == other.IncomingInvoicesEndpoint ||
                    IncomingInvoicesEndpoint != null &&
                    IncomingInvoicesEndpoint.Equals(other.IncomingInvoicesEndpoint)
                ) &&
                (
                    IncomingInvoicesPPCEndpoint == other.IncomingInvoicesPPCEndpoint ||
                    IncomingInvoicesPPCEndpoint != null &&
                    IncomingInvoicesPPCEndpoint.Equals(other.IncomingInvoicesPPCEndpoint)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (OutgoingInvoicesEndpoint != null)
                    hashCode = hashCode * 59 + OutgoingInvoicesEndpoint.GetHashCode();
                if (IncomingInvoicesEndpoint != null)
                    hashCode = hashCode * 59 + IncomingInvoicesEndpoint.GetHashCode();
                if (IncomingInvoicesPPCEndpoint != null)
                    hashCode = hashCode * 59 + IncomingInvoicesPPCEndpoint.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CompanyUpdateNotificationEndpointDto left, CompanyUpdateNotificationEndpointDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CompanyUpdateNotificationEndpointDto left, CompanyUpdateNotificationEndpointDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
