/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ExemptionReasonByVatCategoryDto : IEquatable<ExemptionReasonByVatCategoryDto>
    {
        /// <summary>
        /// Gets or Sets VatCategoryCode
        /// </summary>

        [DataMember(Name = "vatCategoryCode")]
        public string VatCategoryCode { get; set; }

        /// <summary>
        /// Gets or Sets ReasonCode
        /// </summary>

        [DataMember(Name = "reasonCode")]
        public string ReasonCode { get; set; }

        /// <summary>
        /// Gets or Sets ExemptionDecisionNumber
        /// </summary>

        [DataMember(Name = "exemptionDecisionNumber")]
        public string ExemptionDecisionNumber { get; set; }

        /// <summary>
        /// Gets or Sets FeeItemsValueWithoutVat
        /// </summary>

        [DataMember(Name = "feeItemsValueWithoutVat")]
        public double? FeeItemsValueWithoutVat { get; set; }

        /// <summary>
        /// Gets or Sets DiscountFeeWithoutVat
        /// </summary>

        [DataMember(Name = "discountFeeWithoutVat")]
        public double? DiscountFeeWithoutVat { get; set; }

        /// <summary>
        /// Gets or Sets FeeWithoutVat
        /// </summary>

        [DataMember(Name = "feeWithoutVat")]
        public double? FeeWithoutVat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExemptionReasonByVatCategoryDto {\n");
            sb.Append("  VatCategoryCode: ").Append(VatCategoryCode).Append("\n");
            sb.Append("  ReasonCode: ").Append(ReasonCode).Append("\n");
            sb.Append("  ExemptionDecisionNumber: ").Append(ExemptionDecisionNumber).Append("\n");
            sb.Append("  FeeItemsValueWithoutVat: ").Append(FeeItemsValueWithoutVat).Append("\n");
            sb.Append("  DiscountFeeWithoutVat: ").Append(DiscountFeeWithoutVat).Append("\n");
            sb.Append("  FeeWithoutVat: ").Append(FeeWithoutVat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ExemptionReasonByVatCategoryDto)obj);
        }

        /// <summary>
        /// Returns true if ExemptionReasonByVatCategoryDto instances are equal
        /// </summary>
        /// <param name="other">Instance of ExemptionReasonByVatCategoryDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExemptionReasonByVatCategoryDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VatCategoryCode == other.VatCategoryCode ||
                    VatCategoryCode != null &&
                    VatCategoryCode.Equals(other.VatCategoryCode)
                ) &&
                (
                    ReasonCode == other.ReasonCode ||
                    ReasonCode != null &&
                    ReasonCode.Equals(other.ReasonCode)
                ) &&
                (
                    ExemptionDecisionNumber == other.ExemptionDecisionNumber ||
                    ExemptionDecisionNumber != null &&
                    ExemptionDecisionNumber.Equals(other.ExemptionDecisionNumber)
                ) &&
                (
                    FeeItemsValueWithoutVat == other.FeeItemsValueWithoutVat ||
                    FeeItemsValueWithoutVat != null &&
                    FeeItemsValueWithoutVat.Equals(other.FeeItemsValueWithoutVat)
                ) &&
                (
                    DiscountFeeWithoutVat == other.DiscountFeeWithoutVat ||
                    DiscountFeeWithoutVat != null &&
                    DiscountFeeWithoutVat.Equals(other.DiscountFeeWithoutVat)
                ) &&
                (
                    FeeWithoutVat == other.FeeWithoutVat ||
                    FeeWithoutVat != null &&
                    FeeWithoutVat.Equals(other.FeeWithoutVat)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (VatCategoryCode != null)
                    hashCode = hashCode * 59 + VatCategoryCode.GetHashCode();
                if (ReasonCode != null)
                    hashCode = hashCode * 59 + ReasonCode.GetHashCode();
                if (ExemptionDecisionNumber != null)
                    hashCode = hashCode * 59 + ExemptionDecisionNumber.GetHashCode();
                if (FeeItemsValueWithoutVat != null)
                    hashCode = hashCode * 59 + FeeItemsValueWithoutVat.GetHashCode();
                if (DiscountFeeWithoutVat != null)
                    hashCode = hashCode * 59 + DiscountFeeWithoutVat.GetHashCode();
                if (FeeWithoutVat != null)
                    hashCode = hashCode * 59 + FeeWithoutVat.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ExemptionReasonByVatCategoryDto left, ExemptionReasonByVatCategoryDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExemptionReasonByVatCategoryDto left, ExemptionReasonByVatCategoryDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
