/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{

    /// <summary>
    /// Gets or Sets InternalInvoiceOption
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum InternalInvoiceOption
    {
        /// <summary>
        /// Enum TurnoverEnum for Turnover
        /// </summary>
        [EnumMember(Value = "Turnover")]
        TurnoverEnum = 0,
        /// <summary>
        /// Enum PrepaymentEnum for Prepayment
        /// </summary>
        [EnumMember(Value = "Prepayment")]
        PrepaymentEnum = 1
    }
}
