/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InvoiceTotalVatPerRateCalculationDomesticDto : IEquatable<InvoiceTotalVatPerRateCalculationDomesticDto>
    {
        /// <summary>
        /// Gets or Sets VatRate
        /// </summary>

        [DataMember(Name = "vatRate")]
        public double? VatRate { get; set; }

        /// <summary>
        /// Gets or Sets BaseSumForPaymentVatRate
        /// </summary>

        [DataMember(Name = "baseSumForPaymentVatRate")]
        public double? BaseSumForPaymentVatRate { get; set; }

        /// <summary>
        /// Gets or Sets VatCategory
        /// </summary>

        [DataMember(Name = "vatCategory")]
        public string VatCategory { get; set; }

        /// <summary>
        /// Gets or Sets VatPaymentPerRate
        /// </summary>

        [DataMember(Name = "vatPaymentPerRate")]
        public double? VatPaymentPerRate { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvoiceTotalVatPerRateCalculationDomesticDto {\n");
            sb.Append("  VatRate: ").Append(VatRate).Append("\n");
            sb.Append("  BaseSumForPaymentVatRate: ").Append(BaseSumForPaymentVatRate).Append("\n");
            sb.Append("  VatCategory: ").Append(VatCategory).Append("\n");
            sb.Append("  VatPaymentPerRate: ").Append(VatPaymentPerRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InvoiceTotalVatPerRateCalculationDomesticDto)obj);
        }

        /// <summary>
        /// Returns true if InvoiceTotalVatPerRateCalculationDomesticDto instances are equal
        /// </summary>
        /// <param name="other">Instance of InvoiceTotalVatPerRateCalculationDomesticDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvoiceTotalVatPerRateCalculationDomesticDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VatRate == other.VatRate ||
                    VatRate != null &&
                    VatRate.Equals(other.VatRate)
                ) &&
                (
                    BaseSumForPaymentVatRate == other.BaseSumForPaymentVatRate ||
                    BaseSumForPaymentVatRate != null &&
                    BaseSumForPaymentVatRate.Equals(other.BaseSumForPaymentVatRate)
                ) &&
                (
                    VatCategory == other.VatCategory ||
                    VatCategory != null &&
                    VatCategory.Equals(other.VatCategory)
                ) &&
                (
                    VatPaymentPerRate == other.VatPaymentPerRate ||
                    VatPaymentPerRate != null &&
                    VatPaymentPerRate.Equals(other.VatPaymentPerRate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (VatRate != null)
                    hashCode = hashCode * 59 + VatRate.GetHashCode();
                if (BaseSumForPaymentVatRate != null)
                    hashCode = hashCode * 59 + BaseSumForPaymentVatRate.GetHashCode();
                if (VatCategory != null)
                    hashCode = hashCode * 59 + VatCategory.GetHashCode();
                if (VatPaymentPerRate != null)
                    hashCode = hashCode * 59 + VatPaymentPerRate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(InvoiceTotalVatPerRateCalculationDomesticDto left, InvoiceTotalVatPerRateCalculationDomesticDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InvoiceTotalVatPerRateCalculationDomesticDto left, InvoiceTotalVatPerRateCalculationDomesticDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
