/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PurchaseFileDto : IEquatable<PurchaseFileDto>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>

        [DataMember(Name = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Extension
        /// </summary>

        [DataMember(Name = "extension")]
        public string Extension { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>

        [DataMember(Name = "invoiceId")]
        public long? InvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets MainPdf
        /// </summary>

        [DataMember(Name = "mainPdf")]
        public bool? MainPdf { get; set; }

        /// <summary>
        /// Gets or Sets MainXml
        /// </summary>

        [DataMember(Name = "mainXml")]
        public bool? MainXml { get; set; }

        /// <summary>
        /// Gets or Sets IsFitekInZip
        /// </summary>

        [DataMember(Name = "isFitekInZip")]
        public bool? IsFitekInZip { get; set; }

        /// <summary>
        /// Gets or Sets IsLink
        /// </summary>

        [DataMember(Name = "isLink")]
        public bool? IsLink { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>

        [DataMember(Name = "link")]
        public string Link { get; set; }

        /// <summary>
        /// Gets or Sets ExtendedPdf
        /// </summary>

        [DataMember(Name = "extendedPdf")]
        public bool? ExtendedPdf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseFileDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Extension: ").Append(Extension).Append("\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  MainPdf: ").Append(MainPdf).Append("\n");
            sb.Append("  MainXml: ").Append(MainXml).Append("\n");
            sb.Append("  IsFitekInZip: ").Append(IsFitekInZip).Append("\n");
            sb.Append("  IsLink: ").Append(IsLink).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  ExtendedPdf: ").Append(ExtendedPdf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PurchaseFileDto)obj);
        }

        /// <summary>
        /// Returns true if PurchaseFileDto instances are equal
        /// </summary>
        /// <param name="other">Instance of PurchaseFileDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseFileDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    Extension == other.Extension ||
                    Extension != null &&
                    Extension.Equals(other.Extension)
                ) &&
                (
                    InvoiceId == other.InvoiceId ||
                    InvoiceId != null &&
                    InvoiceId.Equals(other.InvoiceId)
                ) &&
                (
                    MainPdf == other.MainPdf ||
                    MainPdf != null &&
                    MainPdf.Equals(other.MainPdf)
                ) &&
                (
                    MainXml == other.MainXml ||
                    MainXml != null &&
                    MainXml.Equals(other.MainXml)
                ) &&
                (
                    IsFitekInZip == other.IsFitekInZip ||
                    IsFitekInZip != null &&
                    IsFitekInZip.Equals(other.IsFitekInZip)
                ) &&
                (
                    IsLink == other.IsLink ||
                    IsLink != null &&
                    IsLink.Equals(other.IsLink)
                ) &&
                (
                    Link == other.Link ||
                    Link != null &&
                    Link.Equals(other.Link)
                ) &&
                (
                    ExtendedPdf == other.ExtendedPdf ||
                    ExtendedPdf != null &&
                    ExtendedPdf.Equals(other.ExtendedPdf)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Extension != null)
                    hashCode = hashCode * 59 + Extension.GetHashCode();
                if (InvoiceId != null)
                    hashCode = hashCode * 59 + InvoiceId.GetHashCode();
                if (MainPdf != null)
                    hashCode = hashCode * 59 + MainPdf.GetHashCode();
                if (MainXml != null)
                    hashCode = hashCode * 59 + MainXml.GetHashCode();
                if (IsFitekInZip != null)
                    hashCode = hashCode * 59 + IsFitekInZip.GetHashCode();
                if (IsLink != null)
                    hashCode = hashCode * 59 + IsLink.GetHashCode();
                if (Link != null)
                    hashCode = hashCode * 59 + Link.GetHashCode();
                if (ExtendedPdf != null)
                    hashCode = hashCode * 59 + ExtendedPdf.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PurchaseFileDto left, PurchaseFileDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PurchaseFileDto left, PurchaseFileDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
