/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SearchParameter : IEquatable<SearchParameter>
    {
        /// <summary>
        /// Gets or Sets SortItems
        /// </summary>

        [DataMember(Name = "sortItems")]
        public List<SortItem> SortItems { get; set; }

        /// <summary>
        /// Gets or Sets PagingOptions
        /// </summary>

        [DataMember(Name = "pagingOptions")]
        public PagingOptions PagingOptions { get; set; }

        /// <summary>
        /// Gets or Sets Restrictions
        /// </summary>

        [DataMember(Name = "restrictions")]
        public List<RestrictionItem> Restrictions { get; set; }

        /// <summary>
        /// Gets or Sets LocalizationType
        /// </summary>

        [DataMember(Name = "localizationType")]
        public string LocalizationType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SearchParameter {\n");
            sb.Append("  SortItems: ").Append(SortItems).Append("\n");
            sb.Append("  PagingOptions: ").Append(PagingOptions).Append("\n");
            sb.Append("  Restrictions: ").Append(Restrictions).Append("\n");
            sb.Append("  LocalizationType: ").Append(LocalizationType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SearchParameter)obj);
        }

        /// <summary>
        /// Returns true if SearchParameter instances are equal
        /// </summary>
        /// <param name="other">Instance of SearchParameter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SearchParameter other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    SortItems == other.SortItems ||
                    SortItems != null &&
                    SortItems.SequenceEqual(other.SortItems)
                ) &&
                (
                    PagingOptions == other.PagingOptions ||
                    PagingOptions != null &&
                    PagingOptions.Equals(other.PagingOptions)
                ) &&
                (
                    Restrictions == other.Restrictions ||
                    Restrictions != null &&
                    Restrictions.SequenceEqual(other.Restrictions)
                ) &&
                (
                    LocalizationType == other.LocalizationType ||
                    LocalizationType != null &&
                    LocalizationType.Equals(other.LocalizationType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (SortItems != null)
                    hashCode = hashCode * 59 + SortItems.GetHashCode();
                if (PagingOptions != null)
                    hashCode = hashCode * 59 + PagingOptions.GetHashCode();
                if (Restrictions != null)
                    hashCode = hashCode * 59 + Restrictions.GetHashCode();
                if (LocalizationType != null)
                    hashCode = hashCode * 59 + LocalizationType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SearchParameter left, SearchParameter right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SearchParameter left, SearchParameter right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
