/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SearchInvoiceResultDto : IEquatable<SearchInvoiceResultDto>
    {
        /// <summary>
        /// Gets or Sets Total
        /// </summary>

        [DataMember(Name = "total")]
        public int? Total { get; set; }

        /// <summary>
        /// Gets or Sets TotalSum
        /// </summary>

        [DataMember(Name = "totalSum")]
        public double? TotalSum { get; set; }

        /// <summary>
        /// Gets or Sets Invoices
        /// </summary>

        [DataMember(Name = "invoices")]
        public List<SmallInvoiceDto> Invoices { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>

        [DataMember(Name = "requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SearchInvoiceResultDto {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  TotalSum: ").Append(TotalSum).Append("\n");
            sb.Append("  Invoices: ").Append(Invoices).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SearchInvoiceResultDto)obj);
        }

        /// <summary>
        /// Returns true if SearchInvoiceResultDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SearchInvoiceResultDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SearchInvoiceResultDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Total == other.Total ||
                    Total != null &&
                    Total.Equals(other.Total)
                ) &&
                (
                    TotalSum == other.TotalSum ||
                    TotalSum != null &&
                    TotalSum.Equals(other.TotalSum)
                ) &&
                (
                    Invoices == other.Invoices ||
                    Invoices != null &&
                    Invoices.SequenceEqual(other.Invoices)
                ) &&
                (
                    RequestId == other.RequestId ||
                    RequestId != null &&
                    RequestId.Equals(other.RequestId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Total != null)
                    hashCode = hashCode * 59 + Total.GetHashCode();
                if (TotalSum != null)
                    hashCode = hashCode * 59 + TotalSum.GetHashCode();
                if (Invoices != null)
                    hashCode = hashCode * 59 + Invoices.GetHashCode();
                if (RequestId != null)
                    hashCode = hashCode * 59 + RequestId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SearchInvoiceResultDto left, SearchInvoiceResultDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SearchInvoiceResultDto left, SearchInvoiceResultDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
