/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{

    /// <summary>
    /// Gets or Sets VatDeductionRight
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum VatDeductionRight
    {
        /// <summary>
        /// Enum NoneEnum for None
        /// </summary>
        [EnumMember(Value = "None")]
        NoneEnum = 0,
        /// <summary>
        /// Enum PartiallyEnum for Partially
        /// </summary>
        [EnumMember(Value = "Partially")]
        PartiallyEnum = 1,
        /// <summary>
        /// Enum FullyEnum for Fully
        /// </summary>
        [EnumMember(Value = "Fully")]
        FullyEnum = 2
    }
}
