/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VatReverseChargeDto : IEquatable<VatReverseChargeDto>
    {
        /// <summary>
        /// Gets or Sets PurchaseInvoiceId
        /// </summary>

        [DataMember(Name = "purchaseInvoiceId")]
        public long? PurchaseInvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets VatAmount
        /// </summary>

        [DataMember(Name = "vatAmount")]
        public double? VatAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VatReverseChargeDto {\n");
            sb.Append("  PurchaseInvoiceId: ").Append(PurchaseInvoiceId).Append("\n");
            sb.Append("  VatAmount: ").Append(VatAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VatReverseChargeDto)obj);
        }

        /// <summary>
        /// Returns true if VatReverseChargeDto instances are equal
        /// </summary>
        /// <param name="other">Instance of VatReverseChargeDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VatReverseChargeDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PurchaseInvoiceId == other.PurchaseInvoiceId ||
                    PurchaseInvoiceId != null &&
                    PurchaseInvoiceId.Equals(other.PurchaseInvoiceId)
                ) &&
                (
                    VatAmount == other.VatAmount ||
                    VatAmount != null &&
                    VatAmount.Equals(other.VatAmount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (PurchaseInvoiceId != null)
                    hashCode = hashCode * 59 + PurchaseInvoiceId.GetHashCode();
                if (VatAmount != null)
                    hashCode = hashCode * 59 + VatAmount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(VatReverseChargeDto left, VatReverseChargeDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VatReverseChargeDto left, VatReverseChargeDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
