/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models
{

    /// <summary>
    /// Gets or Sets VatRecordVersion
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum VatRecordVersion
    {
        /// <summary>
        /// Enum FirstEnum for First
        /// </summary>
        [EnumMember(Value = "First")]
        FirstEnum = 0,
        /// <summary>
        /// Enum SecondEnum for Second
        /// </summary>
        [EnumMember(Value = "Second")]
        SecondEnum = 1,
        /// <summary>
        /// Enum ThirdEnum for Third
        /// </summary>
        [EnumMember(Value = "Third")]
        ThirdEnum = 2
    }
}
