/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using eFaktureModel.Api.Models.Enums;

namespace eFaktureModel.Api.Models.Search
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SortItem : IEquatable<SortItem>
    {
        /// <summary>
        /// Gets or Sets SortColumn
        /// </summary>

        [DataMember(Name = "sortColumn")]
        public ESortColumn SortColumn { get; set; }

        /// <summary>
        /// Gets or Sets SortDirection
        /// </summary>

        [DataMember(Name = "sortDirection")]
        public SortDirection SortDirection { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SortItem {\n");
            sb.Append("  SortColumn: ").Append(SortColumn).Append("\n");
            sb.Append("  SortDirection: ").Append(SortDirection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SortItem)obj);
        }

        /// <summary>
        /// Returns true if SortItem instances are equal
        /// </summary>
        /// <param name="other">Instance of SortItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SortItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    SortColumn == other.SortColumn ||
                    SortColumn != null &&
                    SortColumn.Equals(other.SortColumn)
                ) &&
                (
                    SortDirection == other.SortDirection ||
                    SortDirection != null &&
                    SortDirection.Equals(other.SortDirection)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (SortColumn != null)
                    hashCode = hashCode * 59 + SortColumn.GetHashCode();
                if (SortDirection != null)
                    hashCode = hashCode * 59 + SortDirection.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SortItem left, SortItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SortItem left, SortItem right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
