/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Company
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MiniCompanyDto : IEquatable<MiniCompanyDto>
    {
        /// <summary>
        /// Gets or Sets BugetCompanyNumber
        /// </summary>

        [DataMember(Name = "bugetCompanyNumber")]
        public string BugetCompanyNumber { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationCode
        /// </summary>

        [DataMember(Name = "registrationCode")]
        public string RegistrationCode { get; set; }

        /// <summary>
        /// Gets or Sets VatRegistrationCode
        /// </summary>

        [DataMember(Name = "vatRegistrationCode")]
        public string VatRegistrationCode { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>

        [DataMember(Name = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationDate
        /// </summary>

        [DataMember(Name = "registrationDate")]
        public DateTime? RegistrationDate { get; set; }

        /// <summary>
        /// Gets or Sets DeletionDate
        /// </summary>

        [DataMember(Name = "deletionDate")]
        public DateTime? DeletionDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MiniCompanyDto {\n");
            sb.Append("  BugetCompanyNumber: ").Append(BugetCompanyNumber).Append("\n");
            sb.Append("  RegistrationCode: ").Append(RegistrationCode).Append("\n");
            sb.Append("  VatRegistrationCode: ").Append(VatRegistrationCode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RegistrationDate: ").Append(RegistrationDate).Append("\n");
            sb.Append("  DeletionDate: ").Append(DeletionDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MiniCompanyDto)obj);
        }

        /// <summary>
        /// Returns true if MiniCompanyDto instances are equal
        /// </summary>
        /// <param name="other">Instance of MiniCompanyDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MiniCompanyDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    BugetCompanyNumber == other.BugetCompanyNumber ||
                    BugetCompanyNumber != null &&
                    BugetCompanyNumber.Equals(other.BugetCompanyNumber)
                ) &&
                (
                    RegistrationCode == other.RegistrationCode ||
                    RegistrationCode != null &&
                    RegistrationCode.Equals(other.RegistrationCode)
                ) &&
                (
                    VatRegistrationCode == other.VatRegistrationCode ||
                    VatRegistrationCode != null &&
                    VatRegistrationCode.Equals(other.VatRegistrationCode)
                ) &&
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    RegistrationDate == other.RegistrationDate ||
                    RegistrationDate != null &&
                    RegistrationDate.Equals(other.RegistrationDate)
                ) &&
                (
                    DeletionDate == other.DeletionDate ||
                    DeletionDate != null &&
                    DeletionDate.Equals(other.DeletionDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (BugetCompanyNumber != null)
                    hashCode = hashCode * 59 + BugetCompanyNumber.GetHashCode();
                if (RegistrationCode != null)
                    hashCode = hashCode * 59 + RegistrationCode.GetHashCode();
                if (VatRegistrationCode != null)
                    hashCode = hashCode * 59 + VatRegistrationCode.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (RegistrationDate != null)
                    hashCode = hashCode * 59 + RegistrationDate.GetHashCode();
                if (DeletionDate != null)
                    hashCode = hashCode * 59 + DeletionDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(MiniCompanyDto left, MiniCompanyDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MiniCompanyDto left, MiniCompanyDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
