/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Enums
{

    /// <summary>
    /// Gets or Sets Languages
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum Languages
    {
        /// <summary>
        /// Enum CsCZEnum for cs_CZ
        /// </summary>
        [EnumMember(Value = "cs_CZ")]
        CsCZEnum = 0,
        /// <summary>
        /// Enum DeDEEnum for de_DE
        /// </summary>
        [EnumMember(Value = "de_DE")]
        DeDEEnum = 1,
        /// <summary>
        /// Enum EtEEEnum for et_EE
        /// </summary>
        [EnumMember(Value = "et_EE")]
        EtEEEnum = 2,
        /// <summary>
        /// Enum EnUSEnum for en_US
        /// </summary>
        [EnumMember(Value = "en_US")]
        EnUSEnum = 3,
        /// <summary>
        /// Enum FiFIEnum for fi_FI
        /// </summary>
        [EnumMember(Value = "fi_FI")]
        FiFIEnum = 4,
        /// <summary>
        /// Enum LtLTEnum for lt_LT
        /// </summary>
        [EnumMember(Value = "lt_LT")]
        LtLTEnum = 5,
        /// <summary>
        /// Enum LvLVEnum for lv_LV
        /// </summary>
        [EnumMember(Value = "lv_LV")]
        LvLVEnum = 6,
        /// <summary>
        /// Enum RuRUEnum for ru_RU
        /// </summary>
        [EnumMember(Value = "ru_RU")]
        RuRUEnum = 7,
        /// <summary>
        /// Enum SkSKEnum for sk_SK
        /// </summary>
        [EnumMember(Value = "sk_SK")]
        SkSKEnum = 8,
        /// <summary>
        /// Enum SrSCEnum for sr_SC
        /// </summary>
        [EnumMember(Value = "sr_SC")]
        SrSCEnum = 9,
        /// <summary>
        /// Enum SrSLEnum for sr_SL
        /// </summary>
        [EnumMember(Value = "sr_SL")]
        SrSLEnum = 10,
        /// <summary>
        /// Enum HuHUEnum for hu_HU
        /// </summary>
        [EnumMember(Value = "hu_HU")]
        HuHUEnum = 11,
        /// <summary>
        /// Enum PlPLEnum for pl_PL
        /// </summary>
        [EnumMember(Value = "pl_PL")]
        PlPLEnum = 12,
        /// <summary>
        /// Enum BgBGEnum for bg_BG
        /// </summary>
        [EnumMember(Value = "bg_BG")]
        BgBGEnum = 13,
        /// <summary>
        /// Enum HrHREnum for hr_HR
        /// </summary>
        [EnumMember(Value = "hr_HR")]
        HrHREnum = 14,
        /// <summary>
        /// Enum SlSIEnum for sl_SI
        /// </summary>
        [EnumMember(Value = "sl_SI")]
        SlSIEnum = 15
    }
}
