/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Enums
{

    /// <summary>
    /// Gets or Sets SourceInvoiceSelectionMode
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SourceInvoiceSelectionMode
    {
        /// <summary>
        /// Enum InvoiceSelectionEnum for InvoiceSelection
        /// </summary>
        [EnumMember(Value = "InvoiceSelection")]
        InvoiceSelectionEnum = 0,
        /// <summary>
        /// Enum PeriodSelectionEnum for PeriodSelection
        /// </summary>
        [EnumMember(Value = "PeriodSelection")]
        PeriodSelectionEnum = 1,
        /// <summary>
        /// Enum PrepaymentSelectionEnum for PrepaymentSelection
        /// </summary>
        [EnumMember(Value = "PrepaymentSelection")]
        PrepaymentSelectionEnum = 2
    }
}
