/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Cir
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CirTicketListResponse : IEquatable<CirTicketListResponse>
    {
        /// <summary>
        /// Gets or Sets Total
        /// </summary>

        [DataMember(Name = "total")]
        public int? Total { get; set; }

        /// <summary>
        /// Gets or Sets Tickets
        /// </summary>

        [DataMember(Name = "tickets")]
        public List<CirTicketDto> Tickets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CirTicketListResponse {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Tickets: ").Append(Tickets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CirTicketListResponse)obj);
        }

        /// <summary>
        /// Returns true if CirTicketListResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CirTicketListResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CirTicketListResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Total == other.Total ||
                    Total != null &&
                    Total.Equals(other.Total)
                ) &&
                (
                    Tickets == other.Tickets ||
                    Tickets != null &&
                    Tickets.SequenceEqual(other.Tickets)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Total != null)
                    hashCode = hashCode * 59 + Total.GetHashCode();
                if (Tickets != null)
                    hashCode = hashCode * 59 + Tickets.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CirTicketListResponse left, CirTicketListResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CirTicketListResponse left, CirTicketListResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
