/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace eFaktureModel.Api.Models.Cir
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CirTicketSearchEnumRestrictionItem : IEquatable<CirTicketSearchEnumRestrictionItem>
    {
        /// <summary>
        /// Gets or Sets Field
        /// </summary>

        [DataMember(Name = "field")]
        public CirTicketSearchEnum Field { get; set; }

        /// <summary>
        /// Gets or Sets Values
        /// </summary>

        [DataMember(Name = "values")]
        public List<string> Values { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CirTicketSearchEnumRestrictionItem {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CirTicketSearchEnumRestrictionItem)obj);
        }

        /// <summary>
        /// Returns true if CirTicketSearchEnumRestrictionItem instances are equal
        /// </summary>
        /// <param name="other">Instance of CirTicketSearchEnumRestrictionItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CirTicketSearchEnumRestrictionItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Field == other.Field ||
                    Field != null &&
                    Field.Equals(other.Field)
                ) &&
                (
                    Values == other.Values ||
                    Values != null &&
                    Values.SequenceEqual(other.Values)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Field != null)
                    hashCode = hashCode * 59 + Field.GetHashCode();
                if (Values != null)
                    hashCode = hashCode * 59 + Values.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CirTicketSearchEnumRestrictionItem left, CirTicketSearchEnumRestrictionItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CirTicketSearchEnumRestrictionItem left, CirTicketSearchEnumRestrictionItem right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
