/*
 * Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: public_v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using eFaktureModel.Api.Models.Invoices;

namespace eFaktureModel.Api.Models.Purchase
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PurchaseInvoiceOverviewDto : IEquatable<PurchaseInvoiceOverviewDto>
    {
        /// <summary>
        /// Gets or Sets InvoiceId
        /// </summary>

        [DataMember(Name = "invoiceId")]
        public long? InvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets GlobUniqId
        /// </summary>

        [DataMember(Name = "globUniqId")]
        public string GlobUniqId { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>

        [DataMember(Name = "invoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceType
        /// </summary>

        [DataMember(Name = "invoiceType")]
        public InvoiceTypes InvoiceType { get; set; }

        /// <summary>
        /// Gets or Sets CirInvoiceId
        /// </summary>

        [DataMember(Name = "cirInvoiceId")]
        public string CirInvoiceId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>

        [DataMember(Name = "status")]
        public PurchaseInvoiceStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets SupplierName
        /// </summary>

        [DataMember(Name = "supplierName")]
        public string SupplierName { get; set; }

        /// <summary>
        /// Gets or Sets SupplierRegistrationNumber
        /// </summary>

        [DataMember(Name = "supplierRegistrationNumber")]
        public string SupplierRegistrationNumber { get; set; }

        /// <summary>
        /// Gets or Sets SupplierVatRegistrationNumber
        /// </summary>

        [DataMember(Name = "supplierVatRegistrationNumber")]
        public string SupplierVatRegistrationNumber { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>

        [DataMember(Name = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>

        [DataMember(Name = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets DeliveryDate
        /// </summary>

        [DataMember(Name = "deliveryDate")]
        public DateTime? DeliveryDate { get; set; }

        /// <summary>
        /// Gets or Sets SentDate
        /// </summary>

        [DataMember(Name = "sentDate")]
        public DateTime? SentDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseInvoiceOverviewDto {\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  GlobUniqId: ").Append(GlobUniqId).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  InvoiceType: ").Append(InvoiceType).Append("\n");
            sb.Append("  CirInvoiceId: ").Append(CirInvoiceId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  SupplierName: ").Append(SupplierName).Append("\n");
            sb.Append("  SupplierRegistrationNumber: ").Append(SupplierRegistrationNumber).Append("\n");
            sb.Append("  SupplierVatRegistrationNumber: ").Append(SupplierVatRegistrationNumber).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  DeliveryDate: ").Append(DeliveryDate).Append("\n");
            sb.Append("  SentDate: ").Append(SentDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PurchaseInvoiceOverviewDto)obj);
        }

        /// <summary>
        /// Returns true if PurchaseInvoiceOverviewDto instances are equal
        /// </summary>
        /// <param name="other">Instance of PurchaseInvoiceOverviewDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseInvoiceOverviewDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    InvoiceId == other.InvoiceId ||
                    InvoiceId != null &&
                    InvoiceId.Equals(other.InvoiceId)
                ) &&
                (
                    GlobUniqId == other.GlobUniqId ||
                    GlobUniqId != null &&
                    GlobUniqId.Equals(other.GlobUniqId)
                ) &&
                (
                    InvoiceNumber == other.InvoiceNumber ||
                    InvoiceNumber != null &&
                    InvoiceNumber.Equals(other.InvoiceNumber)
                ) &&
                (
                    InvoiceType == other.InvoiceType ||
                    InvoiceType != null &&
                    InvoiceType.Equals(other.InvoiceType)
                ) &&
                (
                    CirInvoiceId == other.CirInvoiceId ||
                    CirInvoiceId != null &&
                    CirInvoiceId.Equals(other.CirInvoiceId)
                ) &&
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) &&
                (
                    SupplierName == other.SupplierName ||
                    SupplierName != null &&
                    SupplierName.Equals(other.SupplierName)
                ) &&
                (
                    SupplierRegistrationNumber == other.SupplierRegistrationNumber ||
                    SupplierRegistrationNumber != null &&
                    SupplierRegistrationNumber.Equals(other.SupplierRegistrationNumber)
                ) &&
                (
                    SupplierVatRegistrationNumber == other.SupplierVatRegistrationNumber ||
                    SupplierVatRegistrationNumber != null &&
                    SupplierVatRegistrationNumber.Equals(other.SupplierVatRegistrationNumber)
                ) &&
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) &&
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) &&
                (
                    DeliveryDate == other.DeliveryDate ||
                    DeliveryDate != null &&
                    DeliveryDate.Equals(other.DeliveryDate)
                ) &&
                (
                    SentDate == other.SentDate ||
                    SentDate != null &&
                    SentDate.Equals(other.SentDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (InvoiceId != null)
                    hashCode = hashCode * 59 + InvoiceId.GetHashCode();
                if (GlobUniqId != null)
                    hashCode = hashCode * 59 + GlobUniqId.GetHashCode();
                if (InvoiceNumber != null)
                    hashCode = hashCode * 59 + InvoiceNumber.GetHashCode();
                if (InvoiceType != null)
                    hashCode = hashCode * 59 + InvoiceType.GetHashCode();
                if (CirInvoiceId != null)
                    hashCode = hashCode * 59 + CirInvoiceId.GetHashCode();
                if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                if (SupplierName != null)
                    hashCode = hashCode * 59 + SupplierName.GetHashCode();
                if (SupplierRegistrationNumber != null)
                    hashCode = hashCode * 59 + SupplierRegistrationNumber.GetHashCode();
                if (SupplierVatRegistrationNumber != null)
                    hashCode = hashCode * 59 + SupplierVatRegistrationNumber.GetHashCode();
                if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                if (DeliveryDate != null)
                    hashCode = hashCode * 59 + DeliveryDate.GetHashCode();
                if (SentDate != null)
                    hashCode = hashCode * 59 + SentDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PurchaseInvoiceOverviewDto left, PurchaseInvoiceOverviewDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PurchaseInvoiceOverviewDto left, PurchaseInvoiceOverviewDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
